// This file was automatically generated.  Do not modify.

'use strict';

Blockly.Msg["ACTUATOR_BUZZER"] = "";  // untranslated
Blockly.Msg["ACTUATOR_BUZZER_FREQ"] = "";  // untranslated
Blockly.Msg["ACTUATOR_BUZZER_TONE"] = "";  // untranslated
Blockly.Msg["ACTUATOR_IRTX"] = "";  // untranslated
Blockly.Msg["ACTUATOR_IRTX_BITS"] = "";  // untranslated
Blockly.Msg["ACTUATOR_IRTX_CODE"] = "";  // untranslated
Blockly.Msg["ACTUATOR_IRTX_PROTOCOL"] = "";  // untranslated
Blockly.Msg["ACTUATOR_LED"] = "";  // untranslated
Blockly.Msg["ACTUATOR_LED_PWM"] = "";  // untranslated
Blockly.Msg["ACTUATOR_RELAY"] = "";  // untranslated
Blockly.Msg["ACTUATOR_RGBLED"] = "";  // untranslated
Blockly.Msg["ADDRESS"] = "";  // untranslated
Blockly.Msg["ADD_COMMENT"] = "Şərh əlavə et";
Blockly.Msg["ADD_NEW_LINE"] = "";  // untranslated
Blockly.Msg["AND"] = "";  // untranslated
Blockly.Msg["ANTICLOCKWISE"] = "";  // untranslated
Blockly.Msg["AS"] = "";  // untranslated
Blockly.Msg["AS_STRING"] = "";  // untranslated
Blockly.Msg["BACKWARD"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_AVAILABLE"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_BAUDRATE"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_DEVNAME"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_FLUSH"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_INIT"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_PIN"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_PRINT"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_PRINTLN"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READ"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READBYTE"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READFLOAT"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READINT"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READSTRING"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READSTRINGLINE"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_WRITEBYTE"] = "";  // untranslated
Blockly.Msg["BLYNK_APP_CONNECTED"] = "";  // untranslated
Blockly.Msg["BLYNK_APP_DISCONNECTED"] = "";  // untranslated
Blockly.Msg["BLYNK_APP_READ"] = "";  // untranslated
Blockly.Msg["BLYNK_APP_WRITE"] = "";  // untranslated
Blockly.Msg["BLYNK_AUTH"] = "";  // untranslated
Blockly.Msg["BLYNK_CONNECTED"] = "";  // untranslated
Blockly.Msg["BLYNK_INIT"] = "";  // untranslated
Blockly.Msg["BLYNK_LCD_CLEAR"] = "";  // untranslated
Blockly.Msg["BLYNK_LCD_PRINT"] = "";  // untranslated
Blockly.Msg["BLYNK_LED"] = "";  // untranslated
Blockly.Msg["BLYNK_LED_INTENSITY"] = "";  // untranslated
Blockly.Msg["BLYNK_LOCALPORT"] = "";  // untranslated
Blockly.Msg["BLYNK_LOCALSERVER"] = "";  // untranslated
Blockly.Msg["BLYNK_MAP"] = "";  // untranslated
Blockly.Msg["BLYNK_PARAM_READ_INT"] = "";  // untranslated
Blockly.Msg["BLYNK_PARAM_READ_STRING"] = "";  // untranslated
Blockly.Msg["BLYNK_SET_PROPERTY"] = "";  // untranslated
Blockly.Msg["BLYNK_TERMINAL_CLEAR"] = "";  // untranslated
Blockly.Msg["BLYNK_TERMINAL_PRINT"] = "";  // untranslated
Blockly.Msg["BLYNK_TIMER"] = "";  // untranslated
Blockly.Msg["BLYNK_VIRTUALWRITE"] = "";  // untranslated
Blockly.Msg["BLYNK_VPIN"] = "";  // untranslated
Blockly.Msg["BLYNK_VPIN_VALUE"] = "";  // untranslated
Blockly.Msg["CHANGE_VALUE_TITLE"] = "Qiyməti dəyiş:";
Blockly.Msg["CLEAN_UP"] = "Blokları təmizlə";
Blockly.Msg["CLOCKWISE"] = "";  // untranslated
Blockly.Msg["COLLAPSE_ALL"] = "Blokları yığ";
Blockly.Msg["COLLAPSE_BLOCK"] = "Bloku yığ";
Blockly.Msg["COLOUR"] = "";  // untranslated
Blockly.Msg["COL_BLUE"] = "";  // untranslated
Blockly.Msg["COL_GREEN"] = "";  // untranslated
Blockly.Msg["COL_RED"] = "";  // untranslated
Blockly.Msg["COMMON_ANODE"] = "";  // untranslated
Blockly.Msg["COMMON_CATHODE"] = "";  // untranslated
Blockly.Msg["CONTROLS_FOR_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg["CONTROLS_FOR_TITLE"] = "say: %1 %2 ilə başlayıb, %3 qiymətinə kimi %4 qədər dəyiş";
Blockly.Msg["CONTROLS_FOR_TOOLTIP"] = "\"%1\" dəyişəni başlanğıc ədəddən son ədədə qədər göstərilən aralıqla qiymətlər aldıqca göstərilən blokları yerinə yetir.";
Blockly.Msg["CONTROLS_IF_ELSEIF_TOOLTIP"] = "\"Əgər\" blokuna bir şərt əlavə et.";
Blockly.Msg["CONTROLS_IF_ELSE_TOOLTIP"] = "\"Əgər\" blokuna qalan bütün halları əhatə edəb son bir şərt əlavə et.";
Blockly.Msg["CONTROLS_IF_HELPURL"] = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg["CONTROLS_IF_IF_TOOLTIP"] = "Bu \"əgər\" blokunu dəyişdirmək üçün bölümlərin yenisini əlavə et, sil və ya yerini dəyiş.";
Blockly.Msg["CONTROLS_IF_MSG_ELSE"] = "əks halda";
Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"] = "əks halda əgər";
Blockly.Msg["CONTROLS_IF_MSG_IF"] = "əgər";
Blockly.Msg["CONTROLS_IF_TOOLTIP_1"] = "Əgər qiymət doğrudursa, onda bəzi əmrləri yerinə yetir.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_2"] = "Əgər qiymət doğrudursa, onda birinci əmrlər blokunu yerinə yetir. Əks halda isə ikinci əmrlər blokunu yerinə yetir.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_3"] = "Əgər birinci qiymət doğrudursa, onda birinci əmrlər blokunu yerinə yetir. Əks halda əgər ikinci qiymət doğrudursa, onda ikinci əmrlər blokunu yerinə yetir.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_4"] = "Əgər birinci qiymət doğrudursa, onda birinci əmrlər blokunu yerinə yetir. Əks halda əgər ikinci qiymət doğrudursa, onda ikinci əmrlər blokunu yerinə yetir. Əgər qiymətlərdən heç biri doğru deyilsə, onda axırıncı əmrlər blokunu yerinə yetir.";
Blockly.Msg["CONTROLS_REPEAT_HELPURL"] = "https://az.wikipedia.org/wiki/For_loop";
Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"] = "icra et";
Blockly.Msg["CONTROLS_REPEAT_TITLE"] = "%1 dəfə təkrar et";
Blockly.Msg["CONTROLS_REPEAT_TOOLTIP"] = "Bəzi əmrləri bir neçə dəfə yerinə yetir.";
Blockly.Msg["CONTROLS_WHILEUNTIL_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_UNTIL"] = "təkrar et, ta ki";
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_WHILE"] = "təkrar et, hələ ki";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL"] = "Hələ ki, qiymət \"yalan\"dır, bəzi əmrləri yerinə yetir.";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_WHILE"] = "Hələ ki, qiymət \"doğru\"dur, bəzi əmrləri yerinə yetir.";
Blockly.Msg["CONTROL_ARDUINO_LOOP"] = "";  // untranslated
Blockly.Msg["CONTROL_ARDUINO_SETUP"] = "";  // untranslated
Blockly.Msg["CONTROL_GROUP"] = "";  // untranslated
Blockly.Msg["DELETE_ALL_BLOCKS"] = "Bütün %1 blok silinsin?";
Blockly.Msg["DELETE_BLOCK"] = "Bloku sil";
Blockly.Msg["DELETE_X_BLOCKS"] = "%1 bloku sil";
Blockly.Msg["DEPRECATED"] = "";  // untranslated
Blockly.Msg["DISABLE_BLOCK"] = "Bloku söndür";
Blockly.Msg["DOMOTICS_INA219_CURRENT"] = "";  // untranslated
Blockly.Msg["DOMOTICS_INA219_INIT"] = "";  // untranslated
Blockly.Msg["DOMOTICS_INA219_POWER"] = "";  // untranslated
Blockly.Msg["DOMOTICS_INA219_VOLTAGE"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_CURRENT"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_ENERGY"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_FREQUENCY"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_INIT"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_POWER"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_POWERFACTOR"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_SETADDRESS"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_VALUE"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_VOLTAGE"] = "";  // untranslated
Blockly.Msg["DOWN"] = "";  // untranslated
Blockly.Msg["DUPLICATE_BLOCK"] = "Dublikat";
Blockly.Msg["EEPROM_ADDRESS"] = "";  // untranslated
Blockly.Msg["EEPROM_READ"] = "";  // untranslated
Blockly.Msg["EEPROM_WRITE"] = "";  // untranslated
Blockly.Msg["ENABLE_BLOCK"] = "Bloku aktivləşdir";
Blockly.Msg["EXPAND_ALL"] = "Blokları aç";
Blockly.Msg["EXPAND_BLOCK"] = "Bloku aç";
Blockly.Msg["EXTERNAL_INPUTS"] = "Xarici girişlər";
Blockly.Msg["FILTER_MEDIAN"] = "";  // untranslated
Blockly.Msg["FILTER_MEDIAN_ADD"] = "";  // untranslated
Blockly.Msg["FILTER_MEDIAN_SAMPLES"] = "";  // untranslated
Blockly.Msg["FILTER_MEDIAN_SETWINDOW"] = "";  // untranslated
Blockly.Msg["FORWARD"] = "";  // untranslated
Blockly.Msg["GPS_DAY"] = "";  // untranslated
Blockly.Msg["GPS_DISTANCEBETWEEN"] = "";  // untranslated
Blockly.Msg["GPS_GETALTITUDE"] = "";  // untranslated
Blockly.Msg["GPS_GETCOURSE"] = "";  // untranslated
Blockly.Msg["GPS_GETDATETIME"] = "";  // untranslated
Blockly.Msg["GPS_GETPOSITION"] = "";  // untranslated
Blockly.Msg["GPS_GETSPEED"] = "";  // untranslated
Blockly.Msg["GPS_HOUR"] = "";  // untranslated
Blockly.Msg["GPS_HUND"] = "";  // untranslated
Blockly.Msg["GPS_INIT"] = "";  // untranslated
Blockly.Msg["GPS_KMPH"] = "";  // untranslated
Blockly.Msg["GPS_LAT"] = "";  // untranslated
Blockly.Msg["GPS_LONG"] = "";  // untranslated
Blockly.Msg["GPS_MIN"] = "";  // untranslated
Blockly.Msg["GPS_MONTH"] = "";  // untranslated
Blockly.Msg["GPS_MPH"] = "";  // untranslated
Blockly.Msg["GPS_SEC"] = "";  // untranslated
Blockly.Msg["GPS_VALIDDATA"] = "";  // untranslated
Blockly.Msg["GPS_YEAR"] = "";  // untranslated
Blockly.Msg["HEIGHT"] = "";  // untranslated
Blockly.Msg["HELP"] = "Kömək";
Blockly.Msg["ID"] = "";  // untranslated
Blockly.Msg["INLINE_INPUTS"] = "Sətiriçi girişlər";
Blockly.Msg["IO_ANALOG_READ"] = "";  // untranslated
Blockly.Msg["IO_ANALOG_READ_DIF"] = "";  // untranslated
Blockly.Msg["IO_ANALOG_WRITE"] = "";  // untranslated
Blockly.Msg["IO_BOOLEAN_OFF"] = "";  // untranslated
Blockly.Msg["IO_BOOLEAN_ON"] = "";  // untranslated
Blockly.Msg["IO_CAPACITIVE_READ"] = "";  // untranslated
Blockly.Msg["IO_DIGITAL_READ"] = "";  // untranslated
Blockly.Msg["IO_DIGITAL_WRITE"] = "";  // untranslated
Blockly.Msg["IO_INTERRUPT"] = "";  // untranslated
Blockly.Msg["IO_PINMODE"] = "";  // untranslated
Blockly.Msg["IO_PINMODE_AS"] = "";  // untranslated
Blockly.Msg["IO_PULSEIN"] = "";  // untranslated
Blockly.Msg["IO_PULSEIN_TIMEOUT"] = "";  // untranslated
Blockly.Msg["KEYBOARD"] = "";  // untranslated
Blockly.Msg["KEYBOARD_KEY"] = "";  // untranslated
Blockly.Msg["KEYBOARD_KEYSTROKE"] = "";  // untranslated
Blockly.Msg["KEYBOARD_PRESS"] = "";  // untranslated
Blockly.Msg["KEYBOARD_RELEASE"] = "";  // untranslated
Blockly.Msg["KEYBOT_BUZZER"] = "";  // untranslated
Blockly.Msg["KEYBOT_BUZZER_FREQ"] = "";  // untranslated
Blockly.Msg["KEYBOT_DISTANCE"] = "";  // untranslated
Blockly.Msg["KEYBOT_IRSENSOR"] = "";  // untranslated
Blockly.Msg["KEYBOT_IRSENSOR_LEFT"] = "";  // untranslated
Blockly.Msg["KEYBOT_IRSENSOR_MIDDLE"] = "";  // untranslated
Blockly.Msg["KEYBOT_IRSENSOR_RIGHT"] = "";  // untranslated
Blockly.Msg["KEYBOT_LEFT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOTOR"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_BACKWARD"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_FAST"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_FORWARD"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_LEFT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_NORMAL"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_RIGHT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_ROTATE_LEFT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_ROTATE_RIGHT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_SLOW"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_SPEED"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_STOP"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_VERYFAST"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_VERYSLOW"] = "";  // untranslated
Blockly.Msg["KEYBOT_RIGHT"] = "";  // untranslated
Blockly.Msg["KEYPAD"] = "";  // untranslated
Blockly.Msg["KEYPAD_COL"] = "";  // untranslated
Blockly.Msg["KEYPAD_KEY"] = "";  // untranslated
Blockly.Msg["KEYPAD_NOKEY"] = "";  // untranslated
Blockly.Msg["KEYPAD_ROW"] = "";  // untranslated
Blockly.Msg["LCD"] = "";  // untranslated
Blockly.Msg["LCD_BACKLIGHT"] = "";  // untranslated
Blockly.Msg["LCD_BEGIN"] = "";  // untranslated
Blockly.Msg["LCD_BEGIN_I2C"] = "";  // untranslated
Blockly.Msg["LCD_BLINK"] = "";  // untranslated
Blockly.Msg["LCD_CLEAR"] = "";  // untranslated
Blockly.Msg["LCD_COL"] = "";  // untranslated
Blockly.Msg["LCD_CURSOR"] = "";  // untranslated
Blockly.Msg["LCD_DEFINE"] = "";  // untranslated
Blockly.Msg["LCD_DISPLAY"] = "";  // untranslated
Blockly.Msg["LCD_PRINT"] = "";  // untranslated
Blockly.Msg["LCD_ROW"] = "";  // untranslated
Blockly.Msg["LCD_SCROLL"] = "";  // untranslated
Blockly.Msg["LCD_SYMBOL"] = "";  // untranslated
Blockly.Msg["LEDMATRIX"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_CLEAR"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_DRAWBITMAP"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_DRAWCIRCLE"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_DRAWPIXEL"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_DRAWTEXT"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_FILL"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_INIT"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_LINE"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_RECTANGLE"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_ROTATION"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_ROUND"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_SHOW"] = "";  // untranslated
Blockly.Msg["LEFT"] = "";  // untranslated
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"] = "siyahı";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"] = "Bu siyahı blokunu yenidən konfigurasiya etmək üçün bölmələri əlavə edin, silin və ya yerlərini dəyişin.";
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH"] = "bunlardan siyahı düzəlt";
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH_TEXT"] = "";  // untranslated
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TOOLTIP"] = "Siyahıya element əlavə edin.";
Blockly.Msg["LISTS_GET_INDEX_FROM_START"] = "#";
Blockly.Msg["LISTS_GET_INDEX_GET"] = "götür";
Blockly.Msg["LISTS_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg["LISTS_LENGTH_TITLE"] = "%1 siyahısının uzunluğu";
Blockly.Msg["LISTS_LENGTH_TOOLTIP"] = "Siyahının uzunluğunu verir.";
Blockly.Msg["LISTS_LISTNAME"] = "";  // untranslated
Blockly.Msg["LISTS_LISTNAME_TEXT"] = "";  // untranslated
Blockly.Msg["LISTS_SET_INDEX_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg["LISTS_SET_INDEX_SET"] = "təyin et";
Blockly.Msg["LOGIC_BOOLEAN_FALSE"] = "səhf";
Blockly.Msg["LOGIC_BOOLEAN_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg["LOGIC_BOOLEAN_TOOLTIP"] = "\"doğru\" və ya \"səhf\" cavanını qaytarır.";
Blockly.Msg["LOGIC_BOOLEAN_TRUE"] = "doğru";
Blockly.Msg["LOGIC_COMPARE_HELPURL"] = "https://az.wikipedia.org/wiki/bərabərsizlik_(riyazi)";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_EQ"] = "Girişlər bir birinə bərabərdirsə \"doğru\" cavabını qaytarır.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GT"] = "Birinci giriş ikincidən böyükdürsə \"doğru\" cavabını qaytarır.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GTE"] = "Birinci giriş ikincidən böyük və ya bərarbərdirsə \"doğru\" cavabını qaytarır.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LT"] = "Birinci giriş ikincidən kiçikdirsə \"doğru\" cavabını qaytarır.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LTE"] = "Birinci giriş ikincidən kiçik və ya bərarbərdirsə \"doğru\" cavabını qaytarır.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_NEQ"] = "Girişlər bərabər deyillərsə \"doğru\" cavabını qaytarır.";
Blockly.Msg["LOGIC_NEGATE_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg["LOGIC_NEGATE_TITLE"] = "%1 deyil";
Blockly.Msg["LOGIC_NEGATE_TOOLTIP"] = "Giriş \"yalan\"-dursa \"doğru\" cavabını qaytarır. Giriş \"doğru\"-dursa \"səhf\" cavabını qaytarır.";
Blockly.Msg["LOGIC_OPERATION_AND"] = "və";
Blockly.Msg["LOGIC_OPERATION_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg["LOGIC_OPERATION_OR"] = "və ya";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_AND"] = "Hər iki giriş \"doğru\"-dursa \"doğru\" cavabını qaytarır.";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_OR"] = "Girişlərdən heç olmasa biri \"doğru\"-dursa \"doğru\" cavabını qaytarır.";
Blockly.Msg["MATH_ADDITION_SYMBOL"] = "+";
Blockly.Msg["MATH_ANGLE"] = "";  // untranslated
Blockly.Msg["MATH_ARITHMETIC_HELPURL"] = "https://az.wikipedia.org/wiki/Hesab";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_ADD"] = "İki ədədin cəmini qaytarır.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_DIVIDE"] = "İki ədədin nisbətini qaytarır.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MINUS"] = "İki ədədin fərqini qaytarır.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MULTIPLY"] = "İki ədədin hasilini verir.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_POWER"] = "Birinci ədədin ikinci ədəd dərəcəsindən qüvvətini qaytarır.";
Blockly.Msg["MATH_CHANGE_HELPURL"] = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
Blockly.Msg["MATH_CHANGE_TITLE"] = "dəyiş: %1 buna: %2";
Blockly.Msg["MATH_CHANGE_TOOLTIP"] = "'%1' dəyişəninin üzərinə bir ədəd artır.";
Blockly.Msg["MATH_CONSTANT_HELPURL"] = "https://az.wikipedia.org/wiki/Riyazi_sabitlər";
Blockly.Msg["MATH_CONSTANT_TOOLTIP"] = "Ümumi sabitlərdən birini qaytarır π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), və ya ∞ (sonsuzluq).";
Blockly.Msg["MATH_CONSTRAIN_HELPURL"] = "https://en.wikipedia.org/wiki/Clamping_(graphics)";  // untranslated
Blockly.Msg["MATH_CONSTRAIN_TITLE"] = "%1 üçün ən aşağı %2, ən yuxarı %3 olmağı tələb et";
Blockly.Msg["MATH_CONSTRAIN_TOOLTIP"] = "Bir ədədin verilmiş iki ədəd arasında olmasını tələb edir (sərhədlər də daxil olmaqla).";
Blockly.Msg["MATH_DIVISION_SYMBOL"] = "÷";
Blockly.Msg["MATH_MAP_HELPURL"] = "";  // untranslated
Blockly.Msg["MATH_MAP_TITLE"] = "";  // untranslated
Blockly.Msg["MATH_MAP_TOOLTIP"] = "";  // untranslated
Blockly.Msg["MATH_MODULO_HELPURL"] = "https://en.wikipedia.org/wiki/Modulo_operation";
Blockly.Msg["MATH_MODULO_TITLE"] = "%1 ÷ %2 bölməsinin qalığı";
Blockly.Msg["MATH_MODULO_TOOLTIP"] = "İki ədədin nisbətindən alınan qalığı qaytarır.";
Blockly.Msg["MATH_MULTIPLICATION_SYMBOL"] = "×";
Blockly.Msg["MATH_NUMBER_HELPURL"] = "https://az.wikipedia.org/wiki/Ədəd";
Blockly.Msg["MATH_NUMBER_TOOLTIP"] = "Ədəd.";
Blockly.Msg["MATH_POWER_SYMBOL"] = "^";
Blockly.Msg["MATH_RANDOM_INT_HELPURL"] = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg["MATH_RANDOM_INT_TITLE"] = "%1 ilə %2 arasından təsadüfi tam ədəd";
Blockly.Msg["MATH_RANDOM_INT_TOOLTIP"] = "Verilmiş iki ədəd arasından (ədədrlər də daxil olmaqla) təsadüfi bir tam ədəd qaytarır.";
Blockly.Msg["MATH_ROUND_HELPURL"] = "https://en.wikipedia.org/wiki/Rounding";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUND"] = "yuvarlaqlaşdır";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDDOWN"] = "aşağı yuvarlaqlaşdır";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDUP"] = "yuxarı yuvarlaqlaşdır";
Blockly.Msg["MATH_ROUND_TOOLTIP"] = "Ədədi aşağı və ya yuxari yuvarlaqşdır.";
Blockly.Msg["MATH_SINGLE_HELPURL"] = "https://az.wikipedia.org/wiki/Kvadrat_kökləri";
Blockly.Msg["MATH_SINGLE_OP_ABSOLUTE"] = "modul";
Blockly.Msg["MATH_SINGLE_OP_ROOT"] = "kvadrat kök";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ABS"] = "Ədədin modulunu qaytarır.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_EXP"] = "e sabitinin verilmiş ədədə qüvvətini qaytarır.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LN"] = "Ədədin natural loqarifmini tapır.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LOG10"] = "Ədədin 10-cu dərəcədən loqarifmini tapır.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_NEG"] = "Ədədin əksini qaytarır.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_POW10"] = "10-un verilmiş ədədə qüvvətini qaytarır.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ROOT"] = "Ədədin kvadrat kökünü qaytarır.";
Blockly.Msg["MATH_SUBTRACTION_SYMBOL"] = "-";
Blockly.Msg["MATH_TO_INT"] = "";  // untranslated
Blockly.Msg["MATH_TO_UINT"] = "";  // untranslated
Blockly.Msg["MATH_TRIG_ACOS"] = "arccos";
Blockly.Msg["MATH_TRIG_ASIN"] = "arcsin";
Blockly.Msg["MATH_TRIG_ATAN"] = "arctan";
Blockly.Msg["MATH_TRIG_ATAN2"] = "";  // untranslated
Blockly.Msg["MATH_TRIG_COS"] = "cos";
Blockly.Msg["MATH_TRIG_HELPURL"] = "https://az.wikipedia.org/wiki/Triqonometrik_funksiyalar";
Blockly.Msg["MATH_TRIG_SIN"] = "sin";
Blockly.Msg["MATH_TRIG_TAN"] = "tg";
Blockly.Msg["MATH_TRIG_TOOLTIP_ACOS"] = "Ədədin arccosinusunu qaytarır.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ASIN"] = "Ədədin arcsinusunu qaytarır.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ATAN"] = "Ədədin arctanqensini qaytarır.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ATAN2"] = "";  // untranslated
Blockly.Msg["MATH_TRIG_TOOLTIP_COS"] = "Dərəcənin kosinusunu qaytarır (radianın yox).";
Blockly.Msg["MATH_TRIG_TOOLTIP_SIN"] = "Dərəcənin sinusunu qaytar (radianın yox).";
Blockly.Msg["MATH_TRIG_TOOLTIP_TAN"] = "Dərəcənin tangensini qaytar (radianın yox).";
Blockly.Msg["MOTORSHIELD_DC"] = "";  // untranslated
Blockly.Msg["MOTORSHIELD_SERVO"] = "";  // untranslated
Blockly.Msg["MOTORSHIELD_STEPPER"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_BW"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_FW"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_INIT"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_MOTOR"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_MOVE"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_SPEED"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298P"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_DEGREE_RANGE"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_DELAY"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_AMPLITUDE"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_OFFSET"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_PERIOD"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_PHASE"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_REFRESH"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_RESET"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_SET"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_START"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_STOP"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_READ"] = "";  // untranslated
Blockly.Msg["MOTOR_STEPPER"] = "";  // untranslated
Blockly.Msg["MOTOR_STEPPER_RPM"] = "";  // untranslated
Blockly.Msg["MOTOR_STEPPER_STEP"] = "";  // untranslated
Blockly.Msg["MOTOR_STEPPER_STEPS"] = "";  // untranslated
Blockly.Msg["MOUSE"] = "";  // untranslated
Blockly.Msg["MOUSE_BUTTON"] = "";  // untranslated
Blockly.Msg["MOUSE_CLICK"] = "";  // untranslated
Blockly.Msg["MOUSE_MIDDLE"] = "";  // untranslated
Blockly.Msg["MOUSE_MOVE"] = "";  // untranslated
Blockly.Msg["MOUSE_WHEEL"] = "";  // untranslated
Blockly.Msg["MP3_CONTROL"] = "";  // untranslated
Blockly.Msg["MP3_EQ"] = "";  // untranslated
Blockly.Msg["MP3_FILE"] = "";  // untranslated
Blockly.Msg["MP3_FOLDER"] = "";  // untranslated
Blockly.Msg["MP3_INIT"] = "";  // untranslated
Blockly.Msg["MP3_NEXT"] = "";  // untranslated
Blockly.Msg["MP3_PAUSE"] = "";  // untranslated
Blockly.Msg["MP3_PLAY"] = "";  // untranslated
Blockly.Msg["MP3_PREV"] = "";  // untranslated
Blockly.Msg["MP3_REPEAT"] = "";  // untranslated
Blockly.Msg["MP3_RESET"] = "";  // untranslated
Blockly.Msg["MP3_SHUFFLE"] = "";  // untranslated
Blockly.Msg["MP3_STOP"] = "";  // untranslated
Blockly.Msg["MP3_VOLUME"] = "";  // untranslated
Blockly.Msg["MQTT_BROKER"] = "";  // untranslated
Blockly.Msg["MQTT_CLIENTID"] = "";  // untranslated
Blockly.Msg["MQTT_INIT"] = "";  // untranslated
Blockly.Msg["MQTT_ISCONNECTED"] = "";  // untranslated
Blockly.Msg["MQTT_MAC"] = "";  // untranslated
Blockly.Msg["MQTT_PASS"] = "";  // untranslated
Blockly.Msg["MQTT_PORT"] = "";  // untranslated
Blockly.Msg["MQTT_PUB"] = "";  // untranslated
Blockly.Msg["MQTT_SUB"] = "";  // untranslated
Blockly.Msg["MQTT_TOPIC"] = "";  // untranslated
Blockly.Msg["MQTT_USER"] = "";  // untranslated
Blockly.Msg["MQTT_VALUE"] = "";  // untranslated
Blockly.Msg["MQTT_WIFI_NAME"] = "";  // untranslated
Blockly.Msg["MQTT_WIFI_PASS"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_CLEAR"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_INIT"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_LEDCOUNT"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_PIXEL"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_SETMATRIX"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_SETPIXEL"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_SETRAW"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_SHOW"] = "";  // untranslated
Blockly.Msg["NEW_VARIABLE"] = "Yeni dəyişən...";
Blockly.Msg["NEW_VARIABLE_TITLE"] = "Yeni dəyişənin adı:";
Blockly.Msg["NOTE_A"] = "";  // untranslated
Blockly.Msg["NOTE_AS"] = "";  // untranslated
Blockly.Msg["NOTE_B"] = "";  // untranslated
Blockly.Msg["NOTE_C"] = "";  // untranslated
Blockly.Msg["NOTE_CS"] = "";  // untranslated
Blockly.Msg["NOTE_D"] = "";  // untranslated
Blockly.Msg["NOTE_DS"] = "";  // untranslated
Blockly.Msg["NOTE_E"] = "";  // untranslated
Blockly.Msg["NOTE_F"] = "";  // untranslated
Blockly.Msg["NOTE_FS"] = "";  // untranslated
Blockly.Msg["NOTE_G"] = "";  // untranslated
Blockly.Msg["NOTE_GS"] = "";  // untranslated
Blockly.Msg["NUMBER"] = "";  // untranslated
Blockly.Msg["NUNCHUK"] = "";  // untranslated
Blockly.Msg["NUNCHUK_X"] = "";  // untranslated
Blockly.Msg["NUNCHUK_Y"] = "";  // untranslated
Blockly.Msg["NUNCHUK_aX"] = "";  // untranslated
Blockly.Msg["NUNCHUK_aY"] = "";  // untranslated
Blockly.Msg["NUNCHUK_aZ"] = "";  // untranslated
Blockly.Msg["NUNCHUK_bC"] = "";  // untranslated
Blockly.Msg["NUNCHUK_bZ"] = "";  // untranslated
Blockly.Msg["OK"] = "";  // untranslated
Blockly.Msg["OLED_AUTOSHOW"] = "";  // untranslated
Blockly.Msg["OTTO_AMP"] = "";  // untranslated
Blockly.Msg["OTTO_AMP_BIG"] = "";  // untranslated
Blockly.Msg["OTTO_AMP_NORMAL"] = "";  // untranslated
Blockly.Msg["OTTO_AMP_SMALL"] = "";  // untranslated
Blockly.Msg["OTTO_BUTTON"] = "";  // untranslated
Blockly.Msg["OTTO_CALIBRATE"] = "";  // untranslated
Blockly.Msg["OTTO_CALIB_FOOTL"] = "";  // untranslated
Blockly.Msg["OTTO_CALIB_FOOTR"] = "";  // untranslated
Blockly.Msg["OTTO_CALIB_LEGL"] = "";  // untranslated
Blockly.Msg["OTTO_CALIB_LEGR"] = "";  // untranslated
Blockly.Msg["OTTO_DISTANCE"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_ANGRY"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_CONFUSED"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_FAIL"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_FART"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_FRETFUL"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_HAPPY"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_LOVE"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_MAGIC"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_SAD"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_SLEEPING"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_SUPERHAPPY"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_VICTORY"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_WAVE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_ANGRY"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_BIGSURPRISE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_CLEAR"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_CONFUSED"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_CULITO"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_DIAGONAL"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_EIGHT"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_FIVE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_FOUR"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_HAPPYCLOSED"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_HAPPYOPEN"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_HEART"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_INTERROGATION"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_LINEMOUTH"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_NINE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_OKMOUTH"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_ONE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SAD"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SADCLOSED"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SADOPEN"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SEVEN"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SIX"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SMALLSURPRISE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SMILE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_THREE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_THUNDER"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_TONGUEOUT"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_TWO"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_VAMP1"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_VAMP2"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_XMOUTH"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_ZERO"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE2"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_ASCTURN"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_BENDL"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_BENDR"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_CRUSAITO1"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_CRUSAITO2"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_FLAPPING1"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_FLAPPING2"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_HOME"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_JITTER"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_JUMP"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_MOONWALKL"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_MOONWALKR"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_SHAKEL"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_SHAKER"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_SWING"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_TIPTOESWING"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_TURNL"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_TURNR"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_UPDOWN"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_WALKB"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_WALKF"] = "";  // untranslated
Blockly.Msg["OTTO_NOISE"] = "";  // untranslated
Blockly.Msg["OTTO_NOTE"] = "";  // untranslated
Blockly.Msg["OTTO_NOTE_DURATION"] = "";  // untranslated
Blockly.Msg["OTTO_SING"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_BUTTON"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_CONFUSED"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_CONNECTION"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_CUDDLY"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_DISCONNECTION"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_FART1"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_FART2"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_FART3"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_HAPPY"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_HAPPYSHOR"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_MODE1"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_MODE2"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_MODE3"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_OH2"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_OH_"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_SAD"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_SLEEPING"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_SUPERHAPPY"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_SURPRISE"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_FAST"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_NORMAL"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_SLOW"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_VERYFAST"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_VERYSLOW"] = "";  // untranslated
Blockly.Msg["PIN"] = "";  // untranslated
Blockly.Msg["PRESSED"] = "";  // untranslated
Blockly.Msg["PROCEDURES_ALLOW_STATEMENTS"] = "operatorlara icazə";
Blockly.Msg["PROCEDURES_BEFORE_PARAMS"] = "ilə:";
Blockly.Msg["PROCEDURES_CALLNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";
Blockly.Msg["PROCEDURES_CALLNORETURN_TOOLTIP"] = "Yaradılmış '%1' funksiyasını çalışdır.";
Blockly.Msg["PROCEDURES_CALLRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";
Blockly.Msg["PROCEDURES_CALLRETURN_TOOLTIP"] = "Yaradılmış '%1' funksiyasını çalışdır və nəticəni istifadə et.";
Blockly.Msg["PROCEDURES_CALL_BEFORE_PARAMS"] = "ilə:";
Blockly.Msg["PROCEDURES_CREATE_DO"] = "'%1' yarat";
Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"] = "Bu funksiyanı təsvir et";
Blockly.Msg["PROCEDURES_DEFNORETURN_DO"] = "";  // untranslated
Blockly.Msg["PROCEDURES_DEFNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"] = "hansısa əməliyyat";
Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"] = "icra et:";
Blockly.Msg["PROCEDURES_DEFNORETURN_TOOLTIP"] = "Nəticəsi olmayan funksiya yaradır.";
Blockly.Msg["PROCEDURES_DEFRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
Blockly.Msg["PROCEDURES_DEFRETURN_RETURN"] = "qaytar";
Blockly.Msg["PROCEDURES_DEFRETURN_TOOLTIP"] = "Nəticəsi olan funksiya yaradır.";
Blockly.Msg["PROCEDURES_DEF_DUPLICATE_WARNING"] = "Xəbərdarlıq: Bu funksiyanın təkrar olunmuş parametrləri var.";
Blockly.Msg["PROCEDURES_HIGHLIGHT_DEF"] = "Funksiyanın təyinatını vurğula";
Blockly.Msg["PROCEDURES_MUTATORARG_TITLE"] = "Giriş adı:";
Blockly.Msg["PROCEDURES_MUTATORARG_TOOLTIP"] = "Funksiyaya giriş parametrləri əlavə et.";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TITLE"] = "girişlər";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TOOLTIP"] = "Bu funksiyanın giriş parametrləri üçün əlavə et, sil, və ya yenilə.";
Blockly.Msg["REMOVE_COMMENT"] = "Şərhi sil";
Blockly.Msg["RENAME_VARIABLE"] = "Dəyişənin adını dəyiş...";
Blockly.Msg["RENAME_VARIABLE_TITLE"] = "Bütün '%1' dəyişənlərinin adını buna dəyiş:";
Blockly.Msg["RFID_EJECTCARD"] = "";  // untranslated
Blockly.Msg["RFID_INIT"] = "";  // untranslated
Blockly.Msg["RFID_NEWCARDPRESENT"] = "";  // untranslated
Blockly.Msg["RFID_READUID"] = "";  // untranslated
Blockly.Msg["RIGHT"] = "";  // untranslated
Blockly.Msg["RTC"] = "";  // untranslated
Blockly.Msg["RTC_DATE_TEXT"] = "";  // untranslated
Blockly.Msg["RTC_DAY"] = "";  // untranslated
Blockly.Msg["RTC_DAYOFWEEK"] = "";  // untranslated
Blockly.Msg["RTC_FRIDAY"] = "";  // untranslated
Blockly.Msg["RTC_HOUR"] = "";  // untranslated
Blockly.Msg["RTC_MINUTE"] = "";  // untranslated
Blockly.Msg["RTC_MONDAY"] = "";  // untranslated
Blockly.Msg["RTC_MONTH"] = "";  // untranslated
Blockly.Msg["RTC_SATURDAY"] = "";  // untranslated
Blockly.Msg["RTC_SECOND"] = "";  // untranslated
Blockly.Msg["RTC_SUNDAY"] = "";  // untranslated
Blockly.Msg["RTC_THURSDAY"] = "";  // untranslated
Blockly.Msg["RTC_TIME_TEXT"] = "";  // untranslated
Blockly.Msg["RTC_TUESDAY"] = "";  // untranslated
Blockly.Msg["RTC_WEDNESDAY"] = "";  // untranslated
Blockly.Msg["RTC_YEAR"] = "";  // untranslated
Blockly.Msg["SD_BEGIN"] = "";  // untranslated
Blockly.Msg["SD_EXISTS"] = "";  // untranslated
Blockly.Msg["SD_POS"] = "";  // untranslated
Blockly.Msg["SD_PRINT"] = "";  // untranslated
Blockly.Msg["SD_READBYTE"] = "";  // untranslated
Blockly.Msg["SD_READLOOP"] = "";  // untranslated
Blockly.Msg["SD_REMOVE"] = "";  // untranslated
Blockly.Msg["SD_SIZE"] = "";  // untranslated
Blockly.Msg["SD_WRITEBYTE"] = "";  // untranslated
Blockly.Msg["SENSOR_18B20"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL_ADXL345"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL_X"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL_Y"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL_Z"] = "";  // untranslated
Blockly.Msg["SENSOR_AIR"] = "";  // untranslated
Blockly.Msg["SENSOR_ALCOHOL"] = "";  // untranslated
Blockly.Msg["SENSOR_ALTITUDE"] = "";  // untranslated
Blockly.Msg["SENSOR_BAROMETRIC"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON_DEBOUNCED"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON_DEBOUNCED_PRESSED"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON_DEBOUNCED_RELEASED"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON_INVERT"] = "";  // untranslated
Blockly.Msg["SENSOR_CCS811"] = "";  // untranslated
Blockly.Msg["SENSOR_CCS811_CO2"] = "";  // untranslated
Blockly.Msg["SENSOR_CCS811_CO2_UGM3"] = "";  // untranslated
Blockly.Msg["SENSOR_CCS811_TVOC"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_BLACK"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_BLUE"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_CYAN"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_GREEN"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_HSV_H"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_HSV_S"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_HSV_V"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_ISCOLOR"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_NAME"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_ORANGE"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_PURPLE"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_READCOLOR"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RED"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RGB_B"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RGB_CLEAR"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RGB_G"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RGB_R"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_WHITE"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_YELLOW"] = "";  // untranslated
Blockly.Msg["SENSOR_CRASH"] = "";  // untranslated
Blockly.Msg["SENSOR_DATA_RAW"] = "";  // untranslated
Blockly.Msg["SENSOR_DHT11"] = "";  // untranslated
Blockly.Msg["SENSOR_DHT22"] = "";  // untranslated
Blockly.Msg["SENSOR_DS18B20"] = "";  // untranslated
Blockly.Msg["SENSOR_FLAME"] = "";  // untranslated
Blockly.Msg["SENSOR_GAS"] = "";  // untranslated
Blockly.Msg["SENSOR_HALL"] = "";  // untranslated
Blockly.Msg["SENSOR_HUMIDITY"] = "";  // untranslated
Blockly.Msg["SENSOR_IRRX"] = "";  // untranslated
Blockly.Msg["SENSOR_JOYSTICK"] = "";  // untranslated
Blockly.Msg["SENSOR_KNOCK"] = "";  // untranslated
Blockly.Msg["SENSOR_LDR"] = "";  // untranslated
Blockly.Msg["SENSOR_LINETRACKING"] = "";  // untranslated
Blockly.Msg["SENSOR_LM35"] = "";  // untranslated
Blockly.Msg["SENSOR_MICS4514"] = "";  // untranslated
Blockly.Msg["SENSOR_MLX90614"] = "";  // untranslated
Blockly.Msg["SENSOR_MLX90614_AMBIENT"] = "";  // untranslated
Blockly.Msg["SENSOR_MLX90614_OBJECT"] = "";  // untranslated
Blockly.Msg["SENSOR_NTC"] = "";  // untranslated
Blockly.Msg["SENSOR_OBSTACLE"] = "";  // untranslated
Blockly.Msg["SENSOR_PAJ7620"] = "";  // untranslated
Blockly.Msg["SENSOR_PHOTOINT"] = "";  // untranslated
Blockly.Msg["SENSOR_PIR"] = "";  // untranslated
Blockly.Msg["SENSOR_PM25"] = "";  // untranslated
Blockly.Msg["SENSOR_PM25_DENSITY"] = "";  // untranslated
Blockly.Msg["SENSOR_PM25_PARTICLESM3"] = "";  // untranslated
Blockly.Msg["SENSOR_POT"] = "";  // untranslated
Blockly.Msg["SENSOR_PRESSURE"] = "";  // untranslated
Blockly.Msg["SENSOR_REED"] = "";  // untranslated
Blockly.Msg["SENSOR_ROTARY_ENCODER"] = "";  // untranslated
Blockly.Msg["SENSOR_ROTARY_ENCODER_POS"] = "";  // untranslated
Blockly.Msg["SENSOR_SOILHUMIDITY"] = "";  // untranslated
Blockly.Msg["SENSOR_SOUND"] = "";  // untranslated
Blockly.Msg["SENSOR_TEMPERATURE"] = "";  // untranslated
Blockly.Msg["SENSOR_TEMT6000"] = "";  // untranslated
Blockly.Msg["SENSOR_TILT"] = "";  // untranslated
Blockly.Msg["SENSOR_TMP36"] = "";  // untranslated
Blockly.Msg["SENSOR_TOUCH"] = "";  // untranslated
Blockly.Msg["SENSOR_ULTRASONIC"] = "";  // untranslated
Blockly.Msg["SENSOR_ULTRASONIC_MAXDISTANCE"] = "";  // untranslated
Blockly.Msg["SENSOR_VIBRATION"] = "";  // untranslated
Blockly.Msg["SENSOR_VL53L0X"] = "";  // untranslated
Blockly.Msg["SENSOR_WATER"] = "";  // untranslated
Blockly.Msg["SERIAL_AVAILABLE"] = "";  // untranslated
Blockly.Msg["SERIAL_BAUDRATE"] = "";  // untranslated
Blockly.Msg["SERIAL_FLUSH"] = "";  // untranslated
Blockly.Msg["SERIAL_INIT"] = "";  // untranslated
Blockly.Msg["SERIAL_INT"] = "";  // untranslated
Blockly.Msg["SERIAL_PLOT"] = "";  // untranslated
Blockly.Msg["SERIAL_PLOTVALUE"] = "";  // untranslated
Blockly.Msg["SERIAL_PLOTVAR"] = "";  // untranslated
Blockly.Msg["SERIAL_PRINT"] = "";  // untranslated
Blockly.Msg["SERIAL_PRINTLN"] = "";  // untranslated
Blockly.Msg["SERIAL_READ"] = "";  // untranslated
Blockly.Msg["SERIAL_READBYTE"] = "";  // untranslated
Blockly.Msg["SERIAL_READFLOAT"] = "";  // untranslated
Blockly.Msg["SERIAL_READINT"] = "";  // untranslated
Blockly.Msg["SERIAL_READSTRING"] = "";  // untranslated
Blockly.Msg["SERIAL_READSTRINGLINE"] = "";  // untranslated
Blockly.Msg["SERIAL_TIMEOUT"] = "";  // untranslated
Blockly.Msg["SERIAL_WRITEBYTE"] = "";  // untranslated
Blockly.Msg["SHOP"] = "";  // untranslated
Blockly.Msg["SOUND_FREQ"] = "";  // untranslated
Blockly.Msg["SOUND_NOTE"] = "";  // untranslated
Blockly.Msg["SOUND_NOTONE"] = "";  // untranslated
Blockly.Msg["SOUND_PLAY"] = "";  // untranslated
Blockly.Msg["SOUND_TONE"] = "";  // untranslated
Blockly.Msg["STATUS"] = "";  // untranslated
Blockly.Msg["TEXT"] = "";  // untranslated
Blockly.Msg["TEXT_ASCII"] = "";  // untranslated
Blockly.Msg["TEXT_COMMENT"] = "";  // untranslated
Blockly.Msg["TEXT_CONTAINS"] = "";  // untranslated
Blockly.Msg["TEXT_CONTAINS_1"] = "";  // untranslated
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TOOLTIP"] = "Mətnə bir element əlavə et.";
Blockly.Msg["TEXT_CREATE_JOIN_TITLE_JOIN"] = "birləşdir";
Blockly.Msg["TEXT_CREATE_JOIN_TOOLTIP"] = "Bu mətn blokunu yenidən konfigurasiya etmək üçün bölmələri əlavə edin, silin və ya yerlərini dəyişin.";
Blockly.Msg["TEXT_DECIMAL"] = "";  // untranslated
Blockly.Msg["TEXT_ENDSWITH"] = "";  // untranslated
Blockly.Msg["TEXT_EQUALS"] = "";  // untranslated
Blockly.Msg["TEXT_EQUALS_IGNORE"] = "";  // untranslated
Blockly.Msg["TEXT_FORMAT"] = "";  // untranslated
Blockly.Msg["TEXT_INDEXOF"] = "";  // untranslated
Blockly.Msg["TEXT_INDEXOF_1"] = "";  // untranslated
Blockly.Msg["TEXT_INDEXOF_FIRST"] = "";  // untranslated
Blockly.Msg["TEXT_INDEXOF_LAST"] = "";  // untranslated
Blockly.Msg["TEXT_JOIN_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg["TEXT_JOIN_TITLE_CREATEWITH"] = "Verilmişlərlə mətn yarat";
Blockly.Msg["TEXT_JOIN_TOOLTIP"] = "İxtiyari sayda elementlərinin birləşməsi ilə mətn parçası yarat.";
Blockly.Msg["TEXT_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg["TEXT_LENGTH_TITLE"] = "%1 - ın uzunluğu";
Blockly.Msg["TEXT_LENGTH_TOOLTIP"] = "Verilmiş mətndəki hərflərin(sözlər arası boşluqlar sayılmaqla) sayını qaytarır.";
Blockly.Msg["TEXT_LOWERCASE"] = "";  // untranslated
Blockly.Msg["TEXT_NOT_EQUALS"] = "";  // untranslated
Blockly.Msg["TEXT_REPLACE"] = "";  // untranslated
Blockly.Msg["TEXT_REPLACE_1"] = "";  // untranslated
Blockly.Msg["TEXT_REPLACE_2"] = "";  // untranslated
Blockly.Msg["TEXT_STARTSWITH"] = "";  // untranslated
Blockly.Msg["TEXT_SUBSTRING"] = "";  // untranslated
Blockly.Msg["TEXT_SUBSTRING_1"] = "";  // untranslated
Blockly.Msg["TEXT_SUBSTRING_2"] = "";  // untranslated
Blockly.Msg["TEXT_TEXT_HELPURL"] = "https://en.wikipedia.org/wiki/String_(computer_science)";
Blockly.Msg["TEXT_TEXT_TOOLTIP"] = "Mətndəki hərf, söz və ya sətir.";
Blockly.Msg["TEXT_TONUMBER"] = "";  // untranslated
Blockly.Msg["TEXT_UPPERCASE"] = "";  // untranslated
Blockly.Msg["TIME_MICROS"] = "";  // untranslated
Blockly.Msg["TIME_MILLIS"] = "";  // untranslated
Blockly.Msg["TIME_RUNEVERYMS"] = "";  // untranslated
Blockly.Msg["TIME_SNOOZE"] = "";  // untranslated
Blockly.Msg["TIME_TIMER"] = "";  // untranslated
Blockly.Msg["TIME_TIMER_RESET"] = "";  // untranslated
Blockly.Msg["TIME_TIME_ELAPSED"] = "";  // untranslated
Blockly.Msg["TIME_WAIT"] = "";  // untranslated
Blockly.Msg["TIME_WAIT_FOREVER"] = "";  // untranslated
Blockly.Msg["TIME_WAIT_UNTIL"] = "";  // untranslated
Blockly.Msg["TIME_WAIT_WHILE"] = "";  // untranslated
Blockly.Msg["TO"] = "";  // untranslated
Blockly.Msg["TODAY"] = "Bugün";
Blockly.Msg["UNTIL_NEW_LINE"] = "";  // untranslated
Blockly.Msg["UP"] = "";  // untranslated
Blockly.Msg["VALUE"] = "";  // untranslated
Blockly.Msg["VARIABLES_DEFAULT_NAME"] = "element";
Blockly.Msg["VARIABLES_DEFAULT_NAME_BOOL"] = "";  // untranslated
Blockly.Msg["VARIABLES_DEFAULT_NAME_TEXT"] = "";  // untranslated
Blockly.Msg["VARIABLES_GET_CREATE_SET"] = "'%1 - i təyin et' - i yarat";
Blockly.Msg["VARIABLES_GET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg["VARIABLES_GET_TOOLTIP"] = "Bu dəyişənin qiymətini qaytarır.";
Blockly.Msg["VARIABLES_SET"] = "%1 - i bu qiymət ilə təyin et: %2";
Blockly.Msg["VARIABLES_SET_CREATE_GET"] = "'%1 - i götür' - ü yarat";
Blockly.Msg["VARIABLES_SET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg["VARIABLES_SET_TOOLTIP"] = "Bu dəyişəni daxil edilmiş qiymətə bərabər edir.";
Blockly.Msg["WAVE"] = "";  // untranslated
Blockly.Msg["WIDTH"] = "";  // untranslated
Blockly.Msg["WIFI_NAME"] = "";  // untranslated
Blockly.Msg["WIFI_PASS"] = "";  // untranslated
Blockly.Msg["WITH"] = "";  // untranslated
Blockly.Msg["_3DBOT_BUTTON"] = "";  // untranslated
Blockly.Msg["_3DBOT_BUZZER"] = "";  // untranslated
Blockly.Msg["_3DBOT_BUZZER_FREQ"] = "";  // untranslated
Blockly.Msg["_3DBOT_DISTANCE"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRRX"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRSENSOR"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRSENSOR_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRSENSOR_MIDDLE"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRSENSOR_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRTX"] = "";  // untranslated
Blockly.Msg["_3DBOT_LDR"] = "";  // untranslated
Blockly.Msg["_3DBOT_LED_GREEN"] = "";  // untranslated
Blockly.Msg["_3DBOT_LED_PWM"] = "";  // untranslated
Blockly.Msg["_3DBOT_LED_RED"] = "";  // untranslated
Blockly.Msg["_3DBOT_LED_YELLOW"] = "";  // untranslated
Blockly.Msg["_3DBOT_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOTOR"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_BACKWARD"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_BACKWARD_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_BACKWARD_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_FAST"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_FORWARD"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_NORMAL"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_ROTATE_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_ROTATE_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_SLOW"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_SPEED"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_STOP"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_VERYFAST"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_VERYSLOW"] = "";  // untranslated
Blockly.Msg["_3DBOT_NTC"] = "";  // untranslated
Blockly.Msg["_3DBOT_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_STEPS"] = "";  // untranslated
Blockly.Msg["_3DBOT_WAIT"] = "";  // untranslated
Blockly.Msg["CONTROLS_FOR_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_IF_ELSEIF_TITLE_ELSEIF"] = Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"];
Blockly.Msg["CONTROLS_IF_ELSE_TITLE_ELSE"] = Blockly.Msg["CONTROLS_IF_MSG_ELSE"];
Blockly.Msg["CONTROLS_IF_IF_TITLE_IF"] = Blockly.Msg["CONTROLS_IF_MSG_IF"];
Blockly.Msg["CONTROLS_IF_MSG_THEN"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_WHILEUNTIL_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TITLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["LISTS_GET_INDEX_HELPURL"] = Blockly.Msg["LISTS_INDEX_OF_HELPURL"];
Blockly.Msg["LISTS_GET_INDEX_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["MATH_CHANGE_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["PROCEDURES_DEFRETURN_COMMENT"] = Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"];
Blockly.Msg["PROCEDURES_DEFRETURN_DO"] = Blockly.Msg["PROCEDURES_DEFNORETURN_DO"];
Blockly.Msg["PROCEDURES_DEFRETURN_PROCEDURE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"];
Blockly.Msg["PROCEDURES_DEFRETURN_TITLE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"];
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
