// This file was automatically generated.  Do not modify.

'use strict';

Blockly.Msg["ACTUATOR_BUZZER"] = "";  // untranslated
Blockly.Msg["ACTUATOR_BUZZER_FREQ"] = "";  // untranslated
Blockly.Msg["ACTUATOR_BUZZER_TONE"] = "";  // untranslated
Blockly.Msg["ACTUATOR_IRTX"] = "";  // untranslated
Blockly.Msg["ACTUATOR_IRTX_BITS"] = "";  // untranslated
Blockly.Msg["ACTUATOR_IRTX_CODE"] = "";  // untranslated
Blockly.Msg["ACTUATOR_IRTX_PROTOCOL"] = "";  // untranslated
Blockly.Msg["ACTUATOR_LED"] = "";  // untranslated
Blockly.Msg["ACTUATOR_LED_PWM"] = "";  // untranslated
Blockly.Msg["ACTUATOR_RELAY"] = "";  // untranslated
Blockly.Msg["ACTUATOR_RGBLED"] = "";  // untranslated
Blockly.Msg["ADDRESS"] = "";  // untranslated
Blockly.Msg["ADD_COMMENT"] = "Lisää kommentti";
Blockly.Msg["ADD_NEW_LINE"] = "";  // untranslated
Blockly.Msg["AND"] = "";  // untranslated
Blockly.Msg["ANTICLOCKWISE"] = "";  // untranslated
Blockly.Msg["AS"] = "";  // untranslated
Blockly.Msg["AS_STRING"] = "";  // untranslated
Blockly.Msg["BACKWARD"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_AVAILABLE"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_BAUDRATE"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_DEVNAME"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_FLUSH"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_INIT"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_PIN"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_PRINT"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_PRINTLN"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READ"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READBYTE"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READFLOAT"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READINT"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READSTRING"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READSTRINGLINE"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_WRITEBYTE"] = "";  // untranslated
Blockly.Msg["BLYNK_APP_CONNECTED"] = "";  // untranslated
Blockly.Msg["BLYNK_APP_DISCONNECTED"] = "";  // untranslated
Blockly.Msg["BLYNK_APP_READ"] = "";  // untranslated
Blockly.Msg["BLYNK_APP_WRITE"] = "";  // untranslated
Blockly.Msg["BLYNK_AUTH"] = "";  // untranslated
Blockly.Msg["BLYNK_CONNECTED"] = "";  // untranslated
Blockly.Msg["BLYNK_INIT"] = "";  // untranslated
Blockly.Msg["BLYNK_LCD_CLEAR"] = "";  // untranslated
Blockly.Msg["BLYNK_LCD_PRINT"] = "";  // untranslated
Blockly.Msg["BLYNK_LED"] = "";  // untranslated
Blockly.Msg["BLYNK_LED_INTENSITY"] = "";  // untranslated
Blockly.Msg["BLYNK_LOCALPORT"] = "";  // untranslated
Blockly.Msg["BLYNK_LOCALSERVER"] = "";  // untranslated
Blockly.Msg["BLYNK_MAP"] = "";  // untranslated
Blockly.Msg["BLYNK_PARAM_READ_INT"] = "";  // untranslated
Blockly.Msg["BLYNK_PARAM_READ_STRING"] = "";  // untranslated
Blockly.Msg["BLYNK_SET_PROPERTY"] = "";  // untranslated
Blockly.Msg["BLYNK_TERMINAL_CLEAR"] = "";  // untranslated
Blockly.Msg["BLYNK_TERMINAL_PRINT"] = "";  // untranslated
Blockly.Msg["BLYNK_TIMER"] = "";  // untranslated
Blockly.Msg["BLYNK_VIRTUALWRITE"] = "";  // untranslated
Blockly.Msg["BLYNK_VPIN"] = "";  // untranslated
Blockly.Msg["BLYNK_VPIN_VALUE"] = "";  // untranslated
Blockly.Msg["CHANGE_VALUE_TITLE"] = "Muuta arvoa:";
Blockly.Msg["CLEAN_UP"] = "Siivoa lohkot";
Blockly.Msg["CLOCKWISE"] = "";  // untranslated
Blockly.Msg["COLLAPSE_ALL"] = "Sulje lohkot";
Blockly.Msg["COLLAPSE_BLOCK"] = "Sulje lohko";
Blockly.Msg["COLOUR"] = "";  // untranslated
Blockly.Msg["COL_BLUE"] = "";  // untranslated
Blockly.Msg["COL_GREEN"] = "";  // untranslated
Blockly.Msg["COL_RED"] = "";  // untranslated
Blockly.Msg["COMMON_ANODE"] = "";  // untranslated
Blockly.Msg["COMMON_CATHODE"] = "";  // untranslated
Blockly.Msg["CONTROLS_FOR_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg["CONTROLS_FOR_TITLE"] = "laske %1 Väli %2-%3 %4:n välein";
Blockly.Msg["CONTROLS_FOR_TOOLTIP"] = "Aseta muuttujaan \"%1\" arvot alkuarvosta loppuarvoon annetun askeleen välein ja suorita joka askeleella annettu koodilohko.";
Blockly.Msg["CONTROLS_IF_ELSEIF_TOOLTIP"] = "Lisää ehto \"jos\" lohkoon.";
Blockly.Msg["CONTROLS_IF_ELSE_TOOLTIP"] = "Lisää lopullinen \"muuten\" lohko \"jos\" lohkoon.";
Blockly.Msg["CONTROLS_IF_HELPURL"] = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg["CONTROLS_IF_IF_TOOLTIP"] = "Lisää, poista tai järjestele osioita tässä \"jos\" lohkossa.";
Blockly.Msg["CONTROLS_IF_MSG_ELSE"] = "muuten";
Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"] = "muuten jos";
Blockly.Msg["CONTROLS_IF_MSG_IF"] = "jos";
Blockly.Msg["CONTROLS_IF_TOOLTIP_1"] = "Jos arvo on tosi, suorita lauseke.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_2"] = "Jos arvo on tosi, suorita ensimmäinen lohko lausekkeita. Muuten suorita toinen lohko lausekkeita.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_3"] = "Jos ensimmäinen arvo on tosi, suorita ensimmäinen lohko lausekkeita. Muuten, jos toinen arvo on tosi, suorita toinen lohko lausekkeita.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_4"] = "Jos ensimmäinen arvo on tosi, suorita ensimmäinen lohko lausekkeita. Muuten, jos toinen arvo on tosi, suorita toinen lohko lausekkeita. Jos mikään arvoista ei ole tosi, suorita viimeinen lohko lausekkeita.";
Blockly.Msg["CONTROLS_REPEAT_HELPURL"] = "https://en.wikipedia.org/wiki/For_loop";
Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"] = "tee";
Blockly.Msg["CONTROLS_REPEAT_TITLE"] = "toista %1 kertaa";
Blockly.Msg["CONTROLS_REPEAT_TOOLTIP"] = "Suorita joukko lausekkeita useampi kertaa.";
Blockly.Msg["CONTROLS_WHILEUNTIL_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_UNTIL"] = "toista kunnes";
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_WHILE"] = "toista niin kauan kuin";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL"] = "Niin kauan kuin arvo on epätosi, suorita joukko lausekkeita.";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_WHILE"] = "Niin kauan kuin arvo on tosi, suorita joukko lausekkeita.";
Blockly.Msg["CONTROL_ARDUINO_LOOP"] = "";  // untranslated
Blockly.Msg["CONTROL_ARDUINO_SETUP"] = "";  // untranslated
Blockly.Msg["CONTROL_GROUP"] = "";  // untranslated
Blockly.Msg["DELETE_ALL_BLOCKS"] = "Poistetaanko kaikki %1 lohkoa?";
Blockly.Msg["DELETE_BLOCK"] = "Poista lohko";
Blockly.Msg["DELETE_X_BLOCKS"] = "Poista %1 lohkoa";
Blockly.Msg["DEPRECATED"] = "";  // untranslated
Blockly.Msg["DISABLE_BLOCK"] = "Passivoi lohko";
Blockly.Msg["DOMOTICS_INA219_CURRENT"] = "";  // untranslated
Blockly.Msg["DOMOTICS_INA219_INIT"] = "";  // untranslated
Blockly.Msg["DOMOTICS_INA219_POWER"] = "";  // untranslated
Blockly.Msg["DOMOTICS_INA219_VOLTAGE"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_CURRENT"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_ENERGY"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_FREQUENCY"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_INIT"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_POWER"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_POWERFACTOR"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_SETADDRESS"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_VALUE"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_VOLTAGE"] = "";  // untranslated
Blockly.Msg["DOWN"] = "";  // untranslated
Blockly.Msg["DUPLICATE_BLOCK"] = "Kaksoiskappale";
Blockly.Msg["EEPROM_ADDRESS"] = "";  // untranslated
Blockly.Msg["EEPROM_READ"] = "";  // untranslated
Blockly.Msg["EEPROM_WRITE"] = "";  // untranslated
Blockly.Msg["ENABLE_BLOCK"] = "Aktivoi lohko";
Blockly.Msg["EXPAND_ALL"] = "Laajenna lohkot";
Blockly.Msg["EXPAND_BLOCK"] = "Laajenna lohko";
Blockly.Msg["EXTERNAL_INPUTS"] = "Ulkoiset syötteet";
Blockly.Msg["FILTER_MEDIAN"] = "";  // untranslated
Blockly.Msg["FILTER_MEDIAN_ADD"] = "";  // untranslated
Blockly.Msg["FILTER_MEDIAN_SAMPLES"] = "";  // untranslated
Blockly.Msg["FILTER_MEDIAN_SETWINDOW"] = "";  // untranslated
Blockly.Msg["FORWARD"] = "";  // untranslated
Blockly.Msg["GPS_DAY"] = "";  // untranslated
Blockly.Msg["GPS_DISTANCEBETWEEN"] = "";  // untranslated
Blockly.Msg["GPS_GETALTITUDE"] = "";  // untranslated
Blockly.Msg["GPS_GETCOURSE"] = "";  // untranslated
Blockly.Msg["GPS_GETDATETIME"] = "";  // untranslated
Blockly.Msg["GPS_GETPOSITION"] = "";  // untranslated
Blockly.Msg["GPS_GETSPEED"] = "";  // untranslated
Blockly.Msg["GPS_HOUR"] = "";  // untranslated
Blockly.Msg["GPS_HUND"] = "";  // untranslated
Blockly.Msg["GPS_INIT"] = "";  // untranslated
Blockly.Msg["GPS_KMPH"] = "";  // untranslated
Blockly.Msg["GPS_LAT"] = "";  // untranslated
Blockly.Msg["GPS_LONG"] = "";  // untranslated
Blockly.Msg["GPS_MIN"] = "";  // untranslated
Blockly.Msg["GPS_MONTH"] = "";  // untranslated
Blockly.Msg["GPS_MPH"] = "";  // untranslated
Blockly.Msg["GPS_SEC"] = "";  // untranslated
Blockly.Msg["GPS_VALIDDATA"] = "";  // untranslated
Blockly.Msg["GPS_YEAR"] = "";  // untranslated
Blockly.Msg["HEIGHT"] = "";  // untranslated
Blockly.Msg["HELP"] = "Apua";
Blockly.Msg["ID"] = "";  // untranslated
Blockly.Msg["INLINE_INPUTS"] = "Tuo syötteet";
Blockly.Msg["IO_ANALOG_READ"] = "";  // untranslated
Blockly.Msg["IO_ANALOG_READ_DIF"] = "";  // untranslated
Blockly.Msg["IO_ANALOG_WRITE"] = "";  // untranslated
Blockly.Msg["IO_BOOLEAN_OFF"] = "";  // untranslated
Blockly.Msg["IO_BOOLEAN_ON"] = "";  // untranslated
Blockly.Msg["IO_CAPACITIVE_READ"] = "";  // untranslated
Blockly.Msg["IO_DIGITAL_READ"] = "";  // untranslated
Blockly.Msg["IO_DIGITAL_WRITE"] = "";  // untranslated
Blockly.Msg["IO_INTERRUPT"] = "";  // untranslated
Blockly.Msg["IO_PINMODE"] = "";  // untranslated
Blockly.Msg["IO_PINMODE_AS"] = "";  // untranslated
Blockly.Msg["IO_PULSEIN"] = "";  // untranslated
Blockly.Msg["IO_PULSEIN_TIMEOUT"] = "";  // untranslated
Blockly.Msg["KEYBOARD"] = "";  // untranslated
Blockly.Msg["KEYBOARD_KEY"] = "";  // untranslated
Blockly.Msg["KEYBOARD_KEYSTROKE"] = "";  // untranslated
Blockly.Msg["KEYBOARD_PRESS"] = "";  // untranslated
Blockly.Msg["KEYBOARD_RELEASE"] = "";  // untranslated
Blockly.Msg["KEYBOT_BUZZER"] = "";  // untranslated
Blockly.Msg["KEYBOT_BUZZER_FREQ"] = "";  // untranslated
Blockly.Msg["KEYBOT_DISTANCE"] = "";  // untranslated
Blockly.Msg["KEYBOT_IRSENSOR"] = "";  // untranslated
Blockly.Msg["KEYBOT_IRSENSOR_LEFT"] = "";  // untranslated
Blockly.Msg["KEYBOT_IRSENSOR_MIDDLE"] = "";  // untranslated
Blockly.Msg["KEYBOT_IRSENSOR_RIGHT"] = "";  // untranslated
Blockly.Msg["KEYBOT_LEFT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOTOR"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_BACKWARD"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_FAST"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_FORWARD"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_LEFT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_NORMAL"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_RIGHT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_ROTATE_LEFT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_ROTATE_RIGHT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_SLOW"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_SPEED"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_STOP"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_VERYFAST"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_VERYSLOW"] = "";  // untranslated
Blockly.Msg["KEYBOT_RIGHT"] = "";  // untranslated
Blockly.Msg["KEYPAD"] = "";  // untranslated
Blockly.Msg["KEYPAD_COL"] = "";  // untranslated
Blockly.Msg["KEYPAD_KEY"] = "";  // untranslated
Blockly.Msg["KEYPAD_NOKEY"] = "";  // untranslated
Blockly.Msg["KEYPAD_ROW"] = "";  // untranslated
Blockly.Msg["LCD"] = "";  // untranslated
Blockly.Msg["LCD_BACKLIGHT"] = "";  // untranslated
Blockly.Msg["LCD_BEGIN"] = "";  // untranslated
Blockly.Msg["LCD_BEGIN_I2C"] = "";  // untranslated
Blockly.Msg["LCD_BLINK"] = "";  // untranslated
Blockly.Msg["LCD_CLEAR"] = "";  // untranslated
Blockly.Msg["LCD_COL"] = "";  // untranslated
Blockly.Msg["LCD_CURSOR"] = "";  // untranslated
Blockly.Msg["LCD_DEFINE"] = "";  // untranslated
Blockly.Msg["LCD_DISPLAY"] = "";  // untranslated
Blockly.Msg["LCD_PRINT"] = "";  // untranslated
Blockly.Msg["LCD_ROW"] = "";  // untranslated
Blockly.Msg["LCD_SCROLL"] = "";  // untranslated
Blockly.Msg["LCD_SYMBOL"] = "";  // untranslated
Blockly.Msg["LEDMATRIX"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_CLEAR"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_DRAWBITMAP"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_DRAWCIRCLE"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_DRAWPIXEL"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_DRAWTEXT"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_FILL"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_INIT"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_LINE"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_RECTANGLE"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_ROTATION"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_ROUND"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_SHOW"] = "";  // untranslated
Blockly.Msg["LEFT"] = "";  // untranslated
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"] = "lista";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"] = "Listää, poista tai järjestele uudestaan osioita tässä lohkossa.";
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH"] = "luo lista";
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH_TEXT"] = "";  // untranslated
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TOOLTIP"] = "Lisää kohde listaan.";
Blockly.Msg["LISTS_GET_INDEX_FROM_START"] = "nro";
Blockly.Msg["LISTS_GET_INDEX_GET"] = "hae";
Blockly.Msg["LISTS_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg["LISTS_LENGTH_TITLE"] = "%1:n pituus";
Blockly.Msg["LISTS_LENGTH_TOOLTIP"] = "Palauttaa listan pituuden.";
Blockly.Msg["LISTS_LISTNAME"] = "";  // untranslated
Blockly.Msg["LISTS_LISTNAME_TEXT"] = "";  // untranslated
Blockly.Msg["LISTS_SET_INDEX_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg["LISTS_SET_INDEX_SET"] = "aseta";
Blockly.Msg["LOGIC_BOOLEAN_FALSE"] = "epätosi";
Blockly.Msg["LOGIC_BOOLEAN_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg["LOGIC_BOOLEAN_TOOLTIP"] = "Palauttaa joko tosi tai epätosi.";
Blockly.Msg["LOGIC_BOOLEAN_TRUE"] = "tosi";
Blockly.Msg["LOGIC_COMPARE_HELPURL"] = "https://fi.wikipedia.org/wiki/Ep%C3%A4yht%C3%A4l%C3%B6";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_EQ"] = "Palauta tosi, jos syötteet ovat keskenään samat.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GT"] = "Palauttaa tosi, jos ensimmäinen syöte on suurempi, kuin toinen.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GTE"] = "Palauttaa tosi, jos ensimmäinen syöte on suurempi tai yhtä suuri, kuin toinen.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LT"] = "Palauttaa tosi, jos ensimmäinen syöte on pienempi, kuin toinen.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LTE"] = "Palauttaa tosi, jos ensimmäinen syöte on pienempi tai yhtä suuri, kuin toinen.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_NEQ"] = "Palauttaa tosi, jos syötteet eivät ole keskenään samoja.";
Blockly.Msg["LOGIC_NEGATE_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg["LOGIC_NEGATE_TITLE"] = "ei %1";
Blockly.Msg["LOGIC_NEGATE_TOOLTIP"] = "Palauttaa tosi, jos syöte on epätosi. Palauttaa epätosi, jos syöte on tosi.";
Blockly.Msg["LOGIC_OPERATION_AND"] = "ja";
Blockly.Msg["LOGIC_OPERATION_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg["LOGIC_OPERATION_OR"] = "tai";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_AND"] = "Palauttaa tosi, jos kummatkin syötteet ovat tosia.";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_OR"] = "Palauttaa tosi, jos ainakin yksi syötteistä on tosi.";
Blockly.Msg["MATH_ADDITION_SYMBOL"] = "+";
Blockly.Msg["MATH_ANGLE"] = "";  // untranslated
Blockly.Msg["MATH_ARITHMETIC_HELPURL"] = "http://fi.wikipedia.org/wiki/Aritmetiikka";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_ADD"] = "Palauttaa kahden luvun summan.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_DIVIDE"] = "Palauttaa jakolaskun osamäärän.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MINUS"] = "Palauttaa kahden luvun erotuksen.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MULTIPLY"] = "Palauttaa kertolaskun tulon.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_POWER"] = "Palauttaa ensimmäisen luvun korotettuna toisen luvun potenssiin.";
Blockly.Msg["MATH_CHANGE_HELPURL"] = "https://fi.wikipedia.org/wiki/Yhteenlasku";
Blockly.Msg["MATH_CHANGE_TITLE"] = "muuta %1 arvolla %2";
Blockly.Msg["MATH_CHANGE_TOOLTIP"] = "Lisää arvo muuttujaan '%1'.";
Blockly.Msg["MATH_CONSTANT_HELPURL"] = "https://en.wikipedia.org/wiki/Mathematical_constant";
Blockly.Msg["MATH_CONSTANT_TOOLTIP"] = "Palauttaa jonkin seuraavista vakioista: π (3.141…), e (2.718…), φ (1.618…), neliöjuuri(2) (1.414…), neliöjuuri(½) (0.707…), or ∞ (ääretön).";
Blockly.Msg["MATH_CONSTRAIN_HELPURL"] = "https://en.wikipedia.org/wiki/Clamping_(graphics)";  // untranslated
Blockly.Msg["MATH_CONSTRAIN_TITLE"] = "rajoita %1 vähintään %2 enintään %3";
Blockly.Msg["MATH_CONSTRAIN_TOOLTIP"] = "Rajoittaa arvon annetulle suljetulle välille.";
Blockly.Msg["MATH_DIVISION_SYMBOL"] = "÷";
Blockly.Msg["MATH_MAP_HELPURL"] = "";  // untranslated
Blockly.Msg["MATH_MAP_TITLE"] = "";  // untranslated
Blockly.Msg["MATH_MAP_TOOLTIP"] = "";  // untranslated
Blockly.Msg["MATH_MODULO_HELPURL"] = "https://en.wikipedia.org/wiki/Modulo_operation";
Blockly.Msg["MATH_MODULO_TITLE"] = "%1 ÷ %2 jakojäännös";
Blockly.Msg["MATH_MODULO_TOOLTIP"] = "Palauttaa jakolaskun jakojäännöksen.";
Blockly.Msg["MATH_MULTIPLICATION_SYMBOL"] = "⋅";
Blockly.Msg["MATH_NUMBER_HELPURL"] = "https://fi.wikipedia.org/wiki/Luku";
Blockly.Msg["MATH_NUMBER_TOOLTIP"] = "Luku.";
Blockly.Msg["MATH_POWER_SYMBOL"] = "^";
Blockly.Msg["MATH_RANDOM_INT_HELPURL"] = "https://fi.wikipedia.org/wiki/Satunnaisluku";
Blockly.Msg["MATH_RANDOM_INT_TITLE"] = "Palauttaa satunnaisen kokonaisluvun väliltä %1-%2";
Blockly.Msg["MATH_RANDOM_INT_TOOLTIP"] = "Palauttaa satunnaisen kokonaisluvun kahden annetun arvon suljetulta väliltä.";
Blockly.Msg["MATH_ROUND_HELPURL"] = "https://fi.wikipedia.org/wiki/Py%C3%B6rist%C3%A4minen";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUND"] = "pyöristä";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDDOWN"] = "pyöristä alaspäin";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDUP"] = "pyöristä ylöspäin";
Blockly.Msg["MATH_ROUND_TOOLTIP"] = "Pyöristää luvun ylös- tai alaspäin.";
Blockly.Msg["MATH_SINGLE_HELPURL"] = "https://fi.wikipedia.org/wiki/Neli%C3%B6juuri";
Blockly.Msg["MATH_SINGLE_OP_ABSOLUTE"] = "itseisarvo";
Blockly.Msg["MATH_SINGLE_OP_ROOT"] = "neliöjuuri";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ABS"] = "Palauttaa luvun itseisarvon.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_EXP"] = "Palauttaa e potenssiin luku.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LN"] = "Palauttaa luvun luonnollisen logaritmin.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LOG10"] = "Palauttaa luvun kymmenkantaisen logaritmin.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_NEG"] = "Palauttaa numeron vastaluvun.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_POW10"] = "Palauttaa 10 potenssiin luku.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ROOT"] = "Palauttaa luvun neliöjuuren.";
Blockly.Msg["MATH_SUBTRACTION_SYMBOL"] = "-";
Blockly.Msg["MATH_TO_INT"] = "";  // untranslated
Blockly.Msg["MATH_TO_UINT"] = "";  // untranslated
Blockly.Msg["MATH_TRIG_ACOS"] = "acos";
Blockly.Msg["MATH_TRIG_ASIN"] = "asin";
Blockly.Msg["MATH_TRIG_ATAN"] = "atan";
Blockly.Msg["MATH_TRIG_ATAN2"] = "";  // untranslated
Blockly.Msg["MATH_TRIG_COS"] = "cos";
Blockly.Msg["MATH_TRIG_HELPURL"] = "https://fi.wikipedia.org/wiki/Trigonometrinen_funktio";
Blockly.Msg["MATH_TRIG_SIN"] = "sin";
Blockly.Msg["MATH_TRIG_TAN"] = "tan";
Blockly.Msg["MATH_TRIG_TOOLTIP_ACOS"] = "Palauttaa luvun arkuskosinin.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ASIN"] = "Palauttaa luvun arkussinin.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ATAN"] = "Palauttaa luvun arkustangentin.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ATAN2"] = "";  // untranslated
Blockly.Msg["MATH_TRIG_TOOLTIP_COS"] = "Palauttaa asteluvun (ei radiaanin) kosinin.";
Blockly.Msg["MATH_TRIG_TOOLTIP_SIN"] = "Palauttaa asteluvun (ei radiaanin) sinin.";
Blockly.Msg["MATH_TRIG_TOOLTIP_TAN"] = "Palauttaa asteluvun (ei radiaanin) tangentin.";
Blockly.Msg["MOTORSHIELD_DC"] = "";  // untranslated
Blockly.Msg["MOTORSHIELD_SERVO"] = "";  // untranslated
Blockly.Msg["MOTORSHIELD_STEPPER"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_BW"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_FW"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_INIT"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_MOTOR"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_MOVE"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_SPEED"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298P"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_DEGREE_RANGE"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_DELAY"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_AMPLITUDE"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_OFFSET"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_PERIOD"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_PHASE"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_REFRESH"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_RESET"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_SET"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_START"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_STOP"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_READ"] = "";  // untranslated
Blockly.Msg["MOTOR_STEPPER"] = "";  // untranslated
Blockly.Msg["MOTOR_STEPPER_RPM"] = "";  // untranslated
Blockly.Msg["MOTOR_STEPPER_STEP"] = "";  // untranslated
Blockly.Msg["MOTOR_STEPPER_STEPS"] = "";  // untranslated
Blockly.Msg["MOUSE"] = "";  // untranslated
Blockly.Msg["MOUSE_BUTTON"] = "";  // untranslated
Blockly.Msg["MOUSE_CLICK"] = "";  // untranslated
Blockly.Msg["MOUSE_MIDDLE"] = "";  // untranslated
Blockly.Msg["MOUSE_MOVE"] = "";  // untranslated
Blockly.Msg["MOUSE_WHEEL"] = "";  // untranslated
Blockly.Msg["MP3_CONTROL"] = "";  // untranslated
Blockly.Msg["MP3_EQ"] = "";  // untranslated
Blockly.Msg["MP3_FILE"] = "";  // untranslated
Blockly.Msg["MP3_FOLDER"] = "";  // untranslated
Blockly.Msg["MP3_INIT"] = "";  // untranslated
Blockly.Msg["MP3_NEXT"] = "";  // untranslated
Blockly.Msg["MP3_PAUSE"] = "";  // untranslated
Blockly.Msg["MP3_PLAY"] = "";  // untranslated
Blockly.Msg["MP3_PREV"] = "";  // untranslated
Blockly.Msg["MP3_REPEAT"] = "";  // untranslated
Blockly.Msg["MP3_RESET"] = "";  // untranslated
Blockly.Msg["MP3_SHUFFLE"] = "";  // untranslated
Blockly.Msg["MP3_STOP"] = "";  // untranslated
Blockly.Msg["MP3_VOLUME"] = "";  // untranslated
Blockly.Msg["MQTT_BROKER"] = "";  // untranslated
Blockly.Msg["MQTT_CLIENTID"] = "";  // untranslated
Blockly.Msg["MQTT_INIT"] = "";  // untranslated
Blockly.Msg["MQTT_ISCONNECTED"] = "";  // untranslated
Blockly.Msg["MQTT_MAC"] = "";  // untranslated
Blockly.Msg["MQTT_PASS"] = "";  // untranslated
Blockly.Msg["MQTT_PORT"] = "";  // untranslated
Blockly.Msg["MQTT_PUB"] = "";  // untranslated
Blockly.Msg["MQTT_SUB"] = "";  // untranslated
Blockly.Msg["MQTT_TOPIC"] = "";  // untranslated
Blockly.Msg["MQTT_USER"] = "";  // untranslated
Blockly.Msg["MQTT_VALUE"] = "";  // untranslated
Blockly.Msg["MQTT_WIFI_NAME"] = "";  // untranslated
Blockly.Msg["MQTT_WIFI_PASS"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_CLEAR"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_INIT"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_LEDCOUNT"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_PIXEL"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_SETMATRIX"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_SETPIXEL"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_SETRAW"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_SHOW"] = "";  // untranslated
Blockly.Msg["NEW_VARIABLE"] = "Luo muuttuja...";
Blockly.Msg["NEW_VARIABLE_TITLE"] = "Uuden muuttujan nimi:";
Blockly.Msg["NOTE_A"] = "";  // untranslated
Blockly.Msg["NOTE_AS"] = "";  // untranslated
Blockly.Msg["NOTE_B"] = "";  // untranslated
Blockly.Msg["NOTE_C"] = "";  // untranslated
Blockly.Msg["NOTE_CS"] = "";  // untranslated
Blockly.Msg["NOTE_D"] = "";  // untranslated
Blockly.Msg["NOTE_DS"] = "";  // untranslated
Blockly.Msg["NOTE_E"] = "";  // untranslated
Blockly.Msg["NOTE_F"] = "";  // untranslated
Blockly.Msg["NOTE_FS"] = "";  // untranslated
Blockly.Msg["NOTE_G"] = "";  // untranslated
Blockly.Msg["NOTE_GS"] = "";  // untranslated
Blockly.Msg["NUMBER"] = "";  // untranslated
Blockly.Msg["NUNCHUK"] = "";  // untranslated
Blockly.Msg["NUNCHUK_X"] = "";  // untranslated
Blockly.Msg["NUNCHUK_Y"] = "";  // untranslated
Blockly.Msg["NUNCHUK_aX"] = "";  // untranslated
Blockly.Msg["NUNCHUK_aY"] = "";  // untranslated
Blockly.Msg["NUNCHUK_aZ"] = "";  // untranslated
Blockly.Msg["NUNCHUK_bC"] = "";  // untranslated
Blockly.Msg["NUNCHUK_bZ"] = "";  // untranslated
Blockly.Msg["OK"] = "";  // untranslated
Blockly.Msg["OLED_AUTOSHOW"] = "";  // untranslated
Blockly.Msg["OTTO_AMP"] = "";  // untranslated
Blockly.Msg["OTTO_AMP_BIG"] = "";  // untranslated
Blockly.Msg["OTTO_AMP_NORMAL"] = "";  // untranslated
Blockly.Msg["OTTO_AMP_SMALL"] = "";  // untranslated
Blockly.Msg["OTTO_BUTTON"] = "";  // untranslated
Blockly.Msg["OTTO_CALIBRATE"] = "";  // untranslated
Blockly.Msg["OTTO_CALIB_FOOTL"] = "";  // untranslated
Blockly.Msg["OTTO_CALIB_FOOTR"] = "";  // untranslated
Blockly.Msg["OTTO_CALIB_LEGL"] = "";  // untranslated
Blockly.Msg["OTTO_CALIB_LEGR"] = "";  // untranslated
Blockly.Msg["OTTO_DISTANCE"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_ANGRY"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_CONFUSED"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_FAIL"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_FART"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_FRETFUL"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_HAPPY"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_LOVE"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_MAGIC"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_SAD"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_SLEEPING"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_SUPERHAPPY"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_VICTORY"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_WAVE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_ANGRY"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_BIGSURPRISE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_CLEAR"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_CONFUSED"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_CULITO"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_DIAGONAL"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_EIGHT"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_FIVE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_FOUR"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_HAPPYCLOSED"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_HAPPYOPEN"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_HEART"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_INTERROGATION"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_LINEMOUTH"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_NINE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_OKMOUTH"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_ONE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SAD"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SADCLOSED"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SADOPEN"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SEVEN"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SIX"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SMALLSURPRISE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SMILE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_THREE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_THUNDER"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_TONGUEOUT"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_TWO"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_VAMP1"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_VAMP2"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_XMOUTH"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_ZERO"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE2"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_ASCTURN"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_BENDL"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_BENDR"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_CRUSAITO1"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_CRUSAITO2"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_FLAPPING1"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_FLAPPING2"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_HOME"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_JITTER"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_JUMP"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_MOONWALKL"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_MOONWALKR"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_SHAKEL"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_SHAKER"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_SWING"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_TIPTOESWING"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_TURNL"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_TURNR"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_UPDOWN"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_WALKB"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_WALKF"] = "";  // untranslated
Blockly.Msg["OTTO_NOISE"] = "";  // untranslated
Blockly.Msg["OTTO_NOTE"] = "";  // untranslated
Blockly.Msg["OTTO_NOTE_DURATION"] = "";  // untranslated
Blockly.Msg["OTTO_SING"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_BUTTON"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_CONFUSED"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_CONNECTION"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_CUDDLY"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_DISCONNECTION"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_FART1"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_FART2"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_FART3"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_HAPPY"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_HAPPYSHOR"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_MODE1"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_MODE2"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_MODE3"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_OH2"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_OH_"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_SAD"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_SLEEPING"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_SUPERHAPPY"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_SURPRISE"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_FAST"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_NORMAL"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_SLOW"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_VERYFAST"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_VERYSLOW"] = "";  // untranslated
Blockly.Msg["PIN"] = "";  // untranslated
Blockly.Msg["PRESSED"] = "";  // untranslated
Blockly.Msg["PROCEDURES_ALLOW_STATEMENTS"] = "salli kommentit";
Blockly.Msg["PROCEDURES_BEFORE_PARAMS"] = "parametrit:";
Blockly.Msg["PROCEDURES_CALLNORETURN_HELPURL"] = "https://fi.wikipedia.org/wiki/Aliohjelma";
Blockly.Msg["PROCEDURES_CALLNORETURN_TOOLTIP"] = "Suorittaa käyttäjän määrittelemä funktio '%1'.";
Blockly.Msg["PROCEDURES_CALLRETURN_HELPURL"] = "https://fi.wikipedia.org/wiki/Aliohjelma";
Blockly.Msg["PROCEDURES_CALLRETURN_TOOLTIP"] = "Suorittaa käyttäjän määrittelemän funktion '%1' ja käyttää sen tuotosta.";
Blockly.Msg["PROCEDURES_CALL_BEFORE_PARAMS"] = "parametrit:";
Blockly.Msg["PROCEDURES_CREATE_DO"] = "Luo '%1'";
Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"] = "Kuvaile tämä funktio...";
Blockly.Msg["PROCEDURES_DEFNORETURN_DO"] = "";  // untranslated
Blockly.Msg["PROCEDURES_DEFNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"] = "tee jotain";
Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"] = "tehdäksesi";
Blockly.Msg["PROCEDURES_DEFNORETURN_TOOLTIP"] = "Luo funktio, jolla ei ole tuotosta.";
Blockly.Msg["PROCEDURES_DEFRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
Blockly.Msg["PROCEDURES_DEFRETURN_RETURN"] = "palauta";
Blockly.Msg["PROCEDURES_DEFRETURN_TOOLTIP"] = "Luo funktio, jolla ei ole tuotosta.";
Blockly.Msg["PROCEDURES_DEF_DUPLICATE_WARNING"] = "Varoitus: tällä funktiolla on sama parametri useamman kerran.";
Blockly.Msg["PROCEDURES_HIGHLIGHT_DEF"] = "Korosta funktion määritelmä";
Blockly.Msg["PROCEDURES_MUTATORARG_TITLE"] = "syötteen nimi:";
Blockly.Msg["PROCEDURES_MUTATORARG_TOOLTIP"] = "Lisää sisääntulon funktioon.";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TITLE"] = "syötteet";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TOOLTIP"] = "Lisää, poista tai järjestele uudelleen tämän toiminnon tulot.";
Blockly.Msg["REDO"] = "Tee uudelleen";
Blockly.Msg["REMOVE_COMMENT"] = "Poista kommentti";
Blockly.Msg["RENAME_VARIABLE"] = "Nimeä uudelleen muuttuja...";
Blockly.Msg["RENAME_VARIABLE_TITLE"] = "Nimeä uudelleen kaikki '%1' muuttujaa:";
Blockly.Msg["RFID_EJECTCARD"] = "";  // untranslated
Blockly.Msg["RFID_INIT"] = "";  // untranslated
Blockly.Msg["RFID_NEWCARDPRESENT"] = "";  // untranslated
Blockly.Msg["RFID_READUID"] = "";  // untranslated
Blockly.Msg["RIGHT"] = "";  // untranslated
Blockly.Msg["RTC"] = "";  // untranslated
Blockly.Msg["RTC_DATE_TEXT"] = "";  // untranslated
Blockly.Msg["RTC_DAY"] = "";  // untranslated
Blockly.Msg["RTC_DAYOFWEEK"] = "";  // untranslated
Blockly.Msg["RTC_FRIDAY"] = "";  // untranslated
Blockly.Msg["RTC_HOUR"] = "";  // untranslated
Blockly.Msg["RTC_MINUTE"] = "";  // untranslated
Blockly.Msg["RTC_MONDAY"] = "";  // untranslated
Blockly.Msg["RTC_MONTH"] = "";  // untranslated
Blockly.Msg["RTC_SATURDAY"] = "";  // untranslated
Blockly.Msg["RTC_SECOND"] = "";  // untranslated
Blockly.Msg["RTC_SUNDAY"] = "";  // untranslated
Blockly.Msg["RTC_THURSDAY"] = "";  // untranslated
Blockly.Msg["RTC_TIME_TEXT"] = "";  // untranslated
Blockly.Msg["RTC_TUESDAY"] = "";  // untranslated
Blockly.Msg["RTC_WEDNESDAY"] = "";  // untranslated
Blockly.Msg["RTC_YEAR"] = "";  // untranslated
Blockly.Msg["SD_BEGIN"] = "";  // untranslated
Blockly.Msg["SD_EXISTS"] = "";  // untranslated
Blockly.Msg["SD_POS"] = "";  // untranslated
Blockly.Msg["SD_PRINT"] = "";  // untranslated
Blockly.Msg["SD_READBYTE"] = "";  // untranslated
Blockly.Msg["SD_READLOOP"] = "";  // untranslated
Blockly.Msg["SD_REMOVE"] = "";  // untranslated
Blockly.Msg["SD_SIZE"] = "";  // untranslated
Blockly.Msg["SD_WRITEBYTE"] = "";  // untranslated
Blockly.Msg["SENSOR_18B20"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL_ADXL345"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL_X"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL_Y"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL_Z"] = "";  // untranslated
Blockly.Msg["SENSOR_AIR"] = "";  // untranslated
Blockly.Msg["SENSOR_ALCOHOL"] = "";  // untranslated
Blockly.Msg["SENSOR_ALTITUDE"] = "";  // untranslated
Blockly.Msg["SENSOR_BAROMETRIC"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON_DEBOUNCED"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON_DEBOUNCED_PRESSED"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON_DEBOUNCED_RELEASED"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON_INVERT"] = "";  // untranslated
Blockly.Msg["SENSOR_CCS811"] = "";  // untranslated
Blockly.Msg["SENSOR_CCS811_CO2"] = "";  // untranslated
Blockly.Msg["SENSOR_CCS811_CO2_UGM3"] = "";  // untranslated
Blockly.Msg["SENSOR_CCS811_TVOC"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_BLACK"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_BLUE"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_CYAN"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_GREEN"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_HSV_H"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_HSV_S"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_HSV_V"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_ISCOLOR"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_NAME"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_ORANGE"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_PURPLE"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_READCOLOR"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RED"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RGB_B"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RGB_CLEAR"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RGB_G"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RGB_R"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_WHITE"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_YELLOW"] = "";  // untranslated
Blockly.Msg["SENSOR_CRASH"] = "";  // untranslated
Blockly.Msg["SENSOR_DATA_RAW"] = "";  // untranslated
Blockly.Msg["SENSOR_DHT11"] = "";  // untranslated
Blockly.Msg["SENSOR_DHT22"] = "";  // untranslated
Blockly.Msg["SENSOR_DS18B20"] = "";  // untranslated
Blockly.Msg["SENSOR_FLAME"] = "";  // untranslated
Blockly.Msg["SENSOR_GAS"] = "";  // untranslated
Blockly.Msg["SENSOR_HALL"] = "";  // untranslated
Blockly.Msg["SENSOR_HUMIDITY"] = "";  // untranslated
Blockly.Msg["SENSOR_IRRX"] = "";  // untranslated
Blockly.Msg["SENSOR_JOYSTICK"] = "";  // untranslated
Blockly.Msg["SENSOR_KNOCK"] = "";  // untranslated
Blockly.Msg["SENSOR_LDR"] = "";  // untranslated
Blockly.Msg["SENSOR_LINETRACKING"] = "";  // untranslated
Blockly.Msg["SENSOR_LM35"] = "";  // untranslated
Blockly.Msg["SENSOR_MICS4514"] = "";  // untranslated
Blockly.Msg["SENSOR_MLX90614"] = "";  // untranslated
Blockly.Msg["SENSOR_MLX90614_AMBIENT"] = "";  // untranslated
Blockly.Msg["SENSOR_MLX90614_OBJECT"] = "";  // untranslated
Blockly.Msg["SENSOR_NTC"] = "";  // untranslated
Blockly.Msg["SENSOR_OBSTACLE"] = "";  // untranslated
Blockly.Msg["SENSOR_PAJ7620"] = "";  // untranslated
Blockly.Msg["SENSOR_PHOTOINT"] = "";  // untranslated
Blockly.Msg["SENSOR_PIR"] = "";  // untranslated
Blockly.Msg["SENSOR_PM25"] = "";  // untranslated
Blockly.Msg["SENSOR_PM25_DENSITY"] = "";  // untranslated
Blockly.Msg["SENSOR_PM25_PARTICLESM3"] = "";  // untranslated
Blockly.Msg["SENSOR_POT"] = "";  // untranslated
Blockly.Msg["SENSOR_PRESSURE"] = "";  // untranslated
Blockly.Msg["SENSOR_REED"] = "";  // untranslated
Blockly.Msg["SENSOR_ROTARY_ENCODER"] = "";  // untranslated
Blockly.Msg["SENSOR_ROTARY_ENCODER_POS"] = "";  // untranslated
Blockly.Msg["SENSOR_SOILHUMIDITY"] = "";  // untranslated
Blockly.Msg["SENSOR_SOUND"] = "";  // untranslated
Blockly.Msg["SENSOR_TEMPERATURE"] = "";  // untranslated
Blockly.Msg["SENSOR_TEMT6000"] = "";  // untranslated
Blockly.Msg["SENSOR_TILT"] = "";  // untranslated
Blockly.Msg["SENSOR_TMP36"] = "";  // untranslated
Blockly.Msg["SENSOR_TOUCH"] = "";  // untranslated
Blockly.Msg["SENSOR_ULTRASONIC"] = "";  // untranslated
Blockly.Msg["SENSOR_ULTRASONIC_MAXDISTANCE"] = "";  // untranslated
Blockly.Msg["SENSOR_VIBRATION"] = "";  // untranslated
Blockly.Msg["SENSOR_VL53L0X"] = "";  // untranslated
Blockly.Msg["SENSOR_WATER"] = "";  // untranslated
Blockly.Msg["SERIAL_AVAILABLE"] = "";  // untranslated
Blockly.Msg["SERIAL_BAUDRATE"] = "";  // untranslated
Blockly.Msg["SERIAL_FLUSH"] = "";  // untranslated
Blockly.Msg["SERIAL_INIT"] = "";  // untranslated
Blockly.Msg["SERIAL_INT"] = "";  // untranslated
Blockly.Msg["SERIAL_PLOT"] = "";  // untranslated
Blockly.Msg["SERIAL_PLOTVALUE"] = "";  // untranslated
Blockly.Msg["SERIAL_PLOTVAR"] = "";  // untranslated
Blockly.Msg["SERIAL_PRINT"] = "";  // untranslated
Blockly.Msg["SERIAL_PRINTLN"] = "";  // untranslated
Blockly.Msg["SERIAL_READ"] = "";  // untranslated
Blockly.Msg["SERIAL_READBYTE"] = "";  // untranslated
Blockly.Msg["SERIAL_READFLOAT"] = "";  // untranslated
Blockly.Msg["SERIAL_READINT"] = "";  // untranslated
Blockly.Msg["SERIAL_READSTRING"] = "";  // untranslated
Blockly.Msg["SERIAL_READSTRINGLINE"] = "";  // untranslated
Blockly.Msg["SERIAL_TIMEOUT"] = "";  // untranslated
Blockly.Msg["SERIAL_WRITEBYTE"] = "";  // untranslated
Blockly.Msg["SHOP"] = "";  // untranslated
Blockly.Msg["SOUND_FREQ"] = "";  // untranslated
Blockly.Msg["SOUND_NOTE"] = "";  // untranslated
Blockly.Msg["SOUND_NOTONE"] = "";  // untranslated
Blockly.Msg["SOUND_PLAY"] = "";  // untranslated
Blockly.Msg["SOUND_TONE"] = "";  // untranslated
Blockly.Msg["STATUS"] = "";  // untranslated
Blockly.Msg["TEXT"] = "";  // untranslated
Blockly.Msg["TEXT_ASCII"] = "";  // untranslated
Blockly.Msg["TEXT_COMMENT"] = "";  // untranslated
Blockly.Msg["TEXT_CONTAINS"] = "";  // untranslated
Blockly.Msg["TEXT_CONTAINS_1"] = "";  // untranslated
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TOOLTIP"] = "Lisää kohteen tekstiin.";
Blockly.Msg["TEXT_CREATE_JOIN_TITLE_JOIN"] = "liitä";
Blockly.Msg["TEXT_CREATE_JOIN_TOOLTIP"] = "Lisää, poista tai uudelleen järjestä osioita tässä lohkossa.";
Blockly.Msg["TEXT_DECIMAL"] = "";  // untranslated
Blockly.Msg["TEXT_ENDSWITH"] = "";  // untranslated
Blockly.Msg["TEXT_EQUALS"] = "";  // untranslated
Blockly.Msg["TEXT_EQUALS_IGNORE"] = "";  // untranslated
Blockly.Msg["TEXT_FORMAT"] = "";  // untranslated
Blockly.Msg["TEXT_INDEXOF"] = "";  // untranslated
Blockly.Msg["TEXT_INDEXOF_1"] = "";  // untranslated
Blockly.Msg["TEXT_INDEXOF_FIRST"] = "";  // untranslated
Blockly.Msg["TEXT_INDEXOF_LAST"] = "";  // untranslated
Blockly.Msg["TEXT_JOIN_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg["TEXT_JOIN_TITLE_CREATEWITH"] = "luo teksti";
Blockly.Msg["TEXT_JOIN_TOOLTIP"] = "Luo merkkijonon liittämällä yhteen minkä tahansa määrän kohteita.";
Blockly.Msg["TEXT_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg["TEXT_LENGTH_TITLE"] = "%1:n pituus";
Blockly.Msg["TEXT_LENGTH_TOOLTIP"] = "Palauttaa annetussa tekstissä olevien merkkien määrän (välilyönnit mukaan lukien).";
Blockly.Msg["TEXT_LOWERCASE"] = "";  // untranslated
Blockly.Msg["TEXT_NOT_EQUALS"] = "";  // untranslated
Blockly.Msg["TEXT_REPLACE"] = "";  // untranslated
Blockly.Msg["TEXT_REPLACE_1"] = "";  // untranslated
Blockly.Msg["TEXT_REPLACE_2"] = "";  // untranslated
Blockly.Msg["TEXT_STARTSWITH"] = "";  // untranslated
Blockly.Msg["TEXT_SUBSTRING"] = "";  // untranslated
Blockly.Msg["TEXT_SUBSTRING_1"] = "";  // untranslated
Blockly.Msg["TEXT_SUBSTRING_2"] = "";  // untranslated
Blockly.Msg["TEXT_TEXT_HELPURL"] = "https://fi.wikipedia.org/wiki/Merkkijono";
Blockly.Msg["TEXT_TEXT_TOOLTIP"] = "Kirjain, sana tai rivi tekstiä.";
Blockly.Msg["TEXT_TONUMBER"] = "";  // untranslated
Blockly.Msg["TEXT_UPPERCASE"] = "";  // untranslated
Blockly.Msg["TIME_MICROS"] = "";  // untranslated
Blockly.Msg["TIME_MILLIS"] = "";  // untranslated
Blockly.Msg["TIME_RUNEVERYMS"] = "";  // untranslated
Blockly.Msg["TIME_SNOOZE"] = "";  // untranslated
Blockly.Msg["TIME_TIMER"] = "";  // untranslated
Blockly.Msg["TIME_TIMER_RESET"] = "";  // untranslated
Blockly.Msg["TIME_TIME_ELAPSED"] = "";  // untranslated
Blockly.Msg["TIME_WAIT"] = "";  // untranslated
Blockly.Msg["TIME_WAIT_FOREVER"] = "";  // untranslated
Blockly.Msg["TIME_WAIT_UNTIL"] = "";  // untranslated
Blockly.Msg["TIME_WAIT_WHILE"] = "";  // untranslated
Blockly.Msg["TO"] = "";  // untranslated
Blockly.Msg["TODAY"] = "Tänään";
Blockly.Msg["UNDO"] = "Kumoa";
Blockly.Msg["UNTIL_NEW_LINE"] = "";  // untranslated
Blockly.Msg["UP"] = "";  // untranslated
Blockly.Msg["VALUE"] = "";  // untranslated
Blockly.Msg["VARIABLES_DEFAULT_NAME"] = "kohde";
Blockly.Msg["VARIABLES_DEFAULT_NAME_BOOL"] = "";  // untranslated
Blockly.Msg["VARIABLES_DEFAULT_NAME_TEXT"] = "";  // untranslated
Blockly.Msg["VARIABLES_GET_CREATE_SET"] = "Luo 'aseta %1'";
Blockly.Msg["VARIABLES_GET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg["VARIABLES_GET_TOOLTIP"] = "Palauttaa muuttujan arvon.";
Blockly.Msg["VARIABLES_SET"] = "aseta %1 arvoksi %2";
Blockly.Msg["VARIABLES_SET_CREATE_GET"] = "Luo 'hae %1'";
Blockly.Msg["VARIABLES_SET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg["VARIABLES_SET_TOOLTIP"] = "Asettaa muutujan arvoksi annetun syötteen.";
Blockly.Msg["WAVE"] = "";  // untranslated
Blockly.Msg["WIDTH"] = "";  // untranslated
Blockly.Msg["WIFI_NAME"] = "";  // untranslated
Blockly.Msg["WIFI_PASS"] = "";  // untranslated
Blockly.Msg["WITH"] = "";  // untranslated
Blockly.Msg["_3DBOT_BUTTON"] = "";  // untranslated
Blockly.Msg["_3DBOT_BUZZER"] = "";  // untranslated
Blockly.Msg["_3DBOT_BUZZER_FREQ"] = "";  // untranslated
Blockly.Msg["_3DBOT_DISTANCE"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRRX"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRSENSOR"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRSENSOR_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRSENSOR_MIDDLE"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRSENSOR_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRTX"] = "";  // untranslated
Blockly.Msg["_3DBOT_LDR"] = "";  // untranslated
Blockly.Msg["_3DBOT_LED_GREEN"] = "";  // untranslated
Blockly.Msg["_3DBOT_LED_PWM"] = "";  // untranslated
Blockly.Msg["_3DBOT_LED_RED"] = "";  // untranslated
Blockly.Msg["_3DBOT_LED_YELLOW"] = "";  // untranslated
Blockly.Msg["_3DBOT_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOTOR"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_BACKWARD"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_BACKWARD_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_BACKWARD_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_FAST"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_FORWARD"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_NORMAL"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_ROTATE_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_ROTATE_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_SLOW"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_SPEED"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_STOP"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_VERYFAST"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_VERYSLOW"] = "";  // untranslated
Blockly.Msg["_3DBOT_NTC"] = "";  // untranslated
Blockly.Msg["_3DBOT_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_STEPS"] = "";  // untranslated
Blockly.Msg["_3DBOT_WAIT"] = "";  // untranslated
Blockly.Msg["CONTROLS_FOR_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_IF_ELSEIF_TITLE_ELSEIF"] = Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"];
Blockly.Msg["CONTROLS_IF_ELSE_TITLE_ELSE"] = Blockly.Msg["CONTROLS_IF_MSG_ELSE"];
Blockly.Msg["CONTROLS_IF_IF_TITLE_IF"] = Blockly.Msg["CONTROLS_IF_MSG_IF"];
Blockly.Msg["CONTROLS_IF_MSG_THEN"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_WHILEUNTIL_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TITLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["LISTS_GET_INDEX_HELPURL"] = Blockly.Msg["LISTS_INDEX_OF_HELPURL"];
Blockly.Msg["LISTS_GET_INDEX_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["MATH_CHANGE_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["PROCEDURES_DEFRETURN_COMMENT"] = Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"];
Blockly.Msg["PROCEDURES_DEFRETURN_DO"] = Blockly.Msg["PROCEDURES_DEFNORETURN_DO"];
Blockly.Msg["PROCEDURES_DEFRETURN_PROCEDURE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"];
Blockly.Msg["PROCEDURES_DEFRETURN_TITLE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"];
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
