// This file was automatically generated.  Do not modify.

'use strict';

Blockly.Msg["ACTUATOR_BUZZER"] = "";  // untranslated
Blockly.Msg["ACTUATOR_BUZZER_FREQ"] = "";  // untranslated
Blockly.Msg["ACTUATOR_BUZZER_TONE"] = "";  // untranslated
Blockly.Msg["ACTUATOR_IRTX"] = "";  // untranslated
Blockly.Msg["ACTUATOR_IRTX_BITS"] = "";  // untranslated
Blockly.Msg["ACTUATOR_IRTX_CODE"] = "";  // untranslated
Blockly.Msg["ACTUATOR_IRTX_PROTOCOL"] = "";  // untranslated
Blockly.Msg["ACTUATOR_LED"] = "";  // untranslated
Blockly.Msg["ACTUATOR_LED_PWM"] = "";  // untranslated
Blockly.Msg["ACTUATOR_RELAY"] = "";  // untranslated
Blockly.Msg["ACTUATOR_RGBLED"] = "";  // untranslated
Blockly.Msg["ADDRESS"] = "";  // untranslated
Blockly.Msg["ADD_COMMENT"] = "コメントを追加";
Blockly.Msg["ADD_NEW_LINE"] = "";  // untranslated
Blockly.Msg["AND"] = "";  // untranslated
Blockly.Msg["ANTICLOCKWISE"] = "";  // untranslated
Blockly.Msg["AS"] = "";  // untranslated
Blockly.Msg["AS_STRING"] = "";  // untranslated
Blockly.Msg["BACKWARD"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_AVAILABLE"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_BAUDRATE"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_DEVNAME"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_FLUSH"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_INIT"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_PIN"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_PRINT"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_PRINTLN"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READ"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READBYTE"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READFLOAT"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READINT"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READSTRING"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READSTRINGLINE"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_WRITEBYTE"] = "";  // untranslated
Blockly.Msg["BLYNK_APP_CONNECTED"] = "";  // untranslated
Blockly.Msg["BLYNK_APP_DISCONNECTED"] = "";  // untranslated
Blockly.Msg["BLYNK_APP_READ"] = "";  // untranslated
Blockly.Msg["BLYNK_APP_WRITE"] = "";  // untranslated
Blockly.Msg["BLYNK_AUTH"] = "";  // untranslated
Blockly.Msg["BLYNK_CONNECTED"] = "";  // untranslated
Blockly.Msg["BLYNK_INIT"] = "";  // untranslated
Blockly.Msg["BLYNK_LCD_CLEAR"] = "";  // untranslated
Blockly.Msg["BLYNK_LCD_PRINT"] = "";  // untranslated
Blockly.Msg["BLYNK_LED"] = "";  // untranslated
Blockly.Msg["BLYNK_LED_INTENSITY"] = "";  // untranslated
Blockly.Msg["BLYNK_LOCALPORT"] = "";  // untranslated
Blockly.Msg["BLYNK_LOCALSERVER"] = "";  // untranslated
Blockly.Msg["BLYNK_MAP"] = "";  // untranslated
Blockly.Msg["BLYNK_PARAM_READ_INT"] = "";  // untranslated
Blockly.Msg["BLYNK_PARAM_READ_STRING"] = "";  // untranslated
Blockly.Msg["BLYNK_SET_PROPERTY"] = "";  // untranslated
Blockly.Msg["BLYNK_TERMINAL_CLEAR"] = "";  // untranslated
Blockly.Msg["BLYNK_TERMINAL_PRINT"] = "";  // untranslated
Blockly.Msg["BLYNK_TIMER"] = "";  // untranslated
Blockly.Msg["BLYNK_VIRTUALWRITE"] = "";  // untranslated
Blockly.Msg["BLYNK_VPIN"] = "";  // untranslated
Blockly.Msg["BLYNK_VPIN_VALUE"] = "";  // untranslated
Blockly.Msg["CHANGE_VALUE_TITLE"] = "値を変える：";
Blockly.Msg["CLEAN_UP"] = "ブロックを整理する";
Blockly.Msg["CLOCKWISE"] = "";  // untranslated
Blockly.Msg["COLLAPSE_ALL"] = "ブロックを折りたたむ";
Blockly.Msg["COLLAPSE_BLOCK"] = "ブロックを折りたたむ";
Blockly.Msg["COLOUR"] = "";  // untranslated
Blockly.Msg["COL_BLUE"] = "";  // untranslated
Blockly.Msg["COL_GREEN"] = "";  // untranslated
Blockly.Msg["COL_RED"] = "";  // untranslated
Blockly.Msg["COMMON_ANODE"] = "";  // untranslated
Blockly.Msg["COMMON_CATHODE"] = "";  // untranslated
Blockly.Msg["CONTROLS_FOR_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#count-with";
Blockly.Msg["CONTROLS_FOR_TITLE"] = "%1 を %2 から %3 まで %4 ずつカウントする";
Blockly.Msg["CONTROLS_FOR_TOOLTIP"] = "変数 '%1' が開始番号から終了番号まで指定した間隔での値をとって、指定したブロックを実行する。";
Blockly.Msg["CONTROLS_IF_ELSEIF_TOOLTIP"] = "「もしも」のブロックに条件を追加します。";
Blockly.Msg["CONTROLS_IF_ELSE_TOOLTIP"] = "Ifブロックに、すべてをキャッチする条件を追加。";
Blockly.Msg["CONTROLS_IF_HELPURL"] = "https://github.com/google/blockly/wiki/IfElse";
Blockly.Msg["CONTROLS_IF_IF_TOOLTIP"] = "追加、削除、またはセクションを順序変更して、ブロックをこれを再構成します。";
Blockly.Msg["CONTROLS_IF_MSG_ELSE"] = "そうでなければ";
Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"] = "そうでなくもし";
Blockly.Msg["CONTROLS_IF_MSG_IF"] = "もし";
Blockly.Msg["CONTROLS_IF_TOOLTIP_1"] = "値が true の場合、ステートメントを実行します。";
Blockly.Msg["CONTROLS_IF_TOOLTIP_2"] = "値が true の場合は、最初のステートメントのブロックを実行します。それ以外の場合は、2番目のステートメントのブロックを実行します。";
Blockly.Msg["CONTROLS_IF_TOOLTIP_3"] = "最初の値が true の場合は、最初のステートメントのブロックを実行します。それ以外の場合で、2番目の値が true の場合は、2番目のステートメントのブロックを実行します。";
Blockly.Msg["CONTROLS_IF_TOOLTIP_4"] = "最初の値が true の場合は、最初のステートメントのブロックを実行します。それ以外の場合で、2番目の値が true の場合は、2番目のステートメントのブロックを実行します。すべての値が true でない場合は、最後のステートメントのブロックを実行します。";
Blockly.Msg["CONTROLS_REPEAT_HELPURL"] = "https://ja.wikipedia.org/wiki/for文";
Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"] = "実行";
Blockly.Msg["CONTROLS_REPEAT_TITLE"] = "%1 回繰り返す";
Blockly.Msg["CONTROLS_REPEAT_TOOLTIP"] = "いくつかのステートメントを数回実行します。";
Blockly.Msg["CONTROLS_WHILEUNTIL_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#repeat";
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_UNTIL"] = "繰り返す：終わる条件";
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_WHILE"] = "繰り返す：続ける条件";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL"] = "値がfalseの間、いくつかのステートメントを実行する。";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_WHILE"] = "値がtrueの間、いくつかのステートメントを実行する。";
Blockly.Msg["CONTROL_ARDUINO_LOOP"] = "";  // untranslated
Blockly.Msg["CONTROL_ARDUINO_SETUP"] = "";  // untranslated
Blockly.Msg["CONTROL_GROUP"] = "";  // untranslated
Blockly.Msg["DELETE_ALL_BLOCKS"] = "%1個あるすべてのブロックを削除しますか？";
Blockly.Msg["DELETE_BLOCK"] = "ブロックを削除";
Blockly.Msg["DELETE_X_BLOCKS"] = "%1個のブロックを削除";
Blockly.Msg["DEPRECATED"] = "";  // untranslated
Blockly.Msg["DISABLE_BLOCK"] = "ブロックを無効にする";
Blockly.Msg["DOMOTICS_INA219_CURRENT"] = "";  // untranslated
Blockly.Msg["DOMOTICS_INA219_INIT"] = "";  // untranslated
Blockly.Msg["DOMOTICS_INA219_POWER"] = "";  // untranslated
Blockly.Msg["DOMOTICS_INA219_VOLTAGE"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_CURRENT"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_ENERGY"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_FREQUENCY"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_INIT"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_POWER"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_POWERFACTOR"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_SETADDRESS"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_VALUE"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_VOLTAGE"] = "";  // untranslated
Blockly.Msg["DOWN"] = "";  // untranslated
Blockly.Msg["DUPLICATE_BLOCK"] = "複製";
Blockly.Msg["EEPROM_ADDRESS"] = "";  // untranslated
Blockly.Msg["EEPROM_READ"] = "";  // untranslated
Blockly.Msg["EEPROM_WRITE"] = "";  // untranslated
Blockly.Msg["ENABLE_BLOCK"] = "ブロックを有効にする";
Blockly.Msg["EXPAND_ALL"] = "ブロックを展開する";
Blockly.Msg["EXPAND_BLOCK"] = "ブロックを展開する";
Blockly.Msg["EXTERNAL_INPUTS"] = "外部入力";
Blockly.Msg["FILTER_MEDIAN"] = "";  // untranslated
Blockly.Msg["FILTER_MEDIAN_ADD"] = "";  // untranslated
Blockly.Msg["FILTER_MEDIAN_SAMPLES"] = "";  // untranslated
Blockly.Msg["FILTER_MEDIAN_SETWINDOW"] = "";  // untranslated
Blockly.Msg["FORWARD"] = "";  // untranslated
Blockly.Msg["GPS_DAY"] = "";  // untranslated
Blockly.Msg["GPS_DISTANCEBETWEEN"] = "";  // untranslated
Blockly.Msg["GPS_GETALTITUDE"] = "";  // untranslated
Blockly.Msg["GPS_GETCOURSE"] = "";  // untranslated
Blockly.Msg["GPS_GETDATETIME"] = "";  // untranslated
Blockly.Msg["GPS_GETPOSITION"] = "";  // untranslated
Blockly.Msg["GPS_GETSPEED"] = "";  // untranslated
Blockly.Msg["GPS_HOUR"] = "";  // untranslated
Blockly.Msg["GPS_HUND"] = "";  // untranslated
Blockly.Msg["GPS_INIT"] = "";  // untranslated
Blockly.Msg["GPS_KMPH"] = "";  // untranslated
Blockly.Msg["GPS_LAT"] = "";  // untranslated
Blockly.Msg["GPS_LONG"] = "";  // untranslated
Blockly.Msg["GPS_MIN"] = "";  // untranslated
Blockly.Msg["GPS_MONTH"] = "";  // untranslated
Blockly.Msg["GPS_MPH"] = "";  // untranslated
Blockly.Msg["GPS_SEC"] = "";  // untranslated
Blockly.Msg["GPS_VALIDDATA"] = "";  // untranslated
Blockly.Msg["GPS_YEAR"] = "";  // untranslated
Blockly.Msg["HEIGHT"] = "";  // untranslated
Blockly.Msg["HELP"] = "ヘルプ";
Blockly.Msg["ID"] = "";  // untranslated
Blockly.Msg["INLINE_INPUTS"] = "インライン入力";
Blockly.Msg["IO_ANALOG_READ"] = "";  // untranslated
Blockly.Msg["IO_ANALOG_READ_DIF"] = "";  // untranslated
Blockly.Msg["IO_ANALOG_WRITE"] = "";  // untranslated
Blockly.Msg["IO_BOOLEAN_OFF"] = "";  // untranslated
Blockly.Msg["IO_BOOLEAN_ON"] = "";  // untranslated
Blockly.Msg["IO_CAPACITIVE_READ"] = "";  // untranslated
Blockly.Msg["IO_DIGITAL_READ"] = "";  // untranslated
Blockly.Msg["IO_DIGITAL_WRITE"] = "";  // untranslated
Blockly.Msg["IO_INTERRUPT"] = "";  // untranslated
Blockly.Msg["IO_PINMODE"] = "";  // untranslated
Blockly.Msg["IO_PINMODE_AS"] = "";  // untranslated
Blockly.Msg["IO_PULSEIN"] = "";  // untranslated
Blockly.Msg["IO_PULSEIN_TIMEOUT"] = "";  // untranslated
Blockly.Msg["KEYBOARD"] = "";  // untranslated
Blockly.Msg["KEYBOARD_KEY"] = "";  // untranslated
Blockly.Msg["KEYBOARD_KEYSTROKE"] = "";  // untranslated
Blockly.Msg["KEYBOARD_PRESS"] = "";  // untranslated
Blockly.Msg["KEYBOARD_RELEASE"] = "";  // untranslated
Blockly.Msg["KEYBOT_BUZZER"] = "";  // untranslated
Blockly.Msg["KEYBOT_BUZZER_FREQ"] = "";  // untranslated
Blockly.Msg["KEYBOT_DISTANCE"] = "";  // untranslated
Blockly.Msg["KEYBOT_IRSENSOR"] = "";  // untranslated
Blockly.Msg["KEYBOT_IRSENSOR_LEFT"] = "";  // untranslated
Blockly.Msg["KEYBOT_IRSENSOR_MIDDLE"] = "";  // untranslated
Blockly.Msg["KEYBOT_IRSENSOR_RIGHT"] = "";  // untranslated
Blockly.Msg["KEYBOT_LEFT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOTOR"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_BACKWARD"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_FAST"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_FORWARD"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_LEFT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_NORMAL"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_RIGHT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_ROTATE_LEFT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_ROTATE_RIGHT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_SLOW"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_SPEED"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_STOP"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_VERYFAST"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_VERYSLOW"] = "";  // untranslated
Blockly.Msg["KEYBOT_RIGHT"] = "";  // untranslated
Blockly.Msg["KEYPAD"] = "";  // untranslated
Blockly.Msg["KEYPAD_COL"] = "";  // untranslated
Blockly.Msg["KEYPAD_KEY"] = "";  // untranslated
Blockly.Msg["KEYPAD_NOKEY"] = "";  // untranslated
Blockly.Msg["KEYPAD_ROW"] = "";  // untranslated
Blockly.Msg["LCD"] = "";  // untranslated
Blockly.Msg["LCD_BACKLIGHT"] = "";  // untranslated
Blockly.Msg["LCD_BEGIN"] = "";  // untranslated
Blockly.Msg["LCD_BEGIN_I2C"] = "";  // untranslated
Blockly.Msg["LCD_BLINK"] = "";  // untranslated
Blockly.Msg["LCD_CLEAR"] = "";  // untranslated
Blockly.Msg["LCD_COL"] = "";  // untranslated
Blockly.Msg["LCD_CURSOR"] = "";  // untranslated
Blockly.Msg["LCD_DEFINE"] = "";  // untranslated
Blockly.Msg["LCD_DISPLAY"] = "";  // untranslated
Blockly.Msg["LCD_PRINT"] = "";  // untranslated
Blockly.Msg["LCD_ROW"] = "";  // untranslated
Blockly.Msg["LCD_SCROLL"] = "";  // untranslated
Blockly.Msg["LCD_SYMBOL"] = "";  // untranslated
Blockly.Msg["LEDMATRIX"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_CLEAR"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_DRAWBITMAP"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_DRAWCIRCLE"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_DRAWPIXEL"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_DRAWTEXT"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_FILL"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_INIT"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_LINE"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_RECTANGLE"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_ROTATION"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_ROUND"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_SHOW"] = "";  // untranslated
Blockly.Msg["LEFT"] = "";  // untranslated
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"] = "リスト";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"] = "追加、削除、またはセクションの順序変更をして、このリスト・ブロックを再構成する。";
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH"] = "以下を使ってリストを作成：";
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH_TEXT"] = "";  // untranslated
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TOOLTIP"] = "リストに項目を追加。";
Blockly.Msg["LISTS_GET_INDEX_FROM_START"] = "#";
Blockly.Msg["LISTS_GET_INDEX_GET"] = "取得";
Blockly.Msg["LISTS_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#length-of";
Blockly.Msg["LISTS_LENGTH_TITLE"] = "%1の長さ";
Blockly.Msg["LISTS_LENGTH_TOOLTIP"] = "リストの長さを返します。";
Blockly.Msg["LISTS_LISTNAME"] = "";  // untranslated
Blockly.Msg["LISTS_LISTNAME_TEXT"] = "";  // untranslated
Blockly.Msg["LISTS_SET_INDEX_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#in-list--set";
Blockly.Msg["LISTS_SET_INDEX_SET"] = "セット";
Blockly.Msg["LOGIC_BOOLEAN_FALSE"] = "false";
Blockly.Msg["LOGIC_BOOLEAN_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#values";
Blockly.Msg["LOGIC_BOOLEAN_TOOLTIP"] = "true または false を返します。";
Blockly.Msg["LOGIC_BOOLEAN_TRUE"] = "true";
Blockly.Msg["LOGIC_COMPARE_HELPURL"] = "https://ja.wikipedia.org/wiki/不等式";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_EQ"] = "両方の入力が互いに等しい場合に true を返します。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GT"] = "最初の入力が 2 番目の入力よりも大きい場合は true を返します。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GTE"] = "最初の入力が 2 番目の入力以上の場合に true を返します。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LT"] = "最初の入力が 2 番目の入力よりも小さい場合は true を返します。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LTE"] = "最初の入力が 2 番目の入力以下の場合に true を返します。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_NEQ"] = "両方の入力が互いに等しくない場合に true を返します。";
Blockly.Msg["LOGIC_NEGATE_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#not";
Blockly.Msg["LOGIC_NEGATE_TITLE"] = "%1ではない";
Blockly.Msg["LOGIC_NEGATE_TOOLTIP"] = "入力が false の場合は、true を返します。入力が true の場合は false を返します。";
Blockly.Msg["LOGIC_OPERATION_AND"] = "かつ";
Blockly.Msg["LOGIC_OPERATION_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#logical-operations";
Blockly.Msg["LOGIC_OPERATION_OR"] = "または";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_AND"] = "両方の入力が true のときに true を返します。";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_OR"] = "少なくとも 1 つの入力が true のときに true を返します。";
Blockly.Msg["MATH_ADDITION_SYMBOL"] = "+";
Blockly.Msg["MATH_ANGLE"] = "";  // untranslated
Blockly.Msg["MATH_ARITHMETIC_HELPURL"] = "https://ja.wikipedia.org/wiki/算術";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_ADD"] = "2 つの数の合計を返します。";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_DIVIDE"] = "2 つの数の商を返します。";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MINUS"] = "2 つの数の差を返します。";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MULTIPLY"] = "2 つの数の積を返します。";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_POWER"] = "最初の数を2 番目の値で累乗した結果を返します。";
Blockly.Msg["MATH_CHANGE_HELPURL"] = "https://ja.wikipedia.org/wiki/加法";
Blockly.Msg["MATH_CHANGE_TITLE"] = "%1 を %2 増やす";
Blockly.Msg["MATH_CHANGE_TOOLTIP"] = "変数'%1'に数をたす。";
Blockly.Msg["MATH_CONSTANT_HELPURL"] = "https://ja.wikipedia.org/wiki/数学定数";
Blockly.Msg["MATH_CONSTANT_TOOLTIP"] = "いずれかの共通の定数のを返す: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), or ∞ (無限).";
Blockly.Msg["MATH_CONSTRAIN_HELPURL"] = "https://en.wikipedia.org/wiki/Clamping_(graphics)";
Blockly.Msg["MATH_CONSTRAIN_TITLE"] = "%1 を %2 以上 %3 以下の範囲に制限";
Blockly.Msg["MATH_CONSTRAIN_TOOLTIP"] = "指定した上限と下限の間に値を制限する（上限と下限の値を含む）。";
Blockly.Msg["MATH_DIVISION_SYMBOL"] = "÷";
Blockly.Msg["MATH_MAP_HELPURL"] = "";  // untranslated
Blockly.Msg["MATH_MAP_TITLE"] = "";  // untranslated
Blockly.Msg["MATH_MAP_TOOLTIP"] = "";  // untranslated
Blockly.Msg["MATH_MODULO_HELPURL"] = "https://en.wikipedia.org/wiki/Modulo_operation";
Blockly.Msg["MATH_MODULO_TITLE"] = "%1÷%2の余り";
Blockly.Msg["MATH_MODULO_TOOLTIP"] = "2つの数値の割り算の余りを返す。";
Blockly.Msg["MATH_MULTIPLICATION_SYMBOL"] = "×";
Blockly.Msg["MATH_NUMBER_HELPURL"] = "https://ja.wikipedia.org/wiki/数";
Blockly.Msg["MATH_NUMBER_TOOLTIP"] = "数です。";
Blockly.Msg["MATH_POWER_SYMBOL"] = "^";
Blockly.Msg["MATH_RANDOM_INT_HELPURL"] = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg["MATH_RANDOM_INT_TITLE"] = "%1から%2までのランダムな整数";
Blockly.Msg["MATH_RANDOM_INT_TOOLTIP"] = "指定された（上下限を含む）範囲のランダムな整数を返します。";
Blockly.Msg["MATH_ROUND_HELPURL"] = "https://ja.wikipedia.org/wiki/端数処理";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUND"] = "四捨五入";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDDOWN"] = "切り捨て";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDUP"] = "切り上げ";
Blockly.Msg["MATH_ROUND_TOOLTIP"] = "数値を切り上げるか切り捨てる";
Blockly.Msg["MATH_SINGLE_HELPURL"] = "https://ja.wikipedia.org/wiki/平方根";
Blockly.Msg["MATH_SINGLE_OP_ABSOLUTE"] = "絶対値";
Blockly.Msg["MATH_SINGLE_OP_ROOT"] = "平方根";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ABS"] = "絶対値を返す。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_EXP"] = "ネイピア数eの数値乗を返す。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LN"] = "数値の自然対数を返す。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LOG10"] = "底が10の対数を返す。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_NEG"] = "負の数を返す。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_POW10"] = "10の数値乗を返す。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ROOT"] = "平方根を返す。";
Blockly.Msg["MATH_SUBTRACTION_SYMBOL"] = "-";
Blockly.Msg["MATH_TO_INT"] = "";  // untranslated
Blockly.Msg["MATH_TO_UINT"] = "";  // untranslated
Blockly.Msg["MATH_TRIG_ACOS"] = "acos";
Blockly.Msg["MATH_TRIG_ASIN"] = "asin";
Blockly.Msg["MATH_TRIG_ATAN"] = "atan";
Blockly.Msg["MATH_TRIG_ATAN2"] = "";  // untranslated
Blockly.Msg["MATH_TRIG_COS"] = "cos";
Blockly.Msg["MATH_TRIG_HELPURL"] = "https://ja.wikipedia.org/wiki/三角関数";
Blockly.Msg["MATH_TRIG_SIN"] = "sin";
Blockly.Msg["MATH_TRIG_TAN"] = "tan";
Blockly.Msg["MATH_TRIG_TOOLTIP_ACOS"] = "アークコサイン（arccosin）を返す。";
Blockly.Msg["MATH_TRIG_TOOLTIP_ASIN"] = "アークサイン（arcsin）を返す。";
Blockly.Msg["MATH_TRIG_TOOLTIP_ATAN"] = "アークタンジェント（arctan）を返す。";
Blockly.Msg["MATH_TRIG_TOOLTIP_ATAN2"] = "";  // untranslated
Blockly.Msg["MATH_TRIG_TOOLTIP_COS"] = "（ラジアンではなく）度数の余弦（cosin）を返す。";
Blockly.Msg["MATH_TRIG_TOOLTIP_SIN"] = "（ラジアンではなく）度数の正弦（sin）を返す。";
Blockly.Msg["MATH_TRIG_TOOLTIP_TAN"] = "（ラジアンではなく）度数の正接（tan）を返す。";
Blockly.Msg["MOTORSHIELD_DC"] = "";  // untranslated
Blockly.Msg["MOTORSHIELD_SERVO"] = "";  // untranslated
Blockly.Msg["MOTORSHIELD_STEPPER"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_BW"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_FW"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_INIT"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_MOTOR"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_MOVE"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_SPEED"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298P"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_DEGREE_RANGE"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_DELAY"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_AMPLITUDE"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_OFFSET"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_PERIOD"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_PHASE"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_REFRESH"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_RESET"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_SET"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_START"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_STOP"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_READ"] = "";  // untranslated
Blockly.Msg["MOTOR_STEPPER"] = "";  // untranslated
Blockly.Msg["MOTOR_STEPPER_RPM"] = "";  // untranslated
Blockly.Msg["MOTOR_STEPPER_STEP"] = "";  // untranslated
Blockly.Msg["MOTOR_STEPPER_STEPS"] = "";  // untranslated
Blockly.Msg["MOUSE"] = "";  // untranslated
Blockly.Msg["MOUSE_BUTTON"] = "";  // untranslated
Blockly.Msg["MOUSE_CLICK"] = "";  // untranslated
Blockly.Msg["MOUSE_MIDDLE"] = "";  // untranslated
Blockly.Msg["MOUSE_MOVE"] = "";  // untranslated
Blockly.Msg["MOUSE_WHEEL"] = "";  // untranslated
Blockly.Msg["MP3_CONTROL"] = "";  // untranslated
Blockly.Msg["MP3_EQ"] = "";  // untranslated
Blockly.Msg["MP3_FILE"] = "";  // untranslated
Blockly.Msg["MP3_FOLDER"] = "";  // untranslated
Blockly.Msg["MP3_INIT"] = "";  // untranslated
Blockly.Msg["MP3_NEXT"] = "";  // untranslated
Blockly.Msg["MP3_PAUSE"] = "";  // untranslated
Blockly.Msg["MP3_PLAY"] = "";  // untranslated
Blockly.Msg["MP3_PREV"] = "";  // untranslated
Blockly.Msg["MP3_REPEAT"] = "";  // untranslated
Blockly.Msg["MP3_RESET"] = "";  // untranslated
Blockly.Msg["MP3_SHUFFLE"] = "";  // untranslated
Blockly.Msg["MP3_STOP"] = "";  // untranslated
Blockly.Msg["MP3_VOLUME"] = "";  // untranslated
Blockly.Msg["MQTT_BROKER"] = "";  // untranslated
Blockly.Msg["MQTT_CLIENTID"] = "";  // untranslated
Blockly.Msg["MQTT_INIT"] = "";  // untranslated
Blockly.Msg["MQTT_ISCONNECTED"] = "";  // untranslated
Blockly.Msg["MQTT_MAC"] = "";  // untranslated
Blockly.Msg["MQTT_PASS"] = "";  // untranslated
Blockly.Msg["MQTT_PORT"] = "";  // untranslated
Blockly.Msg["MQTT_PUB"] = "";  // untranslated
Blockly.Msg["MQTT_SUB"] = "";  // untranslated
Blockly.Msg["MQTT_TOPIC"] = "";  // untranslated
Blockly.Msg["MQTT_USER"] = "";  // untranslated
Blockly.Msg["MQTT_VALUE"] = "";  // untranslated
Blockly.Msg["MQTT_WIFI_NAME"] = "";  // untranslated
Blockly.Msg["MQTT_WIFI_PASS"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_CLEAR"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_INIT"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_LEDCOUNT"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_PIXEL"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_SETMATRIX"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_SETPIXEL"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_SETRAW"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_SHOW"] = "";  // untranslated
Blockly.Msg["NEW_VARIABLE"] = "変数の作成…";
Blockly.Msg["NEW_VARIABLE_TITLE"] = "新しい変数の名前:";
Blockly.Msg["NOTE_A"] = "";  // untranslated
Blockly.Msg["NOTE_AS"] = "";  // untranslated
Blockly.Msg["NOTE_B"] = "";  // untranslated
Blockly.Msg["NOTE_C"] = "";  // untranslated
Blockly.Msg["NOTE_CS"] = "";  // untranslated
Blockly.Msg["NOTE_D"] = "";  // untranslated
Blockly.Msg["NOTE_DS"] = "";  // untranslated
Blockly.Msg["NOTE_E"] = "";  // untranslated
Blockly.Msg["NOTE_F"] = "";  // untranslated
Blockly.Msg["NOTE_FS"] = "";  // untranslated
Blockly.Msg["NOTE_G"] = "";  // untranslated
Blockly.Msg["NOTE_GS"] = "";  // untranslated
Blockly.Msg["NUMBER"] = "";  // untranslated
Blockly.Msg["NUNCHUK"] = "";  // untranslated
Blockly.Msg["NUNCHUK_X"] = "";  // untranslated
Blockly.Msg["NUNCHUK_Y"] = "";  // untranslated
Blockly.Msg["NUNCHUK_aX"] = "";  // untranslated
Blockly.Msg["NUNCHUK_aY"] = "";  // untranslated
Blockly.Msg["NUNCHUK_aZ"] = "";  // untranslated
Blockly.Msg["NUNCHUK_bC"] = "";  // untranslated
Blockly.Msg["NUNCHUK_bZ"] = "";  // untranslated
Blockly.Msg["OK"] = "";  // untranslated
Blockly.Msg["OLED_AUTOSHOW"] = "";  // untranslated
Blockly.Msg["OTTO_AMP"] = "";  // untranslated
Blockly.Msg["OTTO_AMP_BIG"] = "";  // untranslated
Blockly.Msg["OTTO_AMP_NORMAL"] = "";  // untranslated
Blockly.Msg["OTTO_AMP_SMALL"] = "";  // untranslated
Blockly.Msg["OTTO_BUTTON"] = "";  // untranslated
Blockly.Msg["OTTO_CALIBRATE"] = "";  // untranslated
Blockly.Msg["OTTO_CALIB_FOOTL"] = "";  // untranslated
Blockly.Msg["OTTO_CALIB_FOOTR"] = "";  // untranslated
Blockly.Msg["OTTO_CALIB_LEGL"] = "";  // untranslated
Blockly.Msg["OTTO_CALIB_LEGR"] = "";  // untranslated
Blockly.Msg["OTTO_DISTANCE"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_ANGRY"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_CONFUSED"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_FAIL"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_FART"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_FRETFUL"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_HAPPY"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_LOVE"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_MAGIC"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_SAD"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_SLEEPING"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_SUPERHAPPY"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_VICTORY"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_WAVE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_ANGRY"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_BIGSURPRISE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_CLEAR"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_CONFUSED"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_CULITO"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_DIAGONAL"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_EIGHT"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_FIVE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_FOUR"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_HAPPYCLOSED"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_HAPPYOPEN"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_HEART"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_INTERROGATION"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_LINEMOUTH"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_NINE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_OKMOUTH"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_ONE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SAD"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SADCLOSED"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SADOPEN"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SEVEN"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SIX"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SMALLSURPRISE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SMILE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_THREE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_THUNDER"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_TONGUEOUT"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_TWO"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_VAMP1"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_VAMP2"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_XMOUTH"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_ZERO"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE2"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_ASCTURN"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_BENDL"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_BENDR"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_CRUSAITO1"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_CRUSAITO2"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_FLAPPING1"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_FLAPPING2"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_HOME"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_JITTER"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_JUMP"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_MOONWALKL"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_MOONWALKR"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_SHAKEL"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_SHAKER"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_SWING"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_TIPTOESWING"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_TURNL"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_TURNR"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_UPDOWN"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_WALKB"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_WALKF"] = "";  // untranslated
Blockly.Msg["OTTO_NOISE"] = "";  // untranslated
Blockly.Msg["OTTO_NOTE"] = "";  // untranslated
Blockly.Msg["OTTO_NOTE_DURATION"] = "";  // untranslated
Blockly.Msg["OTTO_SING"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_BUTTON"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_CONFUSED"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_CONNECTION"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_CUDDLY"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_DISCONNECTION"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_FART1"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_FART2"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_FART3"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_HAPPY"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_HAPPYSHOR"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_MODE1"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_MODE2"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_MODE3"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_OH2"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_OH_"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_SAD"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_SLEEPING"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_SUPERHAPPY"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_SURPRISE"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_FAST"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_NORMAL"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_SLOW"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_VERYFAST"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_VERYSLOW"] = "";  // untranslated
Blockly.Msg["PIN"] = "";  // untranslated
Blockly.Msg["PRESSED"] = "";  // untranslated
Blockly.Msg["PROCEDURES_ALLOW_STATEMENTS"] = "ステートメントを許可";
Blockly.Msg["PROCEDURES_BEFORE_PARAMS"] = "引数：";
Blockly.Msg["PROCEDURES_CALLNORETURN_HELPURL"] = "https://ja.wikipedia.org/wiki/サブルーチン";
Blockly.Msg["PROCEDURES_CALLNORETURN_TOOLTIP"] = "ユーザー定義関数 '%1' を実行します。";
Blockly.Msg["PROCEDURES_CALLRETURN_HELPURL"] = "https://ja.wikipedia.org/wiki/サブルーチン";
Blockly.Msg["PROCEDURES_CALLRETURN_TOOLTIP"] = "ユーザー定義関数 '%1' を実行し、その出力を使用します。";
Blockly.Msg["PROCEDURES_CALL_BEFORE_PARAMS"] = "引数：";
Blockly.Msg["PROCEDURES_CREATE_DO"] = "'%1' を作成";
Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"] = "この関数の説明…";
Blockly.Msg["PROCEDURES_DEFNORETURN_DO"] = "";
Blockly.Msg["PROCEDURES_DEFNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";
Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"] = "何かする";
Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"] = "関数";
Blockly.Msg["PROCEDURES_DEFNORETURN_TOOLTIP"] = "出力なしの関数を作成します。";
Blockly.Msg["PROCEDURES_DEFRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";
Blockly.Msg["PROCEDURES_DEFRETURN_RETURN"] = "返す";
Blockly.Msg["PROCEDURES_DEFRETURN_TOOLTIP"] = "一つの出力を持つ関数を作成します。";
Blockly.Msg["PROCEDURES_DEF_DUPLICATE_WARNING"] = "警告: この関数には重複するパラメーターがあります。";
Blockly.Msg["PROCEDURES_HIGHLIGHT_DEF"] = "関数の内容を強調表示します。";
Blockly.Msg["PROCEDURES_MUTATORARG_TITLE"] = "入力名:";
Blockly.Msg["PROCEDURES_MUTATORARG_TOOLTIP"] = "関数への入力の追加。";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TITLE"] = "入力";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TOOLTIP"] = "この関数への入力の追加、削除、順番変更。";
Blockly.Msg["REDO"] = "やり直す";
Blockly.Msg["REMOVE_COMMENT"] = "コメントを削除";
Blockly.Msg["RENAME_VARIABLE"] = "変数の名前を変える…";
Blockly.Msg["RENAME_VARIABLE_TITLE"] = "選択した%1個すべての変数の名前を変える：";
Blockly.Msg["RFID_EJECTCARD"] = "";  // untranslated
Blockly.Msg["RFID_INIT"] = "";  // untranslated
Blockly.Msg["RFID_NEWCARDPRESENT"] = "";  // untranslated
Blockly.Msg["RFID_READUID"] = "";  // untranslated
Blockly.Msg["RIGHT"] = "";  // untranslated
Blockly.Msg["RTC"] = "";  // untranslated
Blockly.Msg["RTC_DATE_TEXT"] = "";  // untranslated
Blockly.Msg["RTC_DAY"] = "";  // untranslated
Blockly.Msg["RTC_DAYOFWEEK"] = "";  // untranslated
Blockly.Msg["RTC_FRIDAY"] = "";  // untranslated
Blockly.Msg["RTC_HOUR"] = "";  // untranslated
Blockly.Msg["RTC_MINUTE"] = "";  // untranslated
Blockly.Msg["RTC_MONDAY"] = "";  // untranslated
Blockly.Msg["RTC_MONTH"] = "";  // untranslated
Blockly.Msg["RTC_SATURDAY"] = "";  // untranslated
Blockly.Msg["RTC_SECOND"] = "";  // untranslated
Blockly.Msg["RTC_SUNDAY"] = "";  // untranslated
Blockly.Msg["RTC_THURSDAY"] = "";  // untranslated
Blockly.Msg["RTC_TIME_TEXT"] = "";  // untranslated
Blockly.Msg["RTC_TUESDAY"] = "";  // untranslated
Blockly.Msg["RTC_WEDNESDAY"] = "";  // untranslated
Blockly.Msg["RTC_YEAR"] = "";  // untranslated
Blockly.Msg["SD_BEGIN"] = "";  // untranslated
Blockly.Msg["SD_EXISTS"] = "";  // untranslated
Blockly.Msg["SD_POS"] = "";  // untranslated
Blockly.Msg["SD_PRINT"] = "";  // untranslated
Blockly.Msg["SD_READBYTE"] = "";  // untranslated
Blockly.Msg["SD_READLOOP"] = "";  // untranslated
Blockly.Msg["SD_REMOVE"] = "";  // untranslated
Blockly.Msg["SD_SIZE"] = "";  // untranslated
Blockly.Msg["SD_WRITEBYTE"] = "";  // untranslated
Blockly.Msg["SENSOR_18B20"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL_ADXL345"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL_X"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL_Y"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL_Z"] = "";  // untranslated
Blockly.Msg["SENSOR_AIR"] = "";  // untranslated
Blockly.Msg["SENSOR_ALCOHOL"] = "";  // untranslated
Blockly.Msg["SENSOR_ALTITUDE"] = "";  // untranslated
Blockly.Msg["SENSOR_BAROMETRIC"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON_DEBOUNCED"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON_DEBOUNCED_PRESSED"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON_DEBOUNCED_RELEASED"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON_INVERT"] = "";  // untranslated
Blockly.Msg["SENSOR_CCS811"] = "";  // untranslated
Blockly.Msg["SENSOR_CCS811_CO2"] = "";  // untranslated
Blockly.Msg["SENSOR_CCS811_CO2_UGM3"] = "";  // untranslated
Blockly.Msg["SENSOR_CCS811_TVOC"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_BLACK"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_BLUE"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_CYAN"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_GREEN"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_HSV_H"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_HSV_S"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_HSV_V"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_ISCOLOR"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_NAME"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_ORANGE"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_PURPLE"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_READCOLOR"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RED"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RGB_B"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RGB_CLEAR"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RGB_G"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RGB_R"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_WHITE"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_YELLOW"] = "";  // untranslated
Blockly.Msg["SENSOR_CRASH"] = "";  // untranslated
Blockly.Msg["SENSOR_DATA_RAW"] = "";  // untranslated
Blockly.Msg["SENSOR_DHT11"] = "";  // untranslated
Blockly.Msg["SENSOR_DHT22"] = "";  // untranslated
Blockly.Msg["SENSOR_DS18B20"] = "";  // untranslated
Blockly.Msg["SENSOR_FLAME"] = "";  // untranslated
Blockly.Msg["SENSOR_GAS"] = "";  // untranslated
Blockly.Msg["SENSOR_HALL"] = "";  // untranslated
Blockly.Msg["SENSOR_HUMIDITY"] = "";  // untranslated
Blockly.Msg["SENSOR_IRRX"] = "";  // untranslated
Blockly.Msg["SENSOR_JOYSTICK"] = "";  // untranslated
Blockly.Msg["SENSOR_KNOCK"] = "";  // untranslated
Blockly.Msg["SENSOR_LDR"] = "";  // untranslated
Blockly.Msg["SENSOR_LINETRACKING"] = "";  // untranslated
Blockly.Msg["SENSOR_LM35"] = "";  // untranslated
Blockly.Msg["SENSOR_MICS4514"] = "";  // untranslated
Blockly.Msg["SENSOR_MLX90614"] = "";  // untranslated
Blockly.Msg["SENSOR_MLX90614_AMBIENT"] = "";  // untranslated
Blockly.Msg["SENSOR_MLX90614_OBJECT"] = "";  // untranslated
Blockly.Msg["SENSOR_NTC"] = "";  // untranslated
Blockly.Msg["SENSOR_OBSTACLE"] = "";  // untranslated
Blockly.Msg["SENSOR_PAJ7620"] = "";  // untranslated
Blockly.Msg["SENSOR_PHOTOINT"] = "";  // untranslated
Blockly.Msg["SENSOR_PIR"] = "";  // untranslated
Blockly.Msg["SENSOR_PM25"] = "";  // untranslated
Blockly.Msg["SENSOR_PM25_DENSITY"] = "";  // untranslated
Blockly.Msg["SENSOR_PM25_PARTICLESM3"] = "";  // untranslated
Blockly.Msg["SENSOR_POT"] = "";  // untranslated
Blockly.Msg["SENSOR_PRESSURE"] = "";  // untranslated
Blockly.Msg["SENSOR_REED"] = "";  // untranslated
Blockly.Msg["SENSOR_ROTARY_ENCODER"] = "";  // untranslated
Blockly.Msg["SENSOR_ROTARY_ENCODER_POS"] = "";  // untranslated
Blockly.Msg["SENSOR_SOILHUMIDITY"] = "";  // untranslated
Blockly.Msg["SENSOR_SOUND"] = "";  // untranslated
Blockly.Msg["SENSOR_TEMPERATURE"] = "";  // untranslated
Blockly.Msg["SENSOR_TEMT6000"] = "";  // untranslated
Blockly.Msg["SENSOR_TILT"] = "";  // untranslated
Blockly.Msg["SENSOR_TMP36"] = "";  // untranslated
Blockly.Msg["SENSOR_TOUCH"] = "";  // untranslated
Blockly.Msg["SENSOR_ULTRASONIC"] = "";  // untranslated
Blockly.Msg["SENSOR_ULTRASONIC_MAXDISTANCE"] = "";  // untranslated
Blockly.Msg["SENSOR_VIBRATION"] = "";  // untranslated
Blockly.Msg["SENSOR_VL53L0X"] = "";  // untranslated
Blockly.Msg["SENSOR_WATER"] = "";  // untranslated
Blockly.Msg["SERIAL_AVAILABLE"] = "";  // untranslated
Blockly.Msg["SERIAL_BAUDRATE"] = "";  // untranslated
Blockly.Msg["SERIAL_FLUSH"] = "";  // untranslated
Blockly.Msg["SERIAL_INIT"] = "";  // untranslated
Blockly.Msg["SERIAL_INT"] = "";  // untranslated
Blockly.Msg["SERIAL_PLOT"] = "";  // untranslated
Blockly.Msg["SERIAL_PLOTVALUE"] = "";  // untranslated
Blockly.Msg["SERIAL_PLOTVAR"] = "";  // untranslated
Blockly.Msg["SERIAL_PRINT"] = "";  // untranslated
Blockly.Msg["SERIAL_PRINTLN"] = "";  // untranslated
Blockly.Msg["SERIAL_READ"] = "";  // untranslated
Blockly.Msg["SERIAL_READBYTE"] = "";  // untranslated
Blockly.Msg["SERIAL_READFLOAT"] = "";  // untranslated
Blockly.Msg["SERIAL_READINT"] = "";  // untranslated
Blockly.Msg["SERIAL_READSTRING"] = "";  // untranslated
Blockly.Msg["SERIAL_READSTRINGLINE"] = "";  // untranslated
Blockly.Msg["SERIAL_TIMEOUT"] = "";  // untranslated
Blockly.Msg["SERIAL_WRITEBYTE"] = "";  // untranslated
Blockly.Msg["SHOP"] = "";  // untranslated
Blockly.Msg["SOUND_FREQ"] = "";  // untranslated
Blockly.Msg["SOUND_NOTE"] = "";  // untranslated
Blockly.Msg["SOUND_NOTONE"] = "";  // untranslated
Blockly.Msg["SOUND_PLAY"] = "";  // untranslated
Blockly.Msg["SOUND_TONE"] = "";  // untranslated
Blockly.Msg["STATUS"] = "";  // untranslated
Blockly.Msg["TEXT"] = "";  // untranslated
Blockly.Msg["TEXT_ASCII"] = "";  // untranslated
Blockly.Msg["TEXT_COMMENT"] = "";  // untranslated
Blockly.Msg["TEXT_CONTAINS"] = "";  // untranslated
Blockly.Msg["TEXT_CONTAINS_1"] = "";  // untranslated
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TOOLTIP"] = "テキストへ項目を追加。";
Blockly.Msg["TEXT_CREATE_JOIN_TITLE_JOIN"] = "結合";
Blockly.Msg["TEXT_CREATE_JOIN_TOOLTIP"] = "セクションを追加、削除、または順序変更して、ブロックを再構成。";
Blockly.Msg["TEXT_DECIMAL"] = "";  // untranslated
Blockly.Msg["TEXT_ENDSWITH"] = "";  // untranslated
Blockly.Msg["TEXT_EQUALS"] = "";  // untranslated
Blockly.Msg["TEXT_EQUALS_IGNORE"] = "";  // untranslated
Blockly.Msg["TEXT_FORMAT"] = "";  // untranslated
Blockly.Msg["TEXT_INDEXOF"] = "";  // untranslated
Blockly.Msg["TEXT_INDEXOF_1"] = "";  // untranslated
Blockly.Msg["TEXT_INDEXOF_FIRST"] = "";  // untranslated
Blockly.Msg["TEXT_INDEXOF_LAST"] = "";  // untranslated
Blockly.Msg["TEXT_JOIN_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-creation";
Blockly.Msg["TEXT_JOIN_TITLE_CREATEWITH"] = "テキストの作成：";
Blockly.Msg["TEXT_JOIN_TOOLTIP"] = "任意の数の項目一部を一緒に接合してテキストを作成。";
Blockly.Msg["TEXT_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";
Blockly.Msg["TEXT_LENGTH_TITLE"] = "%1の長さ";
Blockly.Msg["TEXT_LENGTH_TOOLTIP"] = "与えられたテキストの(スペースを含む)文字数を返す。";
Blockly.Msg["TEXT_LOWERCASE"] = "";  // untranslated
Blockly.Msg["TEXT_NOT_EQUALS"] = "";  // untranslated
Blockly.Msg["TEXT_REPLACE"] = "";  // untranslated
Blockly.Msg["TEXT_REPLACE_1"] = "";  // untranslated
Blockly.Msg["TEXT_REPLACE_2"] = "";  // untranslated
Blockly.Msg["TEXT_STARTSWITH"] = "";  // untranslated
Blockly.Msg["TEXT_SUBSTRING"] = "";  // untranslated
Blockly.Msg["TEXT_SUBSTRING_1"] = "";  // untranslated
Blockly.Msg["TEXT_SUBSTRING_2"] = "";  // untranslated
Blockly.Msg["TEXT_TEXT_HELPURL"] = "https://ja.wikipedia.org/wiki/文字列";
Blockly.Msg["TEXT_TEXT_TOOLTIP"] = "文字、単語、または行のテキスト。";
Blockly.Msg["TEXT_TONUMBER"] = "";  // untranslated
Blockly.Msg["TEXT_UPPERCASE"] = "";  // untranslated
Blockly.Msg["TIME_MICROS"] = "";  // untranslated
Blockly.Msg["TIME_MILLIS"] = "";  // untranslated
Blockly.Msg["TIME_RUNEVERYMS"] = "";  // untranslated
Blockly.Msg["TIME_SNOOZE"] = "";  // untranslated
Blockly.Msg["TIME_TIMER"] = "";  // untranslated
Blockly.Msg["TIME_TIMER_RESET"] = "";  // untranslated
Blockly.Msg["TIME_TIME_ELAPSED"] = "";  // untranslated
Blockly.Msg["TIME_WAIT"] = "";  // untranslated
Blockly.Msg["TIME_WAIT_FOREVER"] = "";  // untranslated
Blockly.Msg["TIME_WAIT_UNTIL"] = "";  // untranslated
Blockly.Msg["TIME_WAIT_WHILE"] = "";  // untranslated
Blockly.Msg["TO"] = "";  // untranslated
Blockly.Msg["TODAY"] = "今日";
Blockly.Msg["UNDO"] = "取り消す";
Blockly.Msg["UNTIL_NEW_LINE"] = "";  // untranslated
Blockly.Msg["UP"] = "";  // untranslated
Blockly.Msg["VALUE"] = "";  // untranslated
Blockly.Msg["VARIABLES_DEFAULT_NAME"] = "項目";
Blockly.Msg["VARIABLES_DEFAULT_NAME_BOOL"] = "";  // untranslated
Blockly.Msg["VARIABLES_DEFAULT_NAME_TEXT"] = "";  // untranslated
Blockly.Msg["VARIABLES_GET_CREATE_SET"] = "'セット%1を作成します。";
Blockly.Msg["VARIABLES_GET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#get";
Blockly.Msg["VARIABLES_GET_TOOLTIP"] = "この変数の値を返します。";
Blockly.Msg["VARIABLES_SET"] = "%1 に %2 をセット";
Blockly.Msg["VARIABLES_SET_CREATE_GET"] = "'%1 を取得' を作成します。";
Blockly.Msg["VARIABLES_SET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#set";
Blockly.Msg["VARIABLES_SET_TOOLTIP"] = "この入力を変数と等しくなるように設定します。";
Blockly.Msg["WAVE"] = "";  // untranslated
Blockly.Msg["WIDTH"] = "";  // untranslated
Blockly.Msg["WIFI_NAME"] = "";  // untranslated
Blockly.Msg["WIFI_PASS"] = "";  // untranslated
Blockly.Msg["WITH"] = "";  // untranslated
Blockly.Msg["_3DBOT_BUTTON"] = "";  // untranslated
Blockly.Msg["_3DBOT_BUZZER"] = "";  // untranslated
Blockly.Msg["_3DBOT_BUZZER_FREQ"] = "";  // untranslated
Blockly.Msg["_3DBOT_DISTANCE"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRRX"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRSENSOR"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRSENSOR_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRSENSOR_MIDDLE"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRSENSOR_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRTX"] = "";  // untranslated
Blockly.Msg["_3DBOT_LDR"] = "";  // untranslated
Blockly.Msg["_3DBOT_LED_GREEN"] = "";  // untranslated
Blockly.Msg["_3DBOT_LED_PWM"] = "";  // untranslated
Blockly.Msg["_3DBOT_LED_RED"] = "";  // untranslated
Blockly.Msg["_3DBOT_LED_YELLOW"] = "";  // untranslated
Blockly.Msg["_3DBOT_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOTOR"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_BACKWARD"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_BACKWARD_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_BACKWARD_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_FAST"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_FORWARD"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_NORMAL"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_ROTATE_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_ROTATE_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_SLOW"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_SPEED"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_STOP"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_VERYFAST"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_VERYSLOW"] = "";  // untranslated
Blockly.Msg["_3DBOT_NTC"] = "";  // untranslated
Blockly.Msg["_3DBOT_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_STEPS"] = "";  // untranslated
Blockly.Msg["_3DBOT_WAIT"] = "";  // untranslated
Blockly.Msg["CONTROLS_FOR_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_IF_ELSEIF_TITLE_ELSEIF"] = Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"];
Blockly.Msg["CONTROLS_IF_ELSE_TITLE_ELSE"] = Blockly.Msg["CONTROLS_IF_MSG_ELSE"];
Blockly.Msg["CONTROLS_IF_IF_TITLE_IF"] = Blockly.Msg["CONTROLS_IF_MSG_IF"];
Blockly.Msg["CONTROLS_IF_MSG_THEN"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_WHILEUNTIL_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TITLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["LISTS_GET_INDEX_HELPURL"] = Blockly.Msg["LISTS_INDEX_OF_HELPURL"];
Blockly.Msg["LISTS_GET_INDEX_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["MATH_CHANGE_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["PROCEDURES_DEFRETURN_COMMENT"] = Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"];
Blockly.Msg["PROCEDURES_DEFRETURN_DO"] = Blockly.Msg["PROCEDURES_DEFNORETURN_DO"];
Blockly.Msg["PROCEDURES_DEFRETURN_PROCEDURE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"];
Blockly.Msg["PROCEDURES_DEFRETURN_TITLE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"];
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
