// This file was automatically generated.  Do not modify.

'use strict';

Blockly.Msg["ACTUATOR_BUZZER"] = "";  // untranslated
Blockly.Msg["ACTUATOR_BUZZER_FREQ"] = "";  // untranslated
Blockly.Msg["ACTUATOR_BUZZER_TONE"] = "";  // untranslated
Blockly.Msg["ACTUATOR_IRTX"] = "";  // untranslated
Blockly.Msg["ACTUATOR_IRTX_BITS"] = "";  // untranslated
Blockly.Msg["ACTUATOR_IRTX_CODE"] = "";  // untranslated
Blockly.Msg["ACTUATOR_IRTX_PROTOCOL"] = "";  // untranslated
Blockly.Msg["ACTUATOR_LED"] = "";  // untranslated
Blockly.Msg["ACTUATOR_LED_PWM"] = "";  // untranslated
Blockly.Msg["ACTUATOR_RELAY"] = "";  // untranslated
Blockly.Msg["ACTUATOR_RGBLED"] = "";  // untranslated
Blockly.Msg["ADDRESS"] = "";  // untranslated
Blockly.Msg["ADD_COMMENT"] = "ಟಿಪ್ಪಣಿ ಸೇರ್ಸಲೆ";
Blockly.Msg["ADD_NEW_LINE"] = "";  // untranslated
Blockly.Msg["AND"] = "";  // untranslated
Blockly.Msg["ANTICLOCKWISE"] = "";  // untranslated
Blockly.Msg["AS"] = "";  // untranslated
Blockly.Msg["AS_STRING"] = "";  // untranslated
Blockly.Msg["BACKWARD"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_AVAILABLE"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_BAUDRATE"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_DEVNAME"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_FLUSH"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_INIT"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_PIN"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_PRINT"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_PRINTLN"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READ"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READBYTE"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READFLOAT"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READINT"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READSTRING"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_READSTRINGLINE"] = "";  // untranslated
Blockly.Msg["BLUETOOTH_WRITEBYTE"] = "";  // untranslated
Blockly.Msg["BLYNK_APP_CONNECTED"] = "";  // untranslated
Blockly.Msg["BLYNK_APP_DISCONNECTED"] = "";  // untranslated
Blockly.Msg["BLYNK_APP_READ"] = "";  // untranslated
Blockly.Msg["BLYNK_APP_WRITE"] = "";  // untranslated
Blockly.Msg["BLYNK_AUTH"] = "";  // untranslated
Blockly.Msg["BLYNK_CONNECTED"] = "";  // untranslated
Blockly.Msg["BLYNK_INIT"] = "";  // untranslated
Blockly.Msg["BLYNK_LCD_CLEAR"] = "";  // untranslated
Blockly.Msg["BLYNK_LCD_PRINT"] = "";  // untranslated
Blockly.Msg["BLYNK_LED"] = "";  // untranslated
Blockly.Msg["BLYNK_LED_INTENSITY"] = "";  // untranslated
Blockly.Msg["BLYNK_LOCALPORT"] = "";  // untranslated
Blockly.Msg["BLYNK_LOCALSERVER"] = "";  // untranslated
Blockly.Msg["BLYNK_MAP"] = "";  // untranslated
Blockly.Msg["BLYNK_PARAM_READ_INT"] = "";  // untranslated
Blockly.Msg["BLYNK_PARAM_READ_STRING"] = "";  // untranslated
Blockly.Msg["BLYNK_SET_PROPERTY"] = "";  // untranslated
Blockly.Msg["BLYNK_TERMINAL_CLEAR"] = "";  // untranslated
Blockly.Msg["BLYNK_TERMINAL_PRINT"] = "";  // untranslated
Blockly.Msg["BLYNK_TIMER"] = "";  // untranslated
Blockly.Msg["BLYNK_VIRTUALWRITE"] = "";  // untranslated
Blockly.Msg["BLYNK_VPIN"] = "";  // untranslated
Blockly.Msg["BLYNK_VPIN_VALUE"] = "";  // untranslated
Blockly.Msg["CHANGE_VALUE_TITLE"] = "ಮೌಲ್ಯೊನು ಬದಲ್ ಮಲ್ಪು";
Blockly.Msg["CLEAN_UP"] = "ಬ್ಲಾಕ್‍ಲೆನ್ ಸ್ವೊಚ್ಚೊ ಮಲ್ಪುಲೆ";
Blockly.Msg["CLOCKWISE"] = "";  // untranslated
Blockly.Msg["COLLAPSE_ALL"] = "ಮಾತಾ ತಡೆಕ್ಲೆನ ಮಾಹಿತಿನ್ ಎಲ್ಯ ಮಲ್ಪು";
Blockly.Msg["COLLAPSE_BLOCK"] = "ಎಲ್ಯೆ ಮಲ್ತ್‌ದ್ ತಡೆಲೆ";
Blockly.Msg["COLOUR"] = "";  // untranslated
Blockly.Msg["COL_BLUE"] = "";  // untranslated
Blockly.Msg["COL_GREEN"] = "";  // untranslated
Blockly.Msg["COL_RED"] = "";  // untranslated
Blockly.Msg["COMMON_ANODE"] = "";  // untranslated
Blockly.Msg["COMMON_CATHODE"] = "";  // untranslated
Blockly.Msg["CONTROLS_FOR_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg["CONTROLS_FOR_TITLE"] = "%2 ಡ್ದ್ %3 ಮುಟ %4 ಸರ್ತಿ %1 ದ ಒಟ್ಟುಗು ಗೆನ್ಪು";
Blockly.Msg["CONTROLS_FOR_TOOLTIP"] = "ನಿರ್ದಿಸ್ಟೊ ಮದ್ಯಂತರೊದ ಮೂಲಕೊ ದೆತೊಂದು '%1' ವ್ಯತ್ಯಯೊಡ್ ಸುರುತ್ತ ಅಂಕೆಡ್ದ್ ಕಡೆತ್ತ ಅಂಕೆ ಮುಟ್ಟದ ಮೌಲ್ಯೊನು ದೆತ್ತೊನಾವ್ ಬೊಕ್ಕ ನಿಗಂಟ್ ಮಲ್ತಿನ ತಡೆಕ್ಲೆನ್ ಮಲ್ಪು";
Blockly.Msg["CONTROLS_IF_ELSEIF_TOOLTIP"] = "'ಒಂಜಿ ವೇಲೆ' ತಡೆಕ್ಕ್ ಒಂಜಿ ಶರ್ತನ್ ಸೇರಾವ್";
Blockly.Msg["CONTROLS_IF_ELSE_TOOLTIP"] = "'ಒಂಜಿ ವೇಲೆ' ತಡೆಕ್ಕ್ ಒಂಜಿ ಕಡೆತ್ತ ಮಾತೆನ್ಲಾ-ಪತ್ತ್ (catch-all) ಶರ್ತನ್ ಸೇರಾವ್";
Blockly.Msg["CONTROLS_IF_HELPURL"] = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg["CONTROLS_IF_IF_TOOLTIP"] = "ಸೇರಾವ್, ದೆತ್ತ್‌ ಬುಡು, ಅತ್ತಂಡ ಈ 'ಒಂಜಿ ವೇಲೆ' ತಡೆನ್ ಕುಡ ಸಂರಚಣೆ ಮಲ್ಪೆರೆ ವಿಭಾಗೊಲೆನ್ ಕುಡ ಒತ್ತರೆ ಮಲ್ಪುಲೆ.";
Blockly.Msg["CONTROLS_IF_MSG_ELSE"] = "ಅತ್ತಂಡ";
Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"] = "ಅತ್ತಂಡ";
Blockly.Msg["CONTROLS_IF_MSG_IF"] = "ಒಂಜಿ ವೇಲೆ";
Blockly.Msg["CONTROLS_IF_TOOLTIP_1"] = "ಮೌಲ್ಯ ನಿಜ ಆದಿತ್ತ್ಂಡ ಕೆಲವು ಪಾತೆರೊಲೆನ್ ಮಲ್ಪು";
Blockly.Msg["CONTROLS_IF_TOOLTIP_2"] = "ಮೌಲ್ಯ ನಿಜವಾದಿತ್ತ್‌ಂಡ, ಪಾತೆರೊಲೆನ ಸುರುತ್ತ ತಡೆ ಮಲ್ಪು. ಇಜ್ಜಿಂಡ ಪಾತೆರೊಲೆನ ರಡ್ಡನೆ ತಡೆ ಮಲ್ಪು.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_3"] = "ಸುರುತ್ತ ಮೌಲ್ಯ ನಿಜವಾದಿತ್ತ್‌ಂಡ, ಪಾತೆರೊಲೆನ ಸುರುತ್ತ ತಡೆ ಮಲ್ಪು. ಇಜ್ಜಿಂಡ, ರಡ್ಡನೆ ಮೌಲ್ಯ ನಿಜವಾದಿತ್ತ್ಂಡ, ಪಾತೆರೊಲೆನ ರಡ್ಡನೆ ತಡೆ ಮಲ್ಪು.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_4"] = "ಸುರುತ್ತ ಮೌಲ್ಯೊ ನಿಜವಾದಿತ್ತ್‌ಂಡ, ಪಾತೆರೊಲೆನ ಸುರುತ್ತ ತಡೆ ಮಲ್ಪು. ಇಜ್ಜಿಂಡ, ರಡ್ಡನೆದ ಮೌಲ್ಯ ನಿಜವಾದಿತ್ತ್ಂಡ, ಪಾತೆರೊಲೆನ ರಡ್ಡನೆ ತಡೆ ಮಲ್ಪು. ಒಂಜೇಲೆ ಒವ್ವೇ ಮೌಲ್ಯ ನಿಜವಾದಿತ್ತಿಜಿಂಡ, ಪಾತೆರೊಲೆನ ಕಡೆತ್ತ ತಡೆ ಮಲ್ಪು.";
Blockly.Msg["CONTROLS_REPEAT_HELPURL"] = "https://en.wikipedia.org/wiki/For_loop";
Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"] = "ಮಲ್ಪುಲೆ";
Blockly.Msg["CONTROLS_REPEAT_TITLE"] = " %1 ಸರ್ತಿ ಕೂಡೊರ ಮಲ್ಪು";
Blockly.Msg["CONTROLS_REPEAT_TOOLTIP"] = "ಕೆಲವು ಪಾತೆರೊಲೆನ್ ಮಸ್ತ್ ಸರ್ತಿ ಮಲ್ಪು";
Blockly.Msg["CONTROLS_WHILEUNTIL_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_UNTIL"] = "ಉಂದು ನಿಜ ಆಪಿಲೆಕೊ ಕುಡೊರ ಮಲ್ಪು:";
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_WHILE"] = "ಉಂದು ನಿಜ ಆಂಡ ಕುಡೊರ ಮಲ್ಪು:";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL"] = "ಮೌಲ್ಯ ತಪ್ಪು ಆದಿತ್ತ್ಂಡ ಕೆಲವು ಪಾತೆರೊಲೆನ್ ಮಲ್ಪು";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_WHILE"] = "ಮೌಲ್ಯ ನಿಜ ಆದಿತ್ತ್ಂಡ ಕೆಲವು ಪಾತೆರೊಲೆನ್ ಮಲ್ಪು";
Blockly.Msg["CONTROL_ARDUINO_LOOP"] = "";  // untranslated
Blockly.Msg["CONTROL_ARDUINO_SETUP"] = "";  // untranslated
Blockly.Msg["CONTROL_GROUP"] = "";  // untranslated
Blockly.Msg["DELETE_ALL_BLOCKS"] = "ಮಾತ %1 ಬ್ಲಾಕ್‍ಲೆನ್ ದೆತ್ತ್‌ದ್ ಬುಡೊಡೆ?";
Blockly.Msg["DELETE_BLOCK"] = "ಬ್ಲಾಕ್‍ನ್ ಮಾಜಾವು";
Blockly.Msg["DELETE_X_BLOCKS"] = "%1 ಬ್ಲಾಕ್‍ಲೆನ್ ಮಾಜಾವು";
Blockly.Msg["DEPRECATED"] = "";  // untranslated
Blockly.Msg["DISABLE_BLOCK"] = "ಬ್ಲಾಕ್‍ನ್ ದೆತ್ತ್‌ಪಾಡ್";
Blockly.Msg["DOMOTICS_INA219_CURRENT"] = "";  // untranslated
Blockly.Msg["DOMOTICS_INA219_INIT"] = "";  // untranslated
Blockly.Msg["DOMOTICS_INA219_POWER"] = "";  // untranslated
Blockly.Msg["DOMOTICS_INA219_VOLTAGE"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_CURRENT"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_ENERGY"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_FREQUENCY"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_INIT"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_POWER"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_POWERFACTOR"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_SETADDRESS"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_VALUE"] = "";  // untranslated
Blockly.Msg["DOMOTICS_PZEM004T_VOLTAGE"] = "";  // untranslated
Blockly.Msg["DOWN"] = "";  // untranslated
Blockly.Msg["DUPLICATE_BLOCK"] = "ನಕಲ್";
Blockly.Msg["EEPROM_ADDRESS"] = "";  // untranslated
Blockly.Msg["EEPROM_READ"] = "";  // untranslated
Blockly.Msg["EEPROM_WRITE"] = "";  // untranslated
Blockly.Msg["ENABLE_BLOCK"] = "ತಡೆನ್ ಸಕ್ರಿಯೊ ಮಲ್ಪು";
Blockly.Msg["EXPAND_ALL"] = "ಮಾತಾ ತಡೆಕ್ಲೆನ ಮಾಹಿತಿನ್ ಪರಡಾವು";
Blockly.Msg["EXPAND_BLOCK"] = "ಬ್ಲಾಕ್‍ದ ಮಾಹಿತಿನ್ ಪರಡಾವು";
Blockly.Msg["EXTERNAL_INPUTS"] = "ಪಿದಯಿದ ಪರಿಪು";
Blockly.Msg["FILTER_MEDIAN"] = "";  // untranslated
Blockly.Msg["FILTER_MEDIAN_ADD"] = "";  // untranslated
Blockly.Msg["FILTER_MEDIAN_SAMPLES"] = "";  // untranslated
Blockly.Msg["FILTER_MEDIAN_SETWINDOW"] = "";  // untranslated
Blockly.Msg["FORWARD"] = "";  // untranslated
Blockly.Msg["GPS_DAY"] = "";  // untranslated
Blockly.Msg["GPS_DISTANCEBETWEEN"] = "";  // untranslated
Blockly.Msg["GPS_GETALTITUDE"] = "";  // untranslated
Blockly.Msg["GPS_GETCOURSE"] = "";  // untranslated
Blockly.Msg["GPS_GETDATETIME"] = "";  // untranslated
Blockly.Msg["GPS_GETPOSITION"] = "";  // untranslated
Blockly.Msg["GPS_GETSPEED"] = "";  // untranslated
Blockly.Msg["GPS_HOUR"] = "";  // untranslated
Blockly.Msg["GPS_HUND"] = "";  // untranslated
Blockly.Msg["GPS_INIT"] = "";  // untranslated
Blockly.Msg["GPS_KMPH"] = "";  // untranslated
Blockly.Msg["GPS_LAT"] = "";  // untranslated
Blockly.Msg["GPS_LONG"] = "";  // untranslated
Blockly.Msg["GPS_MIN"] = "";  // untranslated
Blockly.Msg["GPS_MONTH"] = "";  // untranslated
Blockly.Msg["GPS_MPH"] = "";  // untranslated
Blockly.Msg["GPS_SEC"] = "";  // untranslated
Blockly.Msg["GPS_VALIDDATA"] = "";  // untranslated
Blockly.Msg["GPS_YEAR"] = "";  // untranslated
Blockly.Msg["HEIGHT"] = "";  // untranslated
Blockly.Msg["HELP"] = "ಸಕಾಯೊ";
Blockly.Msg["ID"] = "";  // untranslated
Blockly.Msg["INLINE_INPUTS"] = "ಉಳಸಾಲ್‍ದ ಉಳಪರಿಪು";
Blockly.Msg["IO_ANALOG_READ"] = "";  // untranslated
Blockly.Msg["IO_ANALOG_READ_DIF"] = "";  // untranslated
Blockly.Msg["IO_ANALOG_WRITE"] = "";  // untranslated
Blockly.Msg["IO_BOOLEAN_OFF"] = "";  // untranslated
Blockly.Msg["IO_BOOLEAN_ON"] = "";  // untranslated
Blockly.Msg["IO_CAPACITIVE_READ"] = "";  // untranslated
Blockly.Msg["IO_DIGITAL_READ"] = "";  // untranslated
Blockly.Msg["IO_DIGITAL_WRITE"] = "";  // untranslated
Blockly.Msg["IO_INTERRUPT"] = "";  // untranslated
Blockly.Msg["IO_PINMODE"] = "";  // untranslated
Blockly.Msg["IO_PINMODE_AS"] = "";  // untranslated
Blockly.Msg["IO_PULSEIN"] = "";  // untranslated
Blockly.Msg["IO_PULSEIN_TIMEOUT"] = "";  // untranslated
Blockly.Msg["KEYBOARD"] = "";  // untranslated
Blockly.Msg["KEYBOARD_KEY"] = "";  // untranslated
Blockly.Msg["KEYBOARD_KEYSTROKE"] = "";  // untranslated
Blockly.Msg["KEYBOARD_PRESS"] = "";  // untranslated
Blockly.Msg["KEYBOARD_RELEASE"] = "";  // untranslated
Blockly.Msg["KEYBOT_BUZZER"] = "";  // untranslated
Blockly.Msg["KEYBOT_BUZZER_FREQ"] = "";  // untranslated
Blockly.Msg["KEYBOT_DISTANCE"] = "";  // untranslated
Blockly.Msg["KEYBOT_IRSENSOR"] = "";  // untranslated
Blockly.Msg["KEYBOT_IRSENSOR_LEFT"] = "";  // untranslated
Blockly.Msg["KEYBOT_IRSENSOR_MIDDLE"] = "";  // untranslated
Blockly.Msg["KEYBOT_IRSENSOR_RIGHT"] = "";  // untranslated
Blockly.Msg["KEYBOT_LEFT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOTOR"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_BACKWARD"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_FAST"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_FORWARD"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_LEFT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_NORMAL"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_RIGHT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_ROTATE_LEFT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_ROTATE_RIGHT"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_SLOW"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_SPEED"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_STOP"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_VERYFAST"] = "";  // untranslated
Blockly.Msg["KEYBOT_MOVE_VERYSLOW"] = "";  // untranslated
Blockly.Msg["KEYBOT_RIGHT"] = "";  // untranslated
Blockly.Msg["KEYPAD"] = "";  // untranslated
Blockly.Msg["KEYPAD_COL"] = "";  // untranslated
Blockly.Msg["KEYPAD_KEY"] = "";  // untranslated
Blockly.Msg["KEYPAD_NOKEY"] = "";  // untranslated
Blockly.Msg["KEYPAD_ROW"] = "";  // untranslated
Blockly.Msg["LCD"] = "";  // untranslated
Blockly.Msg["LCD_BACKLIGHT"] = "";  // untranslated
Blockly.Msg["LCD_BEGIN"] = "";  // untranslated
Blockly.Msg["LCD_BEGIN_I2C"] = "";  // untranslated
Blockly.Msg["LCD_BLINK"] = "";  // untranslated
Blockly.Msg["LCD_CLEAR"] = "";  // untranslated
Blockly.Msg["LCD_COL"] = "";  // untranslated
Blockly.Msg["LCD_CURSOR"] = "";  // untranslated
Blockly.Msg["LCD_DEFINE"] = "";  // untranslated
Blockly.Msg["LCD_DISPLAY"] = "";  // untranslated
Blockly.Msg["LCD_PRINT"] = "";  // untranslated
Blockly.Msg["LCD_ROW"] = "";  // untranslated
Blockly.Msg["LCD_SCROLL"] = "";  // untranslated
Blockly.Msg["LCD_SYMBOL"] = "";  // untranslated
Blockly.Msg["LEDMATRIX"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_CLEAR"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_DRAWBITMAP"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_DRAWCIRCLE"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_DRAWPIXEL"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_DRAWTEXT"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_FILL"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_INIT"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_LINE"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_RECTANGLE"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_ROTATION"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_ROUND"] = "";  // untranslated
Blockly.Msg["LEDMATRIX_SHOW"] = "";  // untranslated
Blockly.Msg["LEFT"] = "";  // untranslated
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"] = "ಪಟ್ಟಿ";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"] = "ಈ ಪಟ್ಟಿ ತಡೆನ್ ಕುಡ ಸಂರಚನೆ ಮಲ್ಪೆರೆ ಸೇರಾಲೆ, ದೆತ್ತ್ ಬುಡುಲೆ, ಅತ್ತಂಡ ವಿಬಾಗೊಲೆನ್ ಕುಡ ಒತ್ತರೆ ಮಲ್ಪುಲೆ.";
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH"] = "ಒಟ್ಟುಗು ಪಟ್ಟಿನ್ ಉಂಡುಮಲ್ಪುಲೆ";
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH_TEXT"] = "";  // untranslated
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TOOLTIP"] = "ಪಟ್ಟಿಗ್ ಒಂಜಿ ವಿಸಯೊನು ಸೇರಾಲೆ.";
Blockly.Msg["LISTS_GET_INDEX_FROM_START"] = "#";  // untranslated
Blockly.Msg["LISTS_GET_INDEX_GET"] = "ದೆತೊನು";
Blockly.Msg["LISTS_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg["LISTS_LENGTH_TITLE"] = "%1 ಉದ್ದೊ";
Blockly.Msg["LISTS_LENGTH_TOOLTIP"] = "ಪಟ್ಟಿದ ಉದ್ದೊನು ಪಿರಕೊರು.";
Blockly.Msg["LISTS_LISTNAME"] = "";  // untranslated
Blockly.Msg["LISTS_LISTNAME_TEXT"] = "";  // untranslated
Blockly.Msg["LISTS_SET_INDEX_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg["LISTS_SET_INDEX_SET"] = "ಸೆಟ್ ಮಲ್ಪು";
Blockly.Msg["LOGIC_BOOLEAN_FALSE"] = "ಸುಲ್ಲು";
Blockly.Msg["LOGIC_BOOLEAN_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg["LOGIC_BOOLEAN_TOOLTIP"] = "ಒಂಜೆ ನಿಜ ಅತ್ತಂಡ ಸುಲ್ಲುನ್ ಪಿರಕೊರು";
Blockly.Msg["LOGIC_BOOLEAN_TRUE"] = "ಸತ್ಯೊ";
Blockly.Msg["LOGIC_COMPARE_HELPURL"] = "https://en.wikipedia.org/wiki/Inequality_(mathematics)";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_EQ"] = "ರಡ್ದ್ ಇನ್‌ಪುಟ್‌ಲಾ ಸಮ ಇತ್ತ್ಂಡ 'ನಿಜ'ನ್ ಪಿರಕೊರು";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GT"] = "ಸುರುತ್ತ ಇನ್‌ಪುಟ್ ರಡ್ಡನೆ ಇನ್‌ಪುಟ್‌ಡ್ದ್ ಮಲ್ಲ ಆದಿತ್ತ್ಂಡ, 'ನಿಜ'ನ್ ಪಿರಕೊರು";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GTE"] = "ಸುರುತ್ತ ಇನ್‌ಪುಟ್ ರಡ್ಡನೆ ಇನ್‌ಪುಟ್‌ಡ್ದ್ ಮಲ್ಲ ಅತ್ತಂಡ ಅಯಿಕ್ಕ್ ಸಮ ಆದಿತ್ತ್ಂಡ, 'ನಿಜ'ನ್ ಪಿರಕೊರು";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LT"] = "ಸುರುತ್ತ ಇನ್‌ಪುಟ್ ರಡ್ಡನೆ ಇನ್‌ಪುಟ್‌ಡ್ದ್ ಎಲ್ಯ ಆದಿತ್ತ್ಂಡ, 'ನಿಜ'ನ್ ಪಿರಕೊರು";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LTE"] = "ಸುರುತ್ತ ಇನ್‌ಪುಟ್ ರಡ್ಡನೆ ಇನ್‌ಪುಟ್‌ಡ್ದ್ ಎಲ್ಯ ಅತ್ತಂಡ ಅಯಿಕ್ಕ್ ಸಮ ಆದಿತ್ತ್ಂಡ, 'ನಿಜ'ನ್ ಪಿರಕೊರು";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_NEQ"] = "ರಡ್ದ್ ಇನ್‌ಪುಟ್‌ಲಾ ಸಮ ಅತ್ತಾಂಡ 'ನಿಜ'ನ್ ಪಿರಕೊರು";
Blockly.Msg["LOGIC_NEGATE_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg["LOGIC_NEGATE_TITLE"] = "%1 ಅತ್ತ್";
Blockly.Msg["LOGIC_NEGATE_TOOLTIP"] = "ಇನ್‌ಪುಟ್ ಸುಲ್ಲಾದಿತ್ತ್ಂಡ, 'ನಿಜ'ನ್ ಪಿರಕೊರು. ಇನ್‌ಪುಟ್ ನಿಜ ಆದಿತ್ತ್ಂಡ, 'ಸುಲ್ಲು'ನ್ ಪಿರಕೊರು.";
Blockly.Msg["LOGIC_OPERATION_AND"] = "ಬುಕ್ಕೊ";
Blockly.Msg["LOGIC_OPERATION_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg["LOGIC_OPERATION_OR"] = "ಅತ್ತಂಡ";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_AND"] = "ರಡ್ಡ್‌ಲಾ ಇನ್‌ಪುಟ್ ನಿಜ ಆದಿತ್ತ್ಂಡ, 'ನಿಜ'ನ್ ಪಿರಕೊರು";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_OR"] = "ಒವ್ವಾಂಡಲ ಒಂಜಿ ಇನ್‌ಪುಟ್ ನಿಜ ಆಂಡಲಾ, 'ನಿಜ'ನ್ ಪಿರಕೊರು.";
Blockly.Msg["MATH_ADDITION_SYMBOL"] = "+";  // untranslated
Blockly.Msg["MATH_ANGLE"] = "";  // untranslated
Blockly.Msg["MATH_ARITHMETIC_HELPURL"] = "https://en.wikipedia.org/wiki/ಅಂಕಗಣಿತ";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_ADD"] = "ರಡ್ಡ್ ಸಂಖ್ಯೆದ ಮೊತ್ತನ್ ಪಿರಕೊರು.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_DIVIDE"] = "ಸಂಖ್ಯೆದ ಭಾಗಲಬ್ದೊನು ಪಿರಕೊರು.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MINUS"] = "ರಡ್ಡ ಸ್ಂಖ್ಯೆದ ವ್ಯತ್ಯಾಸೊನು ಪಿರಕೊರು.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MULTIPLY"] = "ಸಂಖ್ಯೆದ ಗುಣಲಬ್ಧೊನು ಪಿರಕೊರು.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_POWER"] = "ಸುರುತ್ತ ಸಂಖ್ಯೆದ ಘಾತೊನು ರಡ್ಡನೆ ಸಂಖ್ಯೆಗ್ ಏರ್ಪಾದ್ ಪಿರಕೊರು.";
Blockly.Msg["MATH_CHANGE_HELPURL"] = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
Blockly.Msg["MATH_CHANGE_TITLE"] = "%1 ನ್ %2 ಟ್ ಬದಲ್ ಮಲ್ಪು";
Blockly.Msg["MATH_CHANGE_TOOLTIP"] = "'%1' ವ್ಯತ್ಯಯೊಗು ಒಂಜಿ ಸಂಖ್ಯೆನ್ ಸೇರಾವ್";
Blockly.Msg["MATH_CONSTANT_HELPURL"] = "https://en.wikipedia.org/wiki/ಗಣಿತ_ನಿರಂತರ";
Blockly.Msg["MATH_CONSTANT_TOOLTIP"] = "ಒಂಜಿ ಸಾಮಾನ್ಯ ಸ್ಥಿರಾಂಕೊನು ಪಿರಕೊರು: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), or ∞ (infinity).";
Blockly.Msg["MATH_CONSTRAIN_HELPURL"] = "https://en.wikipedia.org/wiki/Clamping_(graphics)";  // untranslated
Blockly.Msg["MATH_CONSTRAIN_TITLE"] = "%2 ಕಮ್ಮಿ %3 ಜಾಸ್ತಿ %1 ನಿರ್ಬಂಧ ಮಲ್ಪು";
Blockly.Msg["MATH_CONSTRAIN_TOOLTIP"] = "ನಿಗದಿತ ಮಿತಿತ ನಡುಟು ಒಂಜಿ ಸಂಖ್ಯೆನ್ ನಿರ್ಬಂಧ ಮಲ್ಪು";
Blockly.Msg["MATH_DIVISION_SYMBOL"] = "÷";  // untranslated
Blockly.Msg["MATH_MAP_HELPURL"] = "";  // untranslated
Blockly.Msg["MATH_MAP_TITLE"] = "";  // untranslated
Blockly.Msg["MATH_MAP_TOOLTIP"] = "";  // untranslated
Blockly.Msg["MATH_MODULO_HELPURL"] = "https://en.wikipedia.org/wiki/ಮೋಡ್ಯುಲೊ_ಒಪರೇಶನ್";
Blockly.Msg["MATH_MODULO_TITLE"] = " %1 ÷ %2 ತ ಶೇಷ";
Blockly.Msg["MATH_MODULO_TOOLTIP"] = "ರಡ್ಡ್ ಸಂಖ್ಯೆಲೆನ್ ಭಾಗ ಮಲ್ತ್‌ದ್ ಶೇಷೊನು ಪಿರಕೊರು.";
Blockly.Msg["MATH_MULTIPLICATION_SYMBOL"] = "×";  // untranslated
Blockly.Msg["MATH_NUMBER_HELPURL"] = "https://en.wikipedia.org/wiki/ಸಂಖ್ಯೆ";
Blockly.Msg["MATH_NUMBER_TOOLTIP"] = "ಅ ನಂಬ್ರೊ";
Blockly.Msg["MATH_POWER_SYMBOL"] = "^";  // untranslated
Blockly.Msg["MATH_RANDOM_INT_HELPURL"] = "https://en.wikipedia.org/wiki/ರಾಂಡಮ್_ನಂಬರ್_ಜನರೇಶನ್";
Blockly.Msg["MATH_RANDOM_INT_TITLE"] = " %1 ಡ್ದ್ %2 ಯಾದೃಚ್ಛಿಕ ಪೂರ್ಣಾಂಕೊ";
Blockly.Msg["MATH_RANDOM_INT_TOOLTIP"] = "ರಡ್ಡ್ ನಿಗದಿತ ಮಿತಿತ ನಡುತ್ತ ಯಾದೃಚ್ಛಿಕ ಪೂರ್ಣಾಂಕೊನು ಪಿರಕೊರು";
Blockly.Msg["MATH_ROUND_HELPURL"] = "https://en.wikipedia.org/wiki/ಪೂರ್ಣಾಂಕೊ";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUND"] = "ರೌಂಡ್";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDDOWN"] = "ತಿರ್ತ್‌ಗ್ ರೌಂಡ್";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDUP"] = "ಮಿತ್ತ್‌ಗ್ ರೌಂಡ್";
Blockly.Msg["MATH_ROUND_TOOLTIP"] = "ಒಂಜಿ ಸಂಖ್ಯೆನ್ ಮಿತ್ತ್‌ಗ್ ಅತ್ತಂಡ ತಿರ್ತ್‌ಗ್ ರೌಂಡ್ ಮಲ್ಪು";
Blockly.Msg["MATH_SINGLE_HELPURL"] = "https://en.wikipedia.org/wiki/ವರ್ಗಮೂಲೊ";
Blockly.Msg["MATH_SINGLE_OP_ABSOLUTE"] = "ಸಂಪೂರ್ನೊ";
Blockly.Msg["MATH_SINGLE_OP_ROOT"] = "ವರ್ಗಮೂಲೊ";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ABS"] = "ಸಂಖ್ಯೆದ ಸರಿಯಾಯಿನ ಮೌಲ್ಯೊನು ಕೊರು";
Blockly.Msg["MATH_SINGLE_TOOLTIP_EXP"] = "ಒಂಜಿ ಸಂಖ್ಯೆದ ಘಾತೊಗು 'e'ನ್ ಪಿರಕೊರು.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LN"] = "ಸಂಖ್ಯೆದ ಪ್ರಾಕೃತಿಕ ಲಘುಗಣಕನ್ ಪಿರಕೊರು";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LOG10"] = "ಸಂಖ್ಯೆದ ದಶಮಾನ ಲಘುಗಣಕನ್ ಪಿರಕೊರು";
Blockly.Msg["MATH_SINGLE_TOOLTIP_NEG"] = "ಸಂಖ್ಯೆದ ನಿಷೇಧೊನು ಪಿರಕೊರು";
Blockly.Msg["MATH_SINGLE_TOOLTIP_POW10"] = "ಒಂಜಿ ಸಂಖ್ಯೆದ ಘಾತೊಗು ೧೦ನ್ ಪಿರಕೊರು";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ROOT"] = "ಸಂಖ್ಯೆದ ವರ್ಗಮೂಲೊನು ಪಿರಕೊರು.";
Blockly.Msg["MATH_SUBTRACTION_SYMBOL"] = "-";  // untranslated
Blockly.Msg["MATH_TO_INT"] = "";  // untranslated
Blockly.Msg["MATH_TO_UINT"] = "";  // untranslated
Blockly.Msg["MATH_TRIG_ACOS"] = "acos";  // untranslated
Blockly.Msg["MATH_TRIG_ASIN"] = "asin";  // untranslated
Blockly.Msg["MATH_TRIG_ATAN"] = "atan";  // untranslated
Blockly.Msg["MATH_TRIG_ATAN2"] = "";  // untranslated
Blockly.Msg["MATH_TRIG_COS"] = "cos";  // untranslated
Blockly.Msg["MATH_TRIG_HELPURL"] = "https://en.wikipedia.org/wiki/ತ್ರಿಕೋನಮಿತಿದ_ಕಾರ್ಯೊಲು";
Blockly.Msg["MATH_TRIG_SIN"] = "sin";  // untranslated
Blockly.Msg["MATH_TRIG_TAN"] = "tan";  // untranslated
Blockly.Msg["MATH_TRIG_TOOLTIP_ACOS"] = "ಒಂಜಿ ಸಂಖ್ಯೆದ ಆರ್ಕ್‌‌ಕೊಸೈನ್ ಪಿರಕೊರು.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ASIN"] = "ಒಂಜಿ ಸಂಖ್ಯೆದ ಆರ್ಕ್‌ಸೈನ್ ಪಿರಕೊರು.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ATAN"] = "ಒಂಜಿ ಸಂಖ್ಯೆದ ಆರ್ಕ್‌ಟ್ಯಾನ್‌ಜ್ಂಟ್ ಪಿರಕೊರು.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ATAN2"] = "";  // untranslated
Blockly.Msg["MATH_TRIG_TOOLTIP_COS"] = "ಒಂಜಿ ಡಿಗ್ರಿದ ಕೊಸೈನ್ (cosine) ಪಿರಕೊರು (ರೇಡಿಯನ್ ಅತ್ತ್).";
Blockly.Msg["MATH_TRIG_TOOLTIP_SIN"] = "ಒಂಜಿ ಡಿಗ್ರಿದ ಸೈನ್ (sine) ಪಿರಕೊರು (ರೇಡಿಯನ್ ಅತ್ತ್).";
Blockly.Msg["MATH_TRIG_TOOLTIP_TAN"] = "ಒಂಜಿ ಡಿಗ್ರಿದ ಟ್ಯಾನ್‌ಜೆಂಟ್ (tangent) ಪಿರಕೊರು (ರೇಡಿಯನ್ ಅತ್ತ್).";
Blockly.Msg["MOTORSHIELD_DC"] = "";  // untranslated
Blockly.Msg["MOTORSHIELD_SERVO"] = "";  // untranslated
Blockly.Msg["MOTORSHIELD_STEPPER"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_BW"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_FW"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_INIT"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_MOTOR"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_MOVE"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298N_SPEED"] = "";  // untranslated
Blockly.Msg["MOTOR_LM298P"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_DEGREE_RANGE"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_DELAY"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_AMPLITUDE"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_OFFSET"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_PERIOD"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_PHASE"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_REFRESH"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_RESET"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_SET"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_START"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_OSCILLATOR_STOP"] = "";  // untranslated
Blockly.Msg["MOTOR_SERVO_READ"] = "";  // untranslated
Blockly.Msg["MOTOR_STEPPER"] = "";  // untranslated
Blockly.Msg["MOTOR_STEPPER_RPM"] = "";  // untranslated
Blockly.Msg["MOTOR_STEPPER_STEP"] = "";  // untranslated
Blockly.Msg["MOTOR_STEPPER_STEPS"] = "";  // untranslated
Blockly.Msg["MOUSE"] = "";  // untranslated
Blockly.Msg["MOUSE_BUTTON"] = "";  // untranslated
Blockly.Msg["MOUSE_CLICK"] = "";  // untranslated
Blockly.Msg["MOUSE_MIDDLE"] = "";  // untranslated
Blockly.Msg["MOUSE_MOVE"] = "";  // untranslated
Blockly.Msg["MOUSE_WHEEL"] = "";  // untranslated
Blockly.Msg["MP3_CONTROL"] = "";  // untranslated
Blockly.Msg["MP3_EQ"] = "";  // untranslated
Blockly.Msg["MP3_FILE"] = "";  // untranslated
Blockly.Msg["MP3_FOLDER"] = "";  // untranslated
Blockly.Msg["MP3_INIT"] = "";  // untranslated
Blockly.Msg["MP3_NEXT"] = "";  // untranslated
Blockly.Msg["MP3_PAUSE"] = "";  // untranslated
Blockly.Msg["MP3_PLAY"] = "";  // untranslated
Blockly.Msg["MP3_PREV"] = "";  // untranslated
Blockly.Msg["MP3_REPEAT"] = "";  // untranslated
Blockly.Msg["MP3_RESET"] = "";  // untranslated
Blockly.Msg["MP3_SHUFFLE"] = "";  // untranslated
Blockly.Msg["MP3_STOP"] = "";  // untranslated
Blockly.Msg["MP3_VOLUME"] = "";  // untranslated
Blockly.Msg["MQTT_BROKER"] = "";  // untranslated
Blockly.Msg["MQTT_CLIENTID"] = "";  // untranslated
Blockly.Msg["MQTT_INIT"] = "";  // untranslated
Blockly.Msg["MQTT_ISCONNECTED"] = "";  // untranslated
Blockly.Msg["MQTT_MAC"] = "";  // untranslated
Blockly.Msg["MQTT_PASS"] = "";  // untranslated
Blockly.Msg["MQTT_PORT"] = "";  // untranslated
Blockly.Msg["MQTT_PUB"] = "";  // untranslated
Blockly.Msg["MQTT_SUB"] = "";  // untranslated
Blockly.Msg["MQTT_TOPIC"] = "";  // untranslated
Blockly.Msg["MQTT_USER"] = "";  // untranslated
Blockly.Msg["MQTT_VALUE"] = "";  // untranslated
Blockly.Msg["MQTT_WIFI_NAME"] = "";  // untranslated
Blockly.Msg["MQTT_WIFI_PASS"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_CLEAR"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_INIT"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_LEDCOUNT"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_PIXEL"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_SETMATRIX"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_SETPIXEL"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_SETRAW"] = "";  // untranslated
Blockly.Msg["NEOPIXEL_SHOW"] = "";  // untranslated
Blockly.Msg["NEW_VARIABLE"] = "ವ್ಯತ್ಯಯೊನು ಉಂಡು ಮಲ್ಪುಲೆ";
Blockly.Msg["NEW_VARIABLE_TITLE"] = "ಪೊಸ ವ್ಯತ್ಯಯೊದ ಪುದರ್:";
Blockly.Msg["NOTE_A"] = "";  // untranslated
Blockly.Msg["NOTE_AS"] = "";  // untranslated
Blockly.Msg["NOTE_B"] = "";  // untranslated
Blockly.Msg["NOTE_C"] = "";  // untranslated
Blockly.Msg["NOTE_CS"] = "";  // untranslated
Blockly.Msg["NOTE_D"] = "";  // untranslated
Blockly.Msg["NOTE_DS"] = "";  // untranslated
Blockly.Msg["NOTE_E"] = "";  // untranslated
Blockly.Msg["NOTE_F"] = "";  // untranslated
Blockly.Msg["NOTE_FS"] = "";  // untranslated
Blockly.Msg["NOTE_G"] = "";  // untranslated
Blockly.Msg["NOTE_GS"] = "";  // untranslated
Blockly.Msg["NUMBER"] = "";  // untranslated
Blockly.Msg["NUNCHUK"] = "";  // untranslated
Blockly.Msg["NUNCHUK_X"] = "";  // untranslated
Blockly.Msg["NUNCHUK_Y"] = "";  // untranslated
Blockly.Msg["NUNCHUK_aX"] = "";  // untranslated
Blockly.Msg["NUNCHUK_aY"] = "";  // untranslated
Blockly.Msg["NUNCHUK_aZ"] = "";  // untranslated
Blockly.Msg["NUNCHUK_bC"] = "";  // untranslated
Blockly.Msg["NUNCHUK_bZ"] = "";  // untranslated
Blockly.Msg["OK"] = "";  // untranslated
Blockly.Msg["OLED_AUTOSHOW"] = "";  // untranslated
Blockly.Msg["OTTO_AMP"] = "";  // untranslated
Blockly.Msg["OTTO_AMP_BIG"] = "";  // untranslated
Blockly.Msg["OTTO_AMP_NORMAL"] = "";  // untranslated
Blockly.Msg["OTTO_AMP_SMALL"] = "";  // untranslated
Blockly.Msg["OTTO_BUTTON"] = "";  // untranslated
Blockly.Msg["OTTO_CALIBRATE"] = "";  // untranslated
Blockly.Msg["OTTO_CALIB_FOOTL"] = "";  // untranslated
Blockly.Msg["OTTO_CALIB_FOOTR"] = "";  // untranslated
Blockly.Msg["OTTO_CALIB_LEGL"] = "";  // untranslated
Blockly.Msg["OTTO_CALIB_LEGR"] = "";  // untranslated
Blockly.Msg["OTTO_DISTANCE"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_ANGRY"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_CONFUSED"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_FAIL"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_FART"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_FRETFUL"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_HAPPY"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_LOVE"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_MAGIC"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_SAD"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_SLEEPING"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_SUPERHAPPY"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_VICTORY"] = "";  // untranslated
Blockly.Msg["OTTO_GESTURE_WAVE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_ANGRY"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_BIGSURPRISE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_CLEAR"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_CONFUSED"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_CULITO"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_DIAGONAL"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_EIGHT"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_FIVE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_FOUR"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_HAPPYCLOSED"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_HAPPYOPEN"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_HEART"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_INTERROGATION"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_LINEMOUTH"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_NINE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_OKMOUTH"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_ONE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SAD"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SADCLOSED"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SADOPEN"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SEVEN"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SIX"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SMALLSURPRISE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_SMILE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_THREE"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_THUNDER"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_TONGUEOUT"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_TWO"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_VAMP1"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_VAMP2"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_XMOUTH"] = "";  // untranslated
Blockly.Msg["OTTO_MOUTH_ZERO"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE2"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_ASCTURN"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_BENDL"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_BENDR"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_CRUSAITO1"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_CRUSAITO2"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_FLAPPING1"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_FLAPPING2"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_HOME"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_JITTER"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_JUMP"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_MOONWALKL"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_MOONWALKR"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_SHAKEL"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_SHAKER"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_SWING"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_TIPTOESWING"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_TURNL"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_TURNR"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_UPDOWN"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_WALKB"] = "";  // untranslated
Blockly.Msg["OTTO_MOVE_WALKF"] = "";  // untranslated
Blockly.Msg["OTTO_NOISE"] = "";  // untranslated
Blockly.Msg["OTTO_NOTE"] = "";  // untranslated
Blockly.Msg["OTTO_NOTE_DURATION"] = "";  // untranslated
Blockly.Msg["OTTO_SING"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_BUTTON"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_CONFUSED"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_CONNECTION"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_CUDDLY"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_DISCONNECTION"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_FART1"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_FART2"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_FART3"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_HAPPY"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_HAPPYSHOR"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_MODE1"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_MODE2"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_MODE3"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_OH2"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_OH_"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_SAD"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_SLEEPING"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_SUPERHAPPY"] = "";  // untranslated
Blockly.Msg["OTTO_SOUND_SURPRISE"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_FAST"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_NORMAL"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_SLOW"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_VERYFAST"] = "";  // untranslated
Blockly.Msg["OTTO_SPEED_VERYSLOW"] = "";  // untranslated
Blockly.Msg["PIN"] = "";  // untranslated
Blockly.Msg["PRESSED"] = "";  // untranslated
Blockly.Msg["PROCEDURES_ALLOW_STATEMENTS"] = "ಹೇಳಿಕೆಗ್ ಅವಕಾಸೊ";
Blockly.Msg["PROCEDURES_BEFORE_PARAMS"] = "ಒಟ್ಟುಗು:";
Blockly.Msg["PROCEDURES_CALLNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/ವರ್ಗಮೂಲೊ";
Blockly.Msg["PROCEDURES_CALLNORETURN_TOOLTIP"] = "'%1' ಬಳಕೆದಾರೆರೆ ಕಾರ್ಯೊನು ನಡಪಾಲೆ.";
Blockly.Msg["PROCEDURES_CALLRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/ವರ್ಗಮೂಲೊ";
Blockly.Msg["PROCEDURES_CALLRETURN_TOOLTIP"] = " ಬಳಕೆದಾರೆರೆ ಕಾರ್ಯೊ '%1' ನು ನಡಪಾಲೆ ಬುಕ್ಕೊ ಅಯಿತ ಉತ್ಪಾದನೆನ್ ಗಲಸ್‌ಲೆ.";
Blockly.Msg["PROCEDURES_CALL_BEFORE_PARAMS"] = "ಒಟ್ಟುಗು:";
Blockly.Msg["PROCEDURES_CREATE_DO"] = " '%1'ನ್ ಉಂಡುಮಲ್ಪುಲೆ";
Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"] = "ಈ ಕಾರ್ಯೊನು ಇವರಿಪುಲೆ...";
Blockly.Msg["PROCEDURES_DEFNORETURN_DO"] = "";  // untranslated
Blockly.Msg["PROCEDURES_DEFNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"] = "ಎಂಚಿನಾಂಡಲ ಮಲ್ಪುಲೆ";
Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"] = "ಇಂದೆಕ್";
Blockly.Msg["PROCEDURES_DEFNORETURN_TOOLTIP"] = "ಔಟ್‌ಪುಟ್ ದಾಂತಿನ ಕಾರ್ಯೊನು ಉಂಡುಮಲ್ಪುಂಡು.";
Blockly.Msg["PROCEDURES_DEFRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
Blockly.Msg["PROCEDURES_DEFRETURN_RETURN"] = "ಪಿರಕೊರು";
Blockly.Msg["PROCEDURES_DEFRETURN_TOOLTIP"] = "ಔಟ್‌ಪುಟ್ ಇತ್ತಿನ ಕಾರ್ಯೊನು ಉಂಡುಮಲ್ಪುಂಡು.";
Blockly.Msg["PROCEDURES_DEF_DUPLICATE_WARNING"] = "ಎಚ್ಚರಿಕೆ: ಈ ಕಾರ್ಯೊಡು ನಕಲಿ ಮಾನದಂಡೊ ಉಂಡು.";
Blockly.Msg["PROCEDURES_HIGHLIGHT_DEF"] = "ದೆರ್ತ್ ತೋಜುನ ಕಾರ್ಯೊದ ವ್ಯಾಕ್ಯಾನೊ";
Blockly.Msg["PROCEDURES_MUTATORARG_TITLE"] = "ಉಲಪರಿಪುದ ಪುದರ್:";
Blockly.Msg["PROCEDURES_MUTATORARG_TOOLTIP"] = "ಕಾರ್ಯೊಗು ಒಂಜಿ ಉಲಪರಿಪುನು ಸೇರಲೆ.";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TITLE"] = "ಉಲಪರಿಪು";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TOOLTIP"] = "ಸೇರಾಲೆ, ದೆತ್ತ್‌ ಬುಡುಲೆ, ಅತ್ತಂಡ ಈ ಕಾರ್ಯೊಗು ಉಲಪರಿಪುಲೆನ್ ಕುಡ ಒತ್ತರೆ ಮಲ್ಪುಲೆ.";
Blockly.Msg["REMOVE_COMMENT"] = "ಟಿಪ್ಪಣಿನ್ ದೆತ್ತ್‌ದ್ ಬುಡ್ಲೆ";
Blockly.Msg["RENAME_VARIABLE"] = "ವ್ಯತ್ಯಯೊಗು ಕುಡೊರ ಪುದರ್ ದೀಲೆ";
Blockly.Msg["RENAME_VARIABLE_TITLE"] = "ಮಾತಾ '%1' ವ್ಯತ್ಯಯೊಲೆನ ಪುದರ್‌ನ್ ನೆಕ್ಕ್ ಬದಲ್ ಮಲ್ಪುಲೆ:";
Blockly.Msg["RFID_EJECTCARD"] = "";  // untranslated
Blockly.Msg["RFID_INIT"] = "";  // untranslated
Blockly.Msg["RFID_NEWCARDPRESENT"] = "";  // untranslated
Blockly.Msg["RFID_READUID"] = "";  // untranslated
Blockly.Msg["RIGHT"] = "";  // untranslated
Blockly.Msg["RTC"] = "";  // untranslated
Blockly.Msg["RTC_DATE_TEXT"] = "";  // untranslated
Blockly.Msg["RTC_DAY"] = "";  // untranslated
Blockly.Msg["RTC_DAYOFWEEK"] = "";  // untranslated
Blockly.Msg["RTC_FRIDAY"] = "";  // untranslated
Blockly.Msg["RTC_HOUR"] = "";  // untranslated
Blockly.Msg["RTC_MINUTE"] = "";  // untranslated
Blockly.Msg["RTC_MONDAY"] = "";  // untranslated
Blockly.Msg["RTC_MONTH"] = "";  // untranslated
Blockly.Msg["RTC_SATURDAY"] = "";  // untranslated
Blockly.Msg["RTC_SECOND"] = "";  // untranslated
Blockly.Msg["RTC_SUNDAY"] = "";  // untranslated
Blockly.Msg["RTC_THURSDAY"] = "";  // untranslated
Blockly.Msg["RTC_TIME_TEXT"] = "";  // untranslated
Blockly.Msg["RTC_TUESDAY"] = "";  // untranslated
Blockly.Msg["RTC_WEDNESDAY"] = "";  // untranslated
Blockly.Msg["RTC_YEAR"] = "";  // untranslated
Blockly.Msg["SD_BEGIN"] = "";  // untranslated
Blockly.Msg["SD_EXISTS"] = "";  // untranslated
Blockly.Msg["SD_POS"] = "";  // untranslated
Blockly.Msg["SD_PRINT"] = "";  // untranslated
Blockly.Msg["SD_READBYTE"] = "";  // untranslated
Blockly.Msg["SD_READLOOP"] = "";  // untranslated
Blockly.Msg["SD_REMOVE"] = "";  // untranslated
Blockly.Msg["SD_SIZE"] = "";  // untranslated
Blockly.Msg["SD_WRITEBYTE"] = "";  // untranslated
Blockly.Msg["SENSOR_18B20"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL_ADXL345"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL_X"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL_Y"] = "";  // untranslated
Blockly.Msg["SENSOR_ACCEL_Z"] = "";  // untranslated
Blockly.Msg["SENSOR_AIR"] = "";  // untranslated
Blockly.Msg["SENSOR_ALCOHOL"] = "";  // untranslated
Blockly.Msg["SENSOR_ALTITUDE"] = "";  // untranslated
Blockly.Msg["SENSOR_BAROMETRIC"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON_DEBOUNCED"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON_DEBOUNCED_PRESSED"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON_DEBOUNCED_RELEASED"] = "";  // untranslated
Blockly.Msg["SENSOR_BUTTON_INVERT"] = "";  // untranslated
Blockly.Msg["SENSOR_CCS811"] = "";  // untranslated
Blockly.Msg["SENSOR_CCS811_CO2"] = "";  // untranslated
Blockly.Msg["SENSOR_CCS811_CO2_UGM3"] = "";  // untranslated
Blockly.Msg["SENSOR_CCS811_TVOC"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_BLACK"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_BLUE"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_CYAN"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_GREEN"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_HSV_H"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_HSV_S"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_HSV_V"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_ISCOLOR"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_NAME"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_ORANGE"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_PURPLE"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_READCOLOR"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RED"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RGB_B"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RGB_CLEAR"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RGB_G"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_RGB_R"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_WHITE"] = "";  // untranslated
Blockly.Msg["SENSOR_COLOR_YELLOW"] = "";  // untranslated
Blockly.Msg["SENSOR_CRASH"] = "";  // untranslated
Blockly.Msg["SENSOR_DATA_RAW"] = "";  // untranslated
Blockly.Msg["SENSOR_DHT11"] = "";  // untranslated
Blockly.Msg["SENSOR_DHT22"] = "";  // untranslated
Blockly.Msg["SENSOR_DS18B20"] = "";  // untranslated
Blockly.Msg["SENSOR_FLAME"] = "";  // untranslated
Blockly.Msg["SENSOR_GAS"] = "";  // untranslated
Blockly.Msg["SENSOR_HALL"] = "";  // untranslated
Blockly.Msg["SENSOR_HUMIDITY"] = "";  // untranslated
Blockly.Msg["SENSOR_IRRX"] = "";  // untranslated
Blockly.Msg["SENSOR_JOYSTICK"] = "";  // untranslated
Blockly.Msg["SENSOR_KNOCK"] = "";  // untranslated
Blockly.Msg["SENSOR_LDR"] = "";  // untranslated
Blockly.Msg["SENSOR_LINETRACKING"] = "";  // untranslated
Blockly.Msg["SENSOR_LM35"] = "";  // untranslated
Blockly.Msg["SENSOR_MICS4514"] = "";  // untranslated
Blockly.Msg["SENSOR_MLX90614"] = "";  // untranslated
Blockly.Msg["SENSOR_MLX90614_AMBIENT"] = "";  // untranslated
Blockly.Msg["SENSOR_MLX90614_OBJECT"] = "";  // untranslated
Blockly.Msg["SENSOR_NTC"] = "";  // untranslated
Blockly.Msg["SENSOR_OBSTACLE"] = "";  // untranslated
Blockly.Msg["SENSOR_PAJ7620"] = "";  // untranslated
Blockly.Msg["SENSOR_PHOTOINT"] = "";  // untranslated
Blockly.Msg["SENSOR_PIR"] = "";  // untranslated
Blockly.Msg["SENSOR_PM25"] = "";  // untranslated
Blockly.Msg["SENSOR_PM25_DENSITY"] = "";  // untranslated
Blockly.Msg["SENSOR_PM25_PARTICLESM3"] = "";  // untranslated
Blockly.Msg["SENSOR_POT"] = "";  // untranslated
Blockly.Msg["SENSOR_PRESSURE"] = "";  // untranslated
Blockly.Msg["SENSOR_REED"] = "";  // untranslated
Blockly.Msg["SENSOR_ROTARY_ENCODER"] = "";  // untranslated
Blockly.Msg["SENSOR_ROTARY_ENCODER_POS"] = "";  // untranslated
Blockly.Msg["SENSOR_SOILHUMIDITY"] = "";  // untranslated
Blockly.Msg["SENSOR_SOUND"] = "";  // untranslated
Blockly.Msg["SENSOR_TEMPERATURE"] = "";  // untranslated
Blockly.Msg["SENSOR_TEMT6000"] = "";  // untranslated
Blockly.Msg["SENSOR_TILT"] = "";  // untranslated
Blockly.Msg["SENSOR_TMP36"] = "";  // untranslated
Blockly.Msg["SENSOR_TOUCH"] = "";  // untranslated
Blockly.Msg["SENSOR_ULTRASONIC"] = "";  // untranslated
Blockly.Msg["SENSOR_ULTRASONIC_MAXDISTANCE"] = "";  // untranslated
Blockly.Msg["SENSOR_VIBRATION"] = "";  // untranslated
Blockly.Msg["SENSOR_VL53L0X"] = "";  // untranslated
Blockly.Msg["SENSOR_WATER"] = "";  // untranslated
Blockly.Msg["SERIAL_AVAILABLE"] = "";  // untranslated
Blockly.Msg["SERIAL_BAUDRATE"] = "";  // untranslated
Blockly.Msg["SERIAL_FLUSH"] = "";  // untranslated
Blockly.Msg["SERIAL_INIT"] = "";  // untranslated
Blockly.Msg["SERIAL_INT"] = "";  // untranslated
Blockly.Msg["SERIAL_PLOT"] = "";  // untranslated
Blockly.Msg["SERIAL_PLOTVALUE"] = "";  // untranslated
Blockly.Msg["SERIAL_PLOTVAR"] = "";  // untranslated
Blockly.Msg["SERIAL_PRINT"] = "";  // untranslated
Blockly.Msg["SERIAL_PRINTLN"] = "";  // untranslated
Blockly.Msg["SERIAL_READ"] = "";  // untranslated
Blockly.Msg["SERIAL_READBYTE"] = "";  // untranslated
Blockly.Msg["SERIAL_READFLOAT"] = "";  // untranslated
Blockly.Msg["SERIAL_READINT"] = "";  // untranslated
Blockly.Msg["SERIAL_READSTRING"] = "";  // untranslated
Blockly.Msg["SERIAL_READSTRINGLINE"] = "";  // untranslated
Blockly.Msg["SERIAL_TIMEOUT"] = "";  // untranslated
Blockly.Msg["SERIAL_WRITEBYTE"] = "";  // untranslated
Blockly.Msg["SHOP"] = "";  // untranslated
Blockly.Msg["SOUND_FREQ"] = "";  // untranslated
Blockly.Msg["SOUND_NOTE"] = "";  // untranslated
Blockly.Msg["SOUND_NOTONE"] = "";  // untranslated
Blockly.Msg["SOUND_PLAY"] = "";  // untranslated
Blockly.Msg["SOUND_TONE"] = "";  // untranslated
Blockly.Msg["STATUS"] = "";  // untranslated
Blockly.Msg["TEXT"] = "";  // untranslated
Blockly.Msg["TEXT_ASCII"] = "";  // untranslated
Blockly.Msg["TEXT_COMMENT"] = "";  // untranslated
Blockly.Msg["TEXT_CONTAINS"] = "";  // untranslated
Blockly.Msg["TEXT_CONTAINS_1"] = "";  // untranslated
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TOOLTIP"] = "ಪಟ್ಯೊಗು ಒಂಜಿ ವಿಷಯೊನು ಸೇರಾವ್";
Blockly.Msg["TEXT_CREATE_JOIN_TITLE_JOIN"] = "ಸೇರಾವ್";
Blockly.Msg["TEXT_CREATE_JOIN_TOOLTIP"] = "ಈ ಪಠ್ಯ ತಡೆನ್ ಕುಡ ಸಂರಚಣೆ ಮಲ್ಪೆರೆ, ಸೇರಾವ್, ದೆತ್ತ್ ಬುಡು, ಅತ್ತಂಡ ವಿಭಾಗೊಲೆನ್ ಕುಡ ಒತ್ತರೆ ಮಲ್ಪು.";
Blockly.Msg["TEXT_DECIMAL"] = "";  // untranslated
Blockly.Msg["TEXT_ENDSWITH"] = "";  // untranslated
Blockly.Msg["TEXT_EQUALS"] = "";  // untranslated
Blockly.Msg["TEXT_EQUALS_IGNORE"] = "";  // untranslated
Blockly.Msg["TEXT_FORMAT"] = "";  // untranslated
Blockly.Msg["TEXT_INDEXOF"] = "";  // untranslated
Blockly.Msg["TEXT_INDEXOF_1"] = "";  // untranslated
Blockly.Msg["TEXT_INDEXOF_FIRST"] = "";  // untranslated
Blockly.Msg["TEXT_INDEXOF_LAST"] = "";  // untranslated
Blockly.Msg["TEXT_JOIN_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg["TEXT_JOIN_TITLE_CREATEWITH"] = "ನೆಡ್ದ್ ಪಟ್ಯೊನು ಉಂಡು ಮಲ್ಪು";
Blockly.Msg["TEXT_JOIN_TOOLTIP"] = "ಏತಾಂಡಲ ವಿಷಯಲೆನ್ ಒಟ್ಟುಗು ಸೇರಾದ್ ಒಂಜಿ ಪಟ್ಯೊದ ತುಂಡುನು ಉಂಡುಮಲ್ಪು.";
Blockly.Msg["TEXT_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg["TEXT_LENGTH_TITLE"] = "%1 ಉದ್ದೊ";
Blockly.Msg["TEXT_LENGTH_TOOLTIP"] = "ಕೊರಿನ ಪಟ್ಯೊದ ಅಕ್ಷರೊಲೆನ (ಅಂತರೊಲು ಸೇರ್‌ದ್) ಸಂಖ್ಯೆನ್ ಪಿರಕೊರು.";
Blockly.Msg["TEXT_LOWERCASE"] = "";  // untranslated
Blockly.Msg["TEXT_NOT_EQUALS"] = "";  // untranslated
Blockly.Msg["TEXT_REPLACE"] = "";  // untranslated
Blockly.Msg["TEXT_REPLACE_1"] = "";  // untranslated
Blockly.Msg["TEXT_REPLACE_2"] = "";  // untranslated
Blockly.Msg["TEXT_STARTSWITH"] = "";  // untranslated
Blockly.Msg["TEXT_SUBSTRING"] = "";  // untranslated
Blockly.Msg["TEXT_SUBSTRING_1"] = "";  // untranslated
Blockly.Msg["TEXT_SUBSTRING_2"] = "";  // untranslated
Blockly.Msg["TEXT_TEXT_HELPURL"] = "https://en.wikipedia.org/wiki/ಸ್ಟ್ರಿಂಗ್_(ಕಂಪ್ಯೂಟರ್_ಸೈನ್ಸ್)";
Blockly.Msg["TEXT_TEXT_TOOLTIP"] = "ಒಂಜಿ ಅಕ್ಷರೊ, ಪದೊ ಅತ್ತಂಡ ಪಾಟೊದ ಒಂಜಿ ಸಾಲ್";
Blockly.Msg["TEXT_TONUMBER"] = "";  // untranslated
Blockly.Msg["TEXT_UPPERCASE"] = "";  // untranslated
Blockly.Msg["TIME_MICROS"] = "";  // untranslated
Blockly.Msg["TIME_MILLIS"] = "";  // untranslated
Blockly.Msg["TIME_RUNEVERYMS"] = "";  // untranslated
Blockly.Msg["TIME_SNOOZE"] = "";  // untranslated
Blockly.Msg["TIME_TIMER"] = "";  // untranslated
Blockly.Msg["TIME_TIMER_RESET"] = "";  // untranslated
Blockly.Msg["TIME_TIME_ELAPSED"] = "";  // untranslated
Blockly.Msg["TIME_WAIT"] = "";  // untranslated
Blockly.Msg["TIME_WAIT_FOREVER"] = "";  // untranslated
Blockly.Msg["TIME_WAIT_UNTIL"] = "";  // untranslated
Blockly.Msg["TIME_WAIT_WHILE"] = "";  // untranslated
Blockly.Msg["TO"] = "";  // untranslated
Blockly.Msg["TODAY"] = "ಇನಿ";
Blockly.Msg["UNTIL_NEW_LINE"] = "";  // untranslated
Blockly.Msg["UP"] = "";  // untranslated
Blockly.Msg["VALUE"] = "";  // untranslated
Blockly.Msg["VARIABLES_DEFAULT_NAME"] = "ವಸ್ತು";
Blockly.Msg["VARIABLES_DEFAULT_NAME_BOOL"] = "";  // untranslated
Blockly.Msg["VARIABLES_DEFAULT_NAME_TEXT"] = "";  // untranslated
Blockly.Msg["VARIABLES_GET_CREATE_SET"] = "'ಸೆಟ್ %1' ಉಂಡುಮಲ್ಪುಲೆ";
Blockly.Msg["VARIABLES_GET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg["VARIABLES_GET_TOOLTIP"] = "ಈ ವ್ಯತ್ಯಯೊದ ಮೌಲ್ಯೊನು ಪಿರಕೊರು.";
Blockly.Msg["VARIABLES_SET"] = "%1 ನ್ %2 ಕ್ಕ್ ಸೆಟ್ ಮಲ್ಪುಲೆ";
Blockly.Msg["VARIABLES_SET_CREATE_GET"] = "'ದೆತ್ತೊನು %1' ಉಂಡುಮಲ್ಪುಲೆ";
Blockly.Msg["VARIABLES_SET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg["VARIABLES_SET_TOOLTIP"] = "ಈ ವ್ಯತ್ಯಯೊನು ಇನ್‌ಪುಟ್‌ಗ್ ಸಮ ಆಪಿಲೆಕ ಸೆಟ್ ಮಲ್ಪುಂಡು.";
Blockly.Msg["WAVE"] = "";  // untranslated
Blockly.Msg["WIDTH"] = "";  // untranslated
Blockly.Msg["WIFI_NAME"] = "";  // untranslated
Blockly.Msg["WIFI_PASS"] = "";  // untranslated
Blockly.Msg["WITH"] = "";  // untranslated
Blockly.Msg["_3DBOT_BUTTON"] = "";  // untranslated
Blockly.Msg["_3DBOT_BUZZER"] = "";  // untranslated
Blockly.Msg["_3DBOT_BUZZER_FREQ"] = "";  // untranslated
Blockly.Msg["_3DBOT_DISTANCE"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRRX"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRSENSOR"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRSENSOR_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRSENSOR_MIDDLE"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRSENSOR_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_IRTX"] = "";  // untranslated
Blockly.Msg["_3DBOT_LDR"] = "";  // untranslated
Blockly.Msg["_3DBOT_LED_GREEN"] = "";  // untranslated
Blockly.Msg["_3DBOT_LED_PWM"] = "";  // untranslated
Blockly.Msg["_3DBOT_LED_RED"] = "";  // untranslated
Blockly.Msg["_3DBOT_LED_YELLOW"] = "";  // untranslated
Blockly.Msg["_3DBOT_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOTOR"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_BACKWARD"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_BACKWARD_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_BACKWARD_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_FAST"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_FORWARD"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_NORMAL"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_ROTATE_LEFT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_ROTATE_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_SLOW"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_SPEED"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_STOP"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_VERYFAST"] = "";  // untranslated
Blockly.Msg["_3DBOT_MOVE_VERYSLOW"] = "";  // untranslated
Blockly.Msg["_3DBOT_NTC"] = "";  // untranslated
Blockly.Msg["_3DBOT_RIGHT"] = "";  // untranslated
Blockly.Msg["_3DBOT_STEPS"] = "";  // untranslated
Blockly.Msg["_3DBOT_WAIT"] = "";  // untranslated
Blockly.Msg["CONTROLS_FOR_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_IF_ELSEIF_TITLE_ELSEIF"] = Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"];
Blockly.Msg["CONTROLS_IF_ELSE_TITLE_ELSE"] = Blockly.Msg["CONTROLS_IF_MSG_ELSE"];
Blockly.Msg["CONTROLS_IF_IF_TITLE_IF"] = Blockly.Msg["CONTROLS_IF_MSG_IF"];
Blockly.Msg["CONTROLS_IF_MSG_THEN"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_WHILEUNTIL_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TITLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["LISTS_GET_INDEX_HELPURL"] = Blockly.Msg["LISTS_INDEX_OF_HELPURL"];
Blockly.Msg["LISTS_GET_INDEX_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["MATH_CHANGE_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["PROCEDURES_DEFRETURN_COMMENT"] = Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"];
Blockly.Msg["PROCEDURES_DEFRETURN_DO"] = Blockly.Msg["PROCEDURES_DEFNORETURN_DO"];
Blockly.Msg["PROCEDURES_DEFRETURN_PROCEDURE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"];
Blockly.Msg["PROCEDURES_DEFRETURN_TITLE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"];
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
